### ISSUE TITLE
Using from within AppEngine?

### ISSUE THREAD

**Issue by kidoman** [fsouza/go-dockerclient#123]
Any thoughts on this? 

My use case is: connect to a TLS authenticated Docker host over the internet from a AppEngine instance

Since AppEngine supports the sockets service, I was wondering if we could add support for passing in a raw net.Conn (or something higher up) which would permit such usage

**Comment by kidoman** [comment]
I have some time now to investigate into this. Will report back with answers to your questions.

**Comment by kidoman** [comment]
@fsouza: I looked at how we are using the docker packages. We are using it to create a tar for a directory with some options.

There are two routes ahead:
* We reimplement it using stdlib
* Copy necessary files from docker and make them workable on appengine

**Comment by fsouza** [comment]
I'd go for option 2, unless it's too hard, then fallback to option 1. Do you wanna work on it?

**Comment by kidoman** [comment]
Yessir! I am gonna talk to a few Docker guys tomorrow at gophercon.in and ask what they would like to happen.

**Comment by nikolasborrel** [comment]
I'm working on implementing push notification functionality for Apple devices on App Engine as

    config := tls.Config{Certificates: []tls.Certificate{cert}}
	if conn, err = tls.Dial("tcp", "gateway.sandbox.push.apple.com:2195", &config); err != nil {
		log.Errorf(c, "Could not connect to gateway.sandbox.push.apple.com: %v", err)
		response.WriteError(ws.HTTPStatusCodeInternalServerError, errors.New("Could not connect to gateway.sandbox.push.apple.com"))
		return
	}
	defer conn.Close()

but I get the error

    dial tcp: stat /etc/resolv.conf: operation not permitted

due to limitations on App Engine.

@kidoman Are there any solutions at the moment?
