### ISSUE TITLE
client: AttachToContainer does not work with proxies

### ISSUE THREAD

**Issue by fsouza** [fsouza/go-dockerclient#126]
Currently, we dial directly to the Docker API server using net.Dial, which bypasses the proxy configured for usage in the HTTP client's transport.

Actually, AttachToContainer should work more near to the provided Client. It also doesn't work on App Engine (see #123).

**Comment by matthieudelaro** [comment]
+1 for this one

**Comment by matthieudelaro** [comment]
I did not find `net.Dial`, but how about replacing `client.go:617`
```go
clientconn := httputil.NewClientConn(dial, nil)
```
with 

```go
clientconn := httputil.NewProxyClientConn(dial, nil) // MODIF
```
