### ISSUE TITLE
Config.Volumes Usage

### ISSUE THREAD

**Issue by zealws** [fsouza/go-dockerclient#132]
I'm trying to create a new container using the [CreateContainer method](http://godoc.org/github.com/fsouza/go-dockerclient#Client.CreateContainer).

I want the container to mount a directory on the host inside the container, just like using the `docker run -v /xyz:/abc` format.

I've been looking at the [Config type](http://godoc.org/github.com/fsouza/go-dockerclient#Config)'s Volumes field and can't figure out the appropriate value for the `struct{}` as the value type of the map.

I've tried passing in a variety of parameters for it, and none of them seem to work.

Is there some working sample code somewhere for how to pass in the values for Config.Volumes?

**Comment by deepak6446** [comment]
may be useful for someone

resp, err := cli.ContainerCreate(ctx, &container.Config{
		Tty: false,	
		Image: "fb05ad264203",
		Env: []string{"port="+port},
	}, &container.HostConfig{
		PidMode: "host",
		NetworkMode: "host",
		UTSMode: "host",
		Resources: container.Resources{
			Memory: 100000000,
			MemorySwap: 100000000,
		},
		Binds:[]string{  
			HOST.TEMP_PATH + ":" + DOCKER.TEMP_PATH + ":rw", 
			HOST.CONNECTOR_PATH + ":" + DOCKER.CONNECTOR_PATH + ":ro",
			HOST.CLI_CONNECTORS + ":" + DOCKER.CLI_CONNECTORS + ":ro",
		},
	}, nil, "")
