### ISSUE TITLE
Panic when docker stop and logs are streamed

### ISSUE THREAD

**Issue by Soulou** [fsouza/go-dockerclient#136]
Hello,

I'm developping something which should resist a restart of docker (ie: upgrade), but the client is panicing sometimes when the daemon os restarted.

Here is the trace:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x572eac]

goroutine 39 [running]:
runtime.panic(0x6e08e0, 0xad2ee8)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/fsouza/go-dockerclient.(*Client).stream(0xc210060c80, 0x73f960, 0x3, 0xc210060d80, 0x73, ...)
        /Appsdeck/appsdeck-logs/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go:316 +0x61c
github.com/fsouza/go-dockerclient.(*Client).Logs(0xc210060c80, 0xc21001fc80, 0x40, 0x7f5625c90fe0, 0xc210066b60, ...)
        /Appsdeck/appsdeck-logs/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go:593 +0x215

**Comment by Soulou** [comment]
Seems ok, the bug has not happened for a while now

**Comment by fsouza** [comment]
@Soulou thank you!
