### ISSUE TITLE
Can't attach stdin to a container

### ISSUE THREAD

**Issue by acroca** [fsouza/go-dockerclient#144]
I'm working on a go app that needs to run containers and send them some Stdin from a string. I can't manage to make it work

```go
client, _ := docker.NewClient(...)

container, err := client.CreateContainer(docker.CreateContainerOptions{
	Config: &docker.Config{
		Image:     "ubuntu:14.04",
		OpenStdin: true,
		Cmd:       []string{"cat"},
		StdinOnce: true,
	},
})
if err != nil {
	panic(err)
}
defer client.RemoveContainer(docker.RemoveContainerOptions{ID: container.ID, Force: true})

err = client.StartContainer(container.ID, nil)
if err != nil {
	panic(err)
}

err = client.AttachToContainer(docker.AttachToContainerOptions{
	Container:   container.ID,
	InputStream: strings.NewReader("Test\n"),
	Stdin:       true,
	// Stream:      true,
})
if err != nil {
	panic(err)
}

stdout := new(bytes.Buffer)
client.Logs(docker.LogsOptions{
	Container:    container.ID,
	Stdout:       true,
	OutputStream: stdout,
})
fmt.Println(stdout.String())
```
I'm expecting to see `"Test"` in the, but it's empty.

**Comment by fsouza** [comment]
Hi @acroca, it actually works if you set Stream: true in the attach call:

```
err = client.AttachToContainer(docker.AttachToContainerOptions{
	Container:   container.ID,
	InputStream: strings.NewReader("Test\n"),
	Stdin:       true,
	Stream:      true,
})
if err != nil {
	panic(err)
}
```

Also, please ensure you wait for the container to stop:

```
_, err = client.WaitContainer(container.ID)
if err != nil {
	panic(err)
}
````

Thanks for opening this issue!

**Comment by acroca** [comment]
thanks @fsouza. I was using an quite old version of this the lib, probably something good changed since then.

**Comment by fsouza** [comment]
@acroca makes sense! I will checkout to the version in the day that you opened the issue and try to detect what changed. Thank you!

**Comment by sanketsaurav** [comment]
@fsouza I'm facing a somewhat related issue. When a container is stopped and started again, the attached STDIN is not passed on to the container. Is it the expected behavior? If so, any workarounds for this?
