### ISSUE TITLE
Allow cancellation of AttachToContainer and Logs requests

### ISSUE THREAD

**Issue by rykov** [fsouza/go-dockerclient#161]
Currently, I found no way to stop `AttachToContainer` or `Logs` (with Follow:true) requests from the client.  It would be great to have a way to close these connections without quitting the client-side process.

**Comment by amasad** [comment]
+1

**Comment by tomwilkie** [comment]
@fsouza mind if I took a stab at this?  For me the idea would be to have c.hijack not block, but instead return an (err, CloseWaiter) where a CloseWaiter is:
```
type CloseWaiter interface {
  io.Closer
  Wait() error
}
```
People to who wish to have a blocking interface could call Wait after their calls to AttachToContainer, for example.  Compatibility with the existing package interface could be provided by having new functions for non-blocking operations (need a better name, but eg NonBlockingAttachToContainer etc).

This has the added benefit of reliably returning initialisation errors early; if you need to use AttachToContainer in an async fashion with the current API, you can rely on the returned error as it may block indefinitely before returning it.

How does that sound?
