### ISSUE TITLE
no pause/unpause events

### ISSUE THREAD

**Issue by j0hnsmith** [fsouza/go-dockerclient#179]
The [docker event docs](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#monitor-dockers-events) explicitly mention pause/unpause events but I'm not seeing them when I pause/unpause a container.

**Comment by pwaller** [comment]
I think this issue can be closed:

https://godoc.org/github.com/fsouza/go-dockerclient#Client.PauseContainer

**Comment by fsouza** [comment]
@j0hnsmith can you confirm that following @lalyos's instructions work for you? It worked for me.

**Comment by j0hnsmith** [comment]
I haven't used this lib for a long time, I'm not really in a position to test myself, but if he says it's fixed that's good enough for me.

**Comment by fsouza** [comment]
@j0hnsmith thank you! I will move forward and close the issue then.
