### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by mcuadros** [fsouza/go-dockerclient#180]
I am using this library at my project [dockership](https://github.com/mcuadros/dockership), since this commit: https://github.com/fsouza/go-dockerclient/commit/90496c840a3a13cc9976af74a375aef57daaa1de, `docker.PortBinding.HostIp` has changed to `docker.PortBinding.HostIP`

I suggest use versioning in this type of changes because is breaking the compilation of 3rd party projects.

Maybe http://labix.org/gopkg.in could be a good solution.

Best

**Comment by budhrg** [comment]
Hi,

Any update on it?

Thanks.

**Comment by fsouza** [comment]
Hi @budhrg, I will start working on the plans described here in this weekend, thanks for your interest in go-dockerclient!

**Comment by fsouza** [comment]
Same as #191. Let's see what are the next steps in Go versioning/package management.
