### ISSUE TITLE
HostConfig

### ISSUE THREAD

**Issue by razic** [fsouza/go-dockerclient#187]
i had a problem with this...

i have something like the following pseudocode

```
config = { 
  Config: {},
  HostConfig: {},
}

CreateContainer(name, config)
StartContainer(containerID, nil)
```

and `HostConfig` gets overridden... the only way to get it to work is like this:

```
config = { 
  Config: {},
  HostConfig: {},
}

CreateContainer(name, config)
StartContainer(containerID, config.HostConfig)
```

can we get rid of the `hostconfig` argument to the `StartContainer` function and just pass it in the container config when creating the container initially?

**Comment by deanrock** [comment]
I have the same issue, I would like to start an existing container without changing HostConfig.

Other libraries I tested (py-docker for python and dockerclient for go) don't send anything if hostcofing == nil, and Docker just starts the container without changing HostConfig.

**Comment by fsouza** [comment]
Hi @deanrock @razic. Currently, Docker doesn't use HostConfig when starting containers anymore, can you try it again with latest Docker version?

Thanks!

**Comment by deanrock** [comment]
Hi, I noticed in the API documentation that StartContainer no longer accepts HostConfig, but it still seems to use it.

Docker version (it should be the latest):
	$ docker version
	Client version: 1.5.0
	Client API version: 1.17
	Go version (client): go1.4.1
	Git commit (client): a8a31ef
	OS/Arch (client): linux/amd64
	Server version: 1.5.0
	Server API version: 1.17
	Go version (server): go1.4.1
	Git commit (server): a8a31ef

Test code:
```go
package main

import (
	"log"
    "github.com/fsouza/go-dockerclient"
)

func main() {
        endpoint := "unix:///var/run/docker.sock"
        client, _ := docker.NewClient(endpoint)

        container, err := client.CreateContainer(docker.CreateContainerOptions{
			Config: &docker.Config{
				OpenStdin: true,
				Tty: true,
				Cmd:   []string{"date"},
				Image: "debian",
			},
			HostConfig: &docker.HostConfig{
				ExtraHosts: []string{"test:127.0.0.1"},
			},
		})

		if err != nil {
			log.Println("err ", err)
		}

		c, _ := client.InspectContainer(container.ID)
		log.Println("", c.HostConfig.ExtraHosts) //prints 2015/03/03 20:14:39  [test:127.0.0.1]

		err = client.StartContainer(container.ID, nil)

		if err != nil {
			log.Println("err ", err)
		}

		c, _ = client.InspectContainer(container.ID)
		log.Println("", c.HostConfig.ExtraHosts) //prints 2015/03/03 20:14:39  []
}```

Inspecting container and printing ExtraHosts variable before starting it via StartContainer method returns expected result, but after starting it it's empty.

If I use StartContainer from github.com/samalba/dockerclient library which sends empty body I get [test:127.0.0.1] before and after starting the container.

**Comment by fsouza** [comment]
Yeah, my bad. I will push a fix within the next half hour, sorry for the delay.

**Comment by fsouza** [comment]
Just pushed a fix, could you please try it again?

Sorry for the mess!

**Comment by deanrock** [comment]
Now it seems to work fine in both cases (it doesn't change HostConfig when I provide nil, and it updates it if I provide new settings).

Thanks.
