### ISSUE TITLE
Tags removed?

### ISSUE THREAD

**Issue by budhrg** [fsouza/go-dockerclient#191]
Hi @fsouza ,

I am heavily using this package for my projects. 
Also, I was using tags to use particular stable release for my projects. But recently found similar issues as reported in #180 in my projects using `go-dockerclient`.

When I checked the `tags` in this repo, I found tags were missing.
Any particular reason to remove tags or are these removed by mistake(by chance)?

Any help would be appreciated.

Cheers

**Comment by fsouza** [comment]
Since the community put itself in the vendoring world, and there's work going on to improve this state, I'm going to close this issue for now.
