### ISSUE TITLE
batch execute pushImge execption

### ISSUE THREAD

**Issue by zhangwei1234** [fsouza/go-dockerclient#201]
error log

time="2015-01-08T14:09:17+08:00" level="info" msg="POST /images/jae.registry.com:5000/6e4a635d5205b1e1054df96d74974d09/push?registry=jae.registry.com%3A5000&tag=latest" 
time="2015-01-08T14:09:17+08:00" level="info" msg="+job push(jae.registry.com:5000/6e4a635d5205b1e1054df96d74974d09)" 
Received HTTP code 500 while uploading layer: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>

<h1>Internal Server Error</h1>

<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

time="2015-01-08T14:09:19+08:00" level="info" msg="-job push(jae.registry.com:5000/1d238eae732b9647730d02cd4b73dfe9) = ERR (1)" 
time="2015-01-08T14:09:19+08:00" level="info" msg="DELETE /images/jae.registry.com:5000/1d238eae732b9647730d02cd4b73dfe9"

**Comment by fsouza** [comment]
Seems like an error in your registry server. Could you share some code? Are you using [docker-registry](/docker/docker-registry)?

**Comment by zhangwei1234** [comment]
using docker-registry
