### ISSUE TITLE
get error: "unknown archive.TarOptions field 'ExcludePatterns' in struct literal"

### ISSUE THREAD

**Issue by nashasha1** [fsouza/go-dockerclient#207]
go get github.com/fsouza/go-dockerclient
# github.com/fsouza/go-dockerclient
../github.com/fsouza/go-dockerclient/tar.go:30: unknown archive.TarOptions field 'ExcludePatterns' in struct literal

It seems had showed before.I get this at the latest version.

**Comment by fsouza** [comment]
Hey @nashasha1, thanks for reporting!

You need to update the code for docker. Please run:

```
% go get -u github.com/docker/docker/...
```

**Comment by nashasha1** [comment]
thanks a lot @fsouza

**Comment by fsouza** [comment]
No problem! May I close this issue?

**Comment by nashasha1** [comment]
Of course! Thanks again.

**Comment by fsouza** [comment]
Thank you!
