### ISSUE TITLE
Client compatible with docker 1.5?

### ISSUE THREAD

**Issue by ChristianKniep** [fsouza/go-dockerclient#213]
Hey there,

I just tried your example and it failed on me.
On a server with docker 1.0 it worked out (golang 1.4).

Cheers

**Comment by fgrehm** [comment]
It works for me on an Ubuntu 14.04 host with Docker 1.5.0 using Go 1.4.1

**Comment by fsouza** [comment]
Hey @ChristianKniep, can you share more details of the failure?

Thanks for reporting!

**Comment by ChristianKniep** [comment]
Works for me guys... Maybe I misconfigured... Thx for your library!
