### ISSUE TITLE
NetworkMode not respected in HostConfig

### ISSUE THREAD

**Issue by levilovelock** [fsouza/go-dockerclient#218]
When trying to launch containers with custom HostConfig.NetworkMode, the config does not show up in respected containers. Not sure what exactly is going on here. Happy to take a look tomorrow.

Ah yes, and this was specifically for 'container:<container_id>' type NetworkMode. Not sure if the other types work or not, but for container, it literally shows up as `NetworkMode:""` when I inspect the launched container.

**Comment by fsouza** [comment]
Hi @levilovelock, can you share a reproducer, so I can try to reproduce it locally?

Thanks for reporting!

**Comment by levilovelock** [comment]
Yep no worries. I'll write up some reproduction steps tonight!

**Comment by peter-edge** [comment]
Of note @fsouza @levilovelock, I wasn't able to reproduce this. I tried using a known container id, a known container name, and `container:doesnotexit` and `container:`. The first two worked when I ran `docker inspect`, the latter two returned error correctly.

**Comment by fsouza** [comment]
Maybe there was an old bug related to what go-dockerclient did when creating the container: sometimes, StartContainer could reset HostConfig if not defined properly, it was fixed at some point, but I'm not sure whether it was before or after @levilovelock opened this issue (I think so).

Can you confirm that it works now, @levilovelock?

@peter-edge thanks for your contributions!
