### ISSUE TITLE
PortBinding does not work and go-dockerclient debugging

### ISSUE THREAD

**Issue by knodir** [fsouza/go-dockerclient#220]
Hi,

I am trying to run `google/cadvisor` image via `go-dockerclient`. Here is the shell command to do this:

``` shell
sudo docker run --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --detach=true --name=cadvisor google/cadvisor
```

It gives following output on success:

``` shell
sudo docker ps
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS                    NAMES
a7896c6cae43        google/cadvisor:0.9.0   "/usr/bin/cadvisor"   50 seconds ago       Up 49 seconds        0.0.0.0:8080->8080/tcp   cadvisor
```

I wrote a program to do this with `go-dockerclient`, which successfully creates the container, but without port mapping (note the `PORTS: 0.0.0.0:8080->8080/tcp` on above shell output). Here is the code I am running

``` go
package main

import (
    "fmt"
    "github.com/fsouza/go-dockerclient"
)

func main() {
    endpoint := "unix:///var/run/docker.sock"
    client, _ := docker.NewClient(endpoint)

    exposedCadvPort := map[docker.Port]struct{}{
        "8080/tcp": {}}

    createContConf := docker.Config{
        ExposedPorts: exposedCadvPort,
        Image: "google/cadvisor"}

    volumesToMount := []string{
        "/var/run", "/var/run:rw", 
        "/sys", "/sys:ro", 
        "/var/lib/docker/", "/var/lib/docker:ro"}

    portBindings := map[docker.Port][]docker.PortBinding{
        "8080/tcp": []docker.PortBinding{docker.PortBinding{HostPort: "8080"}}}

    createContHostConfig := docker.HostConfig{
        PortBindings: portBindings,
        PublishAllPorts: true,
        Privileged: false,
        VolumesFrom: volumesToMount}

    createContOps := docker.CreateContainerOptions{
        Name: "cadvisor",
        Config: &createContConf,
        HostConfig: &createContHostConfig}

    cont, _ := client.CreateContainer(createContOps)
    fmt.Printf("\ncontainer = %s\n", cont)
}
```

And its output

``` shell
sudo docker ps -a
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS               NAMES
eeedaac903e9        google/cadvisor:0.9.0   "/usr/bin/cadvisor"   17 minutes ago                                              cadvisor 
```

I tweaked `PortBindings` in several different ways, but still fail to create the container with correct port mapping. Can you please point what I am doing wrong?

I have couple of other questions, if I may ask. 

I don't understand the relationship between [Config.ExposedPorts](https://github.com/fsouza/go-dockerclient/blob/master/container.go#L183) and [HostConfig.PortBindings](https://github.com/fsouza/go-dockerclient/blob/master/container.go#L355). Should `PortBindings` provide mapping for ports listed on `ExposedPorts`? I mostly referred to the [Docker remote API](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#create-a-container), which maps `"ExposedPorts": {"22/tcp": {}}` to `"PortBindings": { "22/tcp": [{ "HostPort": "11022" }] },`. If this understanding is correct, should I be using `"ExposedPorts": {"8080/http": {}}` and `"PortBindings": { "8080/http": [{ "HostPort": "8080" }] },` for cAdvisor example (as I'd be pointing the browser to `localhost:8080` to see cAdvisor's output)?

Is there way to see `go-dockerclient`'s `POST` message before calling `client.CreateContainer`? Right now I can't tell if there is a problem in the message `go-dockerclient` is sending, or remote Docker daemon doing something wrong (due to version difference, etc.)? One way to debug this would be to see if my `POST` complies with [Docker remote API](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#create-a-container). It would be great to have such feature (or something similar).

Thanks,
Nodir.

**Comment by fsouza** [comment]
Hi Nodir, sorry for the almost infinite delay and than you very much for reporting.

In order to get the container to run, you need to manually call StartContainer after creating it, something like:

```
cont, err := client.CreateContainer(createContOps)
if err != nil {
	// handle err
}
err = client.StartContainer(cont.ID, nil)
if err != nil {
	// handle err
}
```

Then you will be able to see it running with ``docker ps``.

**Comment by knodir** [comment]
Hi Francisco,

Thanks for pointing this out! I can see my container being successfully created and run now. Here is what I have:

```shell
$ sudo docker ps -a
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS                        PORTS               NAMES
73fbf608b8ef        google/cadvisor:0.9.0   "/usr/bin/cadvisor"   11 minutes ago      Exited (255) 11 minutes ago                       cadvisor            
```

I guess container exits with 255 because it does not have proper volumes mounted as cAdvisor expects. It does not have ports mapped, either. But at least it run once. It would be great if someone could point what I'm doing wrong with volumes and ports. 

I also think it would be nice to have running examples in the repo. I'll try to contribute cAdvisor example (with all port mappings, volume mounts) once I get it run. So, expect a pull request sometime soon :-)

Here is an updated code and output for your reference
```go
package main

import (
    "fmt"
    "github.com/fsouza/go-dockerclient"
)

func main() {
    endpoint := "unix:///var/run/docker.sock"
    client, _ := docker.NewClient(endpoint)

    exposedCadvPort := map[docker.Port]struct{}{
        "8080/tcp": {}}

	createContConf := docker.Config{
		ExposedPorts: exposedCadvPort,
		Image: "google/cadvisor",
	}

	portBindings := map[docker.Port][]docker.PortBinding{
		"8080/tcp": []docker.PortBinding{docker.PortBinding{HostPort: "0.0.0.0:8080"}}}

	createContHostConfig := docker.HostConfig{
		PortBindings: portBindings,
		PublishAllPorts: true,
		Privileged: false,
	}

	createContOps := docker.CreateContainerOptions{
		Name: "cadvisor",
		Config: &createContConf,
		HostConfig: &createContHostConfig,
	}

	fmt.Printf("\nops = %s\n", createContOps)

	cont, err := client.CreateContainer(createContOps)
	if err != nil {
		fmt.Printf("create error = %s\n", err)
	} 
	fmt.Printf("container = %s\n", cont)

	err = client.StartContainer(cont.ID, nil)
	if err != nil {
		fmt.Printf("start error = %s\n", err)
	}
	fmt.Printf("start = %s\n", err)
}
```

Output
```shell
$ go run monitor.go provision.go
ops = {cadvisor %!s(*docker.Config=&{   0 0 0  false false false [] map[8080/tcp:{}] false false false [] [] [] google/cadvisor map[]   [] false [] []}) %!s(*docker.HostConfig=&{[] [] []  [] false map[8080/tcp:[{ 0.0.0.0:8080}]] [] true [] [] [] []   { 0}})}
container = &{2ba6df9d61acaede79a6267bea9004c3e75c5b8b2c8fcd756568abdac1c91b01 0001-01-01 00:00:00 +0000 UTC  [] %!s(*docker.Config=<nil>) {%!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(int=0) %!s(int=0)  0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}  %!s(*docker.NetworkSettings=<nil>)     cadvisor  map[] map[] %!s(*docker.HostConfig=<nil>)}
start = %!s(<nil>)
```

Note that no error is reported during creation or start.

Thanks,
Nodir.

**Comment by fsouza** [comment]
Hi @knodir, can you get anything from the containers log?

```
% docker logs <container-id>
```

I will try to reproduce the failure with your sample code and try to get it to run, thanks for reporting!

**Comment by fsouza** [comment]
Hi @knodir, here's a working solution:

```
package main

import (
	"fmt"

	"github.com/fsouza/go-dockerclient"
)

func main() {
	endpoint := "http://192.168.50.4:2375"
	client, _ := docker.NewClient(endpoint)

	exposedCadvPort := map[docker.Port]struct{}{
		"8080/tcp": {}}

	createContConf := docker.Config{
		ExposedPorts: exposedCadvPort,
		Image:        "google/cadvisor",
	}

	portBindings := map[docker.Port][]docker.PortBinding{
		"8080/tcp": {{HostIP: "0.0.0.0", HostPort: "8080"}}}

	createContHostConfig := docker.HostConfig{
		Binds:           []string{"/var/run:/var/run", "/sys:/sys", "/var/lib/docker:/var/lib/docker"},
		PortBindings:    portBindings,
		PublishAllPorts: true,
		Privileged:      false,
	}

	createContOps := docker.CreateContainerOptions{
		Name:       "cadvisor",
		Config:     &createContConf,
		HostConfig: &createContHostConfig,
	}

	fmt.Printf("\nops = %s\n", createContOps)

	cont, err := client.CreateContainer(createContOps)
	if err != nil {
		fmt.Printf("create error = %s\n", err)
	}
	fmt.Printf("container = %s\n", cont)

	err = client.StartContainer(cont.ID, nil)
	if err != nil {
		fmt.Printf("start error = %s\n", err)
	}
	fmt.Printf("start = %s\n", err)
}
```

Here are the two changes I did in the code:

- when specifying the port binding, you need to pass the host (0.0.0.0) and the port (8080) using different fields in the struct: ``"8080/tcp": {{HostIP: "0.0.0.0", HostPort: "8080"}}``
- you  need to specify the volume _binding_ in the HostConfig, the binding is a list of strings in the format ``<host-dir>:<container-id>``:  ``Binds:           []string{"/var/run:/var/run", "/sys:/sys", "/var/lib/docker:/var/lib/docker"}`` (yeah, I know that the way Docker handles volumes are pretty messy)

Could you apply these changes locally and test it? Thanks for reporting the issue.

**Comment by knodir** [comment]
This is much better. I do have a running cAdvisor now, but port mapping still does not seem right. Here is the output I get after running your code

```shell
$ sudo docker ps
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS               NAMES
00e9c44ee788        google/cadvisor:0.9.0   "/usr/bin/cadvisor"   3 minutes ago       Up 3 minutes        8080/tcp            cadvisor
```

Note that when I create cAdvisor manually (with the command given on top of this issue) port output is `0.0.0.0:8080->8080/tcp` instead of current `8080/tcp`. Can this be a reason I don't see anything when I point my browser to `localhost:8080`?

Also, what about volume binds? Shouldn't we specify mounting options, such as:
`Binds:           []string{"/var/run:/var/run:rw", "/sys:/sys:ro", "/var/lib/docker:/var/lib/docker:ro"},`
Your code does not have `:rw, :ro` options.

Thanks for helping out,
Nodir.

**Comment by fsouza** [comment]
Ops, sorry for not specifying the mount options, they work fine as you posted.

Regarding the port issue, after running the code, I do get this output:

```
% docker ps
CONTAINER ID        IMAGE                                            COMMAND                CREATED             STATUS              PORTS                     NAMES
4a7419976c0b        google/cadvisor:0.10.1                           "/usr/bin/cadvisor"    4 seconds ago       Up 3 seconds        0.0.0.0:8080->8080/tcp    cadvisor
```

Can you confirm that you're specifying ``HostIP`` to be ``0.0.0.0``. For the record, I'm using Docker 1.5.0. Here's the full code (including mount options): https://gist.github.com/fsouza/bf2f69f84267cb1b5d25.

**Comment by knodir** [comment]
I run the same code (`HostIP: 0.0.0.0`), but still get `8080/tcp` instead of `0.0.0.0:8080->8080/tcp`. Here is the Docker version.
```shell
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

Oddly enough, I don't get any output when I go `docker logs cadvisor`. It just does not print anything. Should I enable any option to get this?

Also, I used `endpoint := "unix:///var/run/docker.sock"` instead of `endpoint := "http://<ip-address>:2375"` as in your code. I did not enable REST API. I don't think this is relevant here.

**Comment by fsouza** [comment]
I will try with the socket, and get back to you. Thanks for your patience!

**Comment by bzz** [comment]
Stuck with the same issue. Do you guys have any updates on how to overcome it?

I used docker 1.4.1 over REST API \w `docker.PortBinding{HostIP: "0.0.0.0", HostPort: "8080"},` and on get `docker inspect` get

```
      "PortMapping": null,
        "Ports": {
            "8080/tcp": null
        }
```
as well as for `docker ps`  
```
21eb69777ec3        ...:latest   "/bin/bash -c /usr/l   About a minute ago   Up 59 seconds       8080/tcp            containerName
```

Appreciate your help!

**Comment by knodir** [comment]
No, unfortunately I could not get this working and moved to a different solution. 

I am not sure about your use case, but I needed port bindings to access files inside the container. I ended up mounting the host folder inside container and use that "shared" folder to retrieve files from the container file system.

**Comment by fsouza** [comment]
@bzz could you provide a reproducer?

Does it fail with this code as well: https://gist.github.com/fsouza/bf2f69f84267cb1b5d25?

Thanks!

**Comment by vtuson** [comment]
I am hitting this problem too. Encoding the options into json seems compliant with the api spec. The code above, does not run for me. Any suggestions?

**Comment by bzz** [comment]
\cc @khalidhuseynov as he might have more context

**Comment by vtuson** [comment]
I have fix the issue on my side. I was using the correct hostconfig on container create, but then overwriting it on container run.
