### ISSUE TITLE
Add interfaces to client

### ISSUE THREAD

**Issue by cjellick** [fsouza/go-dockerclient#227]
How would you feel about adding interfaces to the client? I think users would find this useful from a testing standpoint. It would allow us to mock out this client when necessary.

I'm thinking we could have an interface per functional area. So, we'd have a container interface, an image interface, etc.

@fsouza  If you like this idea and it has a good chance of being merged/accepted, I can work on it and submit a PR.

**Comment by fsouza** [comment]
Hi @cjellick, thanks for opening this issue and bringing your suggestion. I don't think that having interfaces would make much sense here, I know it's easier for tests, but it also adds another level of indirection to the production code, and I don't think it's worth it.

We've been using the testing server for a while, and it works great so far, do you think it would not work for you?

Thank you.

**Comment by cjellick** [comment]
Makes sense. I'll take a look at the testing server. I ended up finding a pretty painless way to abstract away and mock the client when necessary anyway.

Thanks for the response (and for the great client).
