### ISSUE TITLE
add support for host devices

### ISSUE THREAD

**Issue by proppy** [fsouza/go-dockerclient#241]
It would be nice if the [`HostConfig`](https://github.com/fsouza/go-dockerclient/blob/20220089b9b5b43f9bc668e4942d39455cd39845/container.go#L381) in `CreateContainerOptions` had support for exposing host devices to the container (like docker run --device does).

This could be passed as an additional member of the `HostConfig` when [calling](https://github.com/fsouza/go-dockerclient/blob/20220089b9b5b43f9bc668e4942d39455cd39845/container.go#L316) the `/containers/create` API method:
```
{
    "PathOnHost": "/dev/deviceName",
    "PathInContainer": "/dev/deviceName",
    "CgroupPermissions": "mrw"
}
```

**Comment by fsouza** [comment]
Hi @proppy, thanks for reporting! I will push this feature within the next few minutes. I will add a type named ``Device`` with the attributes you described, and add a slice of ``Device``s in the ``HostConfig`` struct.

**Comment by proppy** [comment]
Thanks for the quick update!
