### ISSUE TITLE
Rename id parameter for container function to idOrName? Plus tests

### ISSUE THREAD

**Issue by peter-edge** [fsouza/go-dockerclient#261]
I know this works for InspectContainer, and I am assuming for other calls too: when the Docker Remote API says "id" as part of a request, it really means "id or name", both work.

This is probably just a matter of:
- updating the parameters and documentation
- testing for each function

**Comment by fsouza** [comment]
Hi @peter-edge, I don't think that this behavior is present in all Docker API endpoints, specially endpoints like rename, but I'm not sure. I will run some tests to check it.

Thanks for contributing!

**Comment by peter-edge** [comment]
I don't think it is either, after further testing. Happy to help check too.
