### ISSUE TITLE
no port mapping host ip

### ISSUE THREAD

**Issue by tcurdt** [fsouza/go-dockerclient#266]
I am currently tracking down a missing ip on the port binding. Looking at the inspect output I see

                    "HostIp": "0.0.0.0",
                    "HostPort": "6667"

while the code seems to expect `HostIP`

  https://github.com/fsouza/go-dockerclient/blob/master/container.go#L116

s/HostIP/HostIp/g ?

**Comment by tcurdt** [comment]
https://github.com/docker/docker/blob/master/docs/sources/reference/api/docker_remote_api_v1.16.md
https://github.com/docker/docker/blob/master/daemon/container.go#L643

yup!

**Comment by fsouza** [comment]
Closing, see #267.
