### ISSUE TITLE
StartExec gives 'persistent connection closed'

### ISSUE THREAD

**Issue by ewoutp** [fsouza/go-dockerclient#281]
I'm getting an http.ProtocolError now.

This was not the case in commit 09334c56c6

**Comment by peter-edge** [comment]
Do you have steps to reproduce? Otherwise, can you try two things for me:

Here's the diff https://github.com/fsouza/go-dockerclient/compare/09334c56c63bab2cd6c4ccab924d89e2419a361f...master

Look at client.go, where I think the changes would be that would affect this are two places:

1.

line 507:
```
-	clientconn.Do(req)
+	if _, err := clientconn.Do(req); err != nil {
+		return err
+	}
```

2.

line 530:
```
var err error
if hijackOptions.in != nil {
  _, err = io.Copy(rwc, hijackOptions.in)
}		 		}
+ errChan <- err
```

I'm 95% positive it's #1. Could you change that locally and see if you have the same issue? Hacky, but after we identify it quickly, we can add a test to reproduce and kill this.

**Comment by ewoutp** [comment]
Reverting the change near line 507 fixed the connection issue, but closing the connection is now not done.

I'm creating an exec for `/bin/sh` into my shell, I'm doing some `ls`, `ps` etc and finally type `exit`.
After that nothing happens anymore. This worked fine in the earlier commit I mentioned.

**Comment by peter-edge** [comment]
How did you determine the connection is not closed? Do you just have:

```go
clientconn.Do(req)
```

now?

**Comment by ewoutp** [comment]
Yes, only `clientconn.Do(req)` now.

I have attached stdin/out as the streams and set it up such that my process stops when the connection is closed. It does not now, it does when I pin to the above mentioned commit.

**Comment by peter-edge** [comment]
Alright, so that's very peculiar, that it did close before this change but does not now. Let me look more.

**Comment by peter-edge** [comment]
Would you be able to produce a gist with reproduce steps?

**Comment by peter-edge** [comment]
This will mean there is a deeper bug, but around line 530, could you remove `errChan <- err` and then at the end of the function, instead of doing the loop, just do `return <-errChan`?

**Comment by ewoutp** [comment]
This code works:

```
	clientconn := httputil.NewClientConn(dial, nil)
	defer clientconn.Close()
	clientconn.Do(req)
	if hijackOptions.success != nil {
		hijackOptions.success <- struct{}{}
		<-hijackOptions.success
	}
	rwc, br := clientconn.Hijack()
	defer rwc.Close()
	errChanOut := make(chan error, 1)
	errChanIn := make(chan error, 1)
	exit := make(chan bool)
	go func() {
		defer close(exit)
		defer close(errChanOut)
		var err error
		if hijackOptions.setRawTerminal {
			// When TTY is ON, use regular copy
			_, err = io.Copy(hijackOptions.stdout, br)
		} else {
			_, err = stdcopy.StdCopy(hijackOptions.stdout, hijackOptions.stderr, br)
		}
		errChanOut <- err
	}()
	go func() {
		defer close(errChanIn)
		var err error
		if hijackOptions.in != nil {
			_, err = io.Copy(rwc, hijackOptions.in)
		}
		rwc.(interface {
			CloseWrite() error
		}).CloseWrite()
		errChanIn <- err
	}()
	<-exit
	select {
	case err = <-errChanIn:
		return err
	case err = <-errChanOut:
		return err
	}
```

**Comment by peter-edge** [comment]
It doesn't handle if you have errors on both, but it's better than what is there now. Can you submit a PR?

**Comment by ewoutp** [comment]
See #282

**Comment by fsouza** [comment]
@ewoutp in which point you get this error? After you run "exit"? What about non interactive execs?

I will merge #282 to get master working again, but run some local tests without it and see if we can fix the issue without losing all the error checking.

Thank you!

**Comment by ewoutp** [comment]
@fsouza Without the revert in line 507 all calls to StartExec will fail.

With that fixed, the connection was not closed after typing "exit <enter>" in the executed shell.

PS. Thank you both for the fast response!
