### ISSUE TITLE
How can I exec commands on containers?

### ISSUE THREAD

**Issue by aanm** [fsouza/go-dockerclient#287]
I'm trying to replicated the following command with go-dockerclient but I can't
```
docker exec -ti containerID echo hello world
```

Piece of code that I'm trying:
```go
func main() {
	var (
		docker uc.Docker
		dExec  *d.Exec
		err    error
	)
	log.Debug("NewDockerClient")
	if docker, err = NewDockerClient(); err != nil {
		log.Error("Error: %s", err)
		return
	}
	de := d.CreateExecOptions{
		AttachStderr: true,
		AttachStdin:  true,
		AttachStdout: true,
		Tty:          false,
		Cmd:          []string{"echo", "hello world"},
		Container:    "containerID",
	}
	log.Debug("CreateExec")
	if dExec, err = docker.CreateExec(de); err != nil {
		log.Error("Error: %s", err)
		return
	}
	var stdout, stderr bytes.Buffer
	success := make(chan struct{})
	var reader = strings.NewReader("echo hello world")
	execId := dExec.ID
	opts := d.StartExecOptions{
		OutputStream: &stdout,
		ErrorStream:  &stderr,
		InputStream:  reader,
		RawTerminal:  true,
		Success:      success,
	}
	log.Debug("StartExec")
	if err = docker.StartExec(execId, opts); err != nil {
		log.Error("Error: %s", err)
		return
	}
	log.Debug("stdout: %+v", stdout)
	<-opts.Success
	log.Debug("Finish: %+v", stdout)
}
```
It freezes after "StartExec" and I was able to see some packets and I have realized they are different from the `docker exec -ti containerID echo hello world` command.

Any help? Thanks in advance

**Comment by fsouza** [comment]
Hi @aanm, if you're using the success channel, you must call StartExec in a goroutine.

In this case, I'd not use the success channel, removing it from StartExecOptions.

**Comment by aanm** [comment]
@fsouza cool, it worked :-)

**Comment by peter-edge** [comment]
https://github.com/peter-edge/go-dockerutils/blob/master/dockerutils.go#L153 although don't use this lib cuz I'm going to probably refactor it soon

**Comment by aanm** [comment]
@peter-edge I'm a little lost, what does that has to do with my problem?

**Comment by peter-edge** [comment]
Oh man, I copy/pasted into the wrong issue haha. My bad. Disregard *embarrassed*

**Comment by edwinakatosh** [comment]
This was helpful. Thanks guys!
