### ISSUE TITLE
BlkioStatsEntry define error

### ISSUE THREAD

**Issue by lsword** [fsouza/go-dockerclient#290]
type BlkioStatsEntry struct {
	Major uint64 `json:"major,omitempty" yaml:"major,omitempty"`
->    Minor uint64 `json:"major,omitempty" yaml:"major,omitempty"`
	Op    string `json:"op,omitempty" yaml:"op,omitempty"`
	Value uint64 `json:"value,omitempty" yaml:"value,omitempty"`
}

**Comment by fsouza** [comment]
Thank you, fixing right now!
