### ISSUE TITLE
CommitContainer error in docker 1.5

### ISSUE THREAD

**Issue by ghao-ooyala** [fsouza/go-dockerclient#295]
docker version 1.5, docker remote api version 1.7

opts := docker.CommitContainerOptions{Container: container.ID, Repository: c.URL + "/" + imageTo, Run: &docker.Config{}}
client.CommitContainer(opts)

From Docker daemon log:

INFO[0011] POST /commit?container=a59fd253c0fd52c8bde427f9b5934518b1b039e3d2ba5779a438923e52eae2a1&repo=172.17.0.15%2Fbuilder%2Fprecise64-go1.2-0.2.1&run=%7B%22Hostname%22%3A%22%22%2C%22Domainname%22%3A%22%22%2C%22User%22%3A%22%22%2C%22Memory%22%3A0%2C%22MemorySwap%22%3A0%2C%22CpuShares%22%3A0%2C%22AttachStdin%22%3Afalse%2C%22AttachStdout%22%3Afalse%2C%22AttachStderr%22%3Afalse%2C%22PortSpecs%22%3Anull%2C%22ExposedPorts%22%3Anull%2C%22Tty%22%3Afalse%2C%22OpenStdin%22%3Afalse%2C%22StdinOnce%22%3Afalse%2C%22Env%22%3Anull%2C%22Cmd%22%3Anull%2C%22Dns%22%3Anull%2C%22Image%22%3A%22%22%2C%22Volumes%22%3Anull%2C%22VolumesFrom%22%3A%22%22%2C%22WorkingDir%22%3A%22%22%2C%22Entrypoint%22%3Anull%2C%22NetworkDisabled%22%3Afalse%7D 
ERRO[0011] Handler for POST /commit returned error: Content-Type specified (plain/text) must be 'application/json' 
ERRO[0011] HTTP Error: statusCode=500 Content-Type specified (plain/text) must be 'application/json'

**Comment by fsouza** [comment]
Hi @ghao-ooyala, sorry about the delay and thanks for opening this issue.

That's interesting, we're currently using Docker 1.5 and we're not fighting this issue. Can you share a piece of code that reproduces the bug?

**Comment by ghao-ooyala** [comment]
My apologies. Just realized that I was using old commit of go-dockerclient and seems it has been fixed months ago. closing the issue.

**Comment by fsouza** [comment]
I'm glad you figured it out, thank you!
