### ISSUE TITLE
No way to close streaming API calls

### ISSUE THREAD

**Issue by cjellick** [fsouza/go-dockerclient#298]
Functions such as Logs() and Stats(), block indefinitely, or more accurately, until the container exits.
This easily leads to orphaned goroutines.
There should be a way to force these calls to exit.

**Comment by cjellick** [comment]
Ideally, we could pass "stop" channel into Logs() that would signal the client to close the underlying stream.

**Comment by pwaller** [comment]
This sounds the same as #161? (albeit the title is more general)

**Comment by fsouza** [comment]
We can use context to cancel any calls now :)
