### ISSUE TITLE
Test Code Returns Error sync.Pool Undefined

### ISSUE THREAD

**Issue by kgrvamsi** [fsouza/go-dockerclient#305]
I have created a file and copied the sample code and started running it and i get the following error

    # github.com/fsouza/go-dockerclient/vendor/github.com/docker/docker/pkg/pools
    src/github.com/fsouza/go-dockerclient/vendor/github.com/docker/docker/pkg/pools/pools.go:30: undefined: sync.Pool

**Comment by fsouza** [comment]
Hi @kgrvamsi, this is probably due to the version of Go you're using. Can you share the output of the following command?

```
% go version
```

sync.Pool has been added to Go in version 1.3.

**Comment by kgrvamsi** [comment]
Go version Solved the issue thanks @fsouza
