### ISSUE TITLE
omitempty for Cmd and Entrypoint

### ISSUE THREAD

**Issue by ybogdanov** [fsouza/go-dockerclient#314]
Hi,

`omitempty` attribute is specified for Cmd and Entrypoing `[]slice` fields in `Config` struct. Having this attribute becomes impossible to reset the base image setting, e.g. if entrypoint is specified in an image and I want to reset it to empty in a container. It may be reset if an empty slice is passed, but in this case json encoder will omit the field.

Can `json:"omitempty"` attribute be removed for this two slices? What are possible consequences?

**Comment by fsouza** [comment]
Hi @ybogdanov, I do think that it makes sense. I'm applying the change to the code.

**Comment by ybogdanov** [comment]
Thanks!
