### ISSUE TITLE
"use of closed network connection" error after streaming call

### ISSUE THREAD

**Issue by joeshaw** [fsouza/go-dockerclient#318]
Commit ebac37c6 introduced a bug with its use of `defer c.transport.CancelRequest(req)`.  According to [the docs](http://golang.org/pkg/net/http/#Transport.CancelRequest),

> CancelRequest cancels an in-flight request by closing its connection.

The underlying HTTP connection is set to keep-alive.  `CancelRequest()` closes it, and when the client attempts to reuse it, the `net/http` code throws a `use of closed network connection` error.  I am using a TLS connection (to boot2docker) -- I am not sure if it happens with a plain TCP connection.

This can be reproduced by creating a new client (via `docker.NewTLSClient()` in my case),  calling a streaming API (like `PullImage()`) and then calling another API (like `Ping()`).

**Comment by jbardin** [comment]
Also from that commit, the new transport introduced doesn't have reasonable Dial and TLS timeouts from the DefaultTransport.

The behavior of `HttpClient.Timeout` is probably what was intended here.

**Comment by joeshaw** [comment]
Here's a test program.  You need to set `DOCKER_HOST` and `DOCKER_CERT_PATH` environment variables, which if you use boot2docker are set automatically with `boot2docker shellinit`:

```go
package main

import (
	"fmt"
	"os"

	"github.com/fsouza/go-dockerclient"
)

func main() {
	endpoint := os.Getenv("DOCKER_HOST")

	certPath := os.Getenv("DOCKER_CERT_PATH")
	cert := certPath + "/cert.pem"
	key := certPath + "/key.pem"
	ca := certPath + "/ca.pem"

	client, err := docker.NewTLSClient(endpoint, cert, key, ca)
	if err != nil {
		panic(err)
	}

	pullOpts := docker.PullImageOptions{
		Repository:   "nginx",
		Tag:          "1.7",
		OutputStream: os.Stdout,
	}

	dockerAuth := docker.AuthConfiguration{}

	err = client.PullImage(pullOpts, dockerAuth)
	if err != nil {
		panic(err)
	}

	err = client.Ping()
	if err != nil {
		panic(err)
	}

	fmt.Println("All good!")
}
```

Prior to ebac37c this succeeds.

**Comment by fsouza** [comment]
Hi @joeshaw, thanks for reporting. This is big, so I'm reverting ebac37c6531273e98bbac7fff4dcf8f86bee3609 right now, and prepare a better change to address both #298 and #300.

Thank you again for reporting, and sorry about the mess.
