### ISSUE TITLE
NewClientFromEnv

### ISSUE THREAD

**Issue by ejholmes** [fsouza/go-dockerclient#320]
Hey! In a lot of projects, I end up wanting to configure a docker.Client from the standard `DOCKER_*` environment variables. Thoughts on adding a `NewClientFromEnv` factory method? Basically [this](https://github.com/remind101/empire/blob/master/pkg/dockerutil/client.go#L12-L27).

**Comment by peter-edge** [comment]
I submitted this as a PR back in the day but we decided against merging, maybe if more people want it though? :)

I have an alternate impl at github.com/peter-edge/go-dockerutils

**Comment by fsouza** [comment]
Hi @ejholmes, I've just merged #327. Thanks for raising this discussion again!
