### ISSUE TITLE
Build has been broken on Travis for a bit

### ISSUE THREAD

**Issue by peter-edge** [fsouza/go-dockerclient#326]
This was the first commit I can find that this started happening on:

https://travis-ci.org/fsouza/go-dockerclient/builds/67865488
https://github.com/fsouza/go-dockerclient/commit/d41b9f48fae9e82802a2510143508c598e715339

I don't think/know if this is actually related to the build, or if this is a go tip change that caused some failure. It's probably extremely minor, but not great to have the build failing in the readme and PRs showing as broken heh.

**Comment by fsouza** [comment]
Hi @peter-edge, thanks for raising this!

From the [build history](https://travis-ci.org/fsouza/go-dockerclient/builds), seems like the test is intermittent, but only at tip, because it has been [green for a while in Drone](https://drone.io/github.com/fsouza/go-dockerclient) :-(

I will run tip locally and see whether I can catch why it is intermittent.

**Comment by peter-edge** [comment]
The test that fails intermittently is TestAttachToContainerRawTerminalFalse, I can get it to fail about 1 in 5 times on go 1.5 beta. I think the issue is in stdcopy.StdCopy somehow, but I didn't investigate any further than that :)

**Comment by peter-edge** [comment]
Does drone have a github integration? Perhaps we should switch builds on PRs to drone for now, if it does. This problem may get put on the backburner - I'll try to spend more time on it soon but it's not great that builds fail for OSS contributions.

**Comment by fsouza** [comment]
I don't think that Drone can build pull requests :-(

It did build for the #331, because you sent it from a branch in this repository, but I don't think it would build branches from forks.

**Comment by peter-edge** [comment]
On https://github.com/fsouza/go-dockerclient/pull/331 I actually re-ran the build for one of the golang head runs, it actually did fail unfortunately, ugh. I would even suggest we suspend building against golang head for a bit, except that I have this same error against golang 1.5beta1, which means that in less than a month, this will be a flaky test for the stable release of golang.

I'll see if I can spend some time on this fix soon.

**Comment by peter-edge** [comment]
@fsouza this has been ok for a bit, closing
