### ISSUE TITLE
VolumesFrom field

### ISSUE THREAD

**Issue by johnsudaar** [fsouza/go-dockerclient#334]
Hey,

I've just a question about the VolumesFrom field.

This filed is present in the [Config struct] (https://github.com/fsouza/go-dockerclient/blob/master/container.go#L198) and in the [HostConfig struct](https://github.com/fsouza/go-dockerclient/blob/master/container.go#L437).

But, according to the Remote API documentation, the VolumesFrom field is only in HostConfig. So why is he present in both struct ? And which one is needed to create a container ?

Thanks

**Comment by fsouza** [comment]
Hi @johnsudaar, you should use the HostConfig struct. It used to be in the Config struct, but Docker changed it.

In order to not break existing code, we choose to keep VolumesFrom in the Config struct, but it should be documented as deprecated. #321 should address that.

**Comment by johnsudaar** [comment]
Oh ok.
Thanks !

**Comment by fsouza** [comment]
No problem, sorry about the confusion!

May I close this issue?

**Comment by johnsudaar** [comment]
Yes, thanks !

**Comment by fsouza** [comment]
Thank you!
