### ISSUE TITLE
Unable to use docker console's ca certs+keys

### ISSUE THREAD

**Issue by ZeroGraviti** [fsouza/go-dockerclient#335]
When I attempt to connect to docker using your client lib, is there a way for me to turn off ssl cert verification ? I am able to `curl` to the remote api but only using `-k` or `--insecure`. Is there a way for me to do this from within my go sample code which uses the dockerclient lib ? Here is the error I am getting :
`Get https://192.168.59.103:2376/_ping: x509: certificate is valid for 127.0.0.1, 10.0.3.125, not 192.168.59.103`
I am running this from golang which is running in its own container but under the same docker console/kernel. I have mounted the certs+keys from the docker console into the gloang docker container and thats how I was able to `curl`

**Comment by peter-edge** [comment]
You may have to be more specific - how are you calling the Client constructor? If you call it without certificates, you don't get verification.
