### ISSUE TITLE
Import path rewriting and GO15VENDOREXPERIMENT do not mix

### ISSUE THREAD

**Issue by pwaller** [fsouza/go-dockerclient#348]
Please see https://github.com/golang/go/issues/12111.

In my case, `vendor.org/p` is `fsouza/go-dockerclient`. The basic problem is that I cannot import fsouza/go-dockerclient with `GO15VENDOREXPERIMENT` set (and I want to set it in all of my projects!). I think the only solution may be to avoid the rewriting or rename the `/vendor/` directory in this project.

**Comment by pwaller** [comment]
A recommendation from the linked issue is to use a directory called `internal` instead of `vendor`. (Though it is preferred to use the new vendoring way wherever it is possible. We might have to wait for GO15VENDOREXPERIMENT to become standard first though).

**Comment by peter-edge** [comment]
We already re-named it to external, see https://github.com/fsouza/go-dockerclient/pull/339 and https://github.com/fsouza/go-dockerclient/issues/338

**Comment by pwaller** [comment]
@peter-edge aha! Apologies for the noise, I missed the fact I was looking at an out of date module.

**Comment by peter-edge** [comment]
All good man haha
