### ISSUE TITLE
API Changes in Docker 1.8.0 

### ISSUE THREAD

**Issue by paulbellamy** [fsouza/go-dockerclient#350]
Particularly "Volumes" has been replaced with "Mounts" with a different format.

**Comment by itheiss** [comment]
Still unable to get Mounts previously Volumes from running container with commit d220186. In my opinion  ```Mounts          []Mount             `json:"Mounts,omitempty" yaml:"Mounts,omitempty"`'``` must be part of the ```Container struct```. Could you please verify this or is Docker 1.8 compatibility still WIP?

**Comment by cybercode** [comment]
@itheiss is correct. `Mounts` is not part of the `Config`, but part of the `Container`. The following (quick) patch will correct this (tested w/docker-gen):

```diff
diff --git a/container.go b/container.go
index 0b2fc4b..85b0256 100644
--- a/container.go
+++ b/container.go
@@ -214,7 +214,6 @@ type Config struct {
    NetworkDisabled bool                `json:"NetworkDisabled,omitempty" yaml:"NetworkDisabled,omitempty"`
    SecurityOpts    []string            `json:"SecurityOpts,omitempty" yaml:"SecurityOpts,omitempty"`
    OnBuild         []string            `json:"OnBuild,omitempty" yaml:"OnBuild,omitempty"`
-   Mounts          []Mount             `json:"Mounts,omitempty" yaml:"Mounts,omitempty"`
    Labels          map[string]string   `json:"Labels,omitempty" yaml:"Labels,omitempty"`
 }

@@ -282,6 +281,7 @@ type Container struct {

    Volumes    map[string]string `json:"Volumes,omitempty" yaml:"Volumes,omitempty"`
    VolumesRW  map[string]bool   `json:"VolumesRW,omitempty" yaml:"VolumesRW,omitempty"`
+   Mounts     []Mount           `json:"Mounts,omitempty" yaml:"Mounts,omitempty"`
    HostConfig *HostConfig       `json:"HostConfig,omitempty" yaml:"HostConfig,omitempty"`
    ExecIDs    []string          `json:"ExecIDs,omitempty" yaml:"ExecIDs,omitempty"
```

**Comment by fsouza** [comment]
@cybercode it's part of both types. Config is used only to create a container. Container is the result of the InspectContainer call.

**Comment by cybercode** [comment]
@fsouza thanks for the fix. I understood the difference between the container and the config, I guess I'm a bit confused as to why `inspect` returns an empty `Config.Mounts`.
