### ISSUE TITLE
support api v1.20 new ability - upload files to container

### ISSUE THREAD

**Issue by elasti-erezh** [fsouza/go-dockerclient#352]
Note that the new api deprecates the copy files or folders from a container.

Please support the new added ability to upload/download tarred files to/from a container.

From [docker remote api v1.20](https://docs.docker.com/reference/api/docker_remote_api_v1.20/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container) :
`PUT /containers/(id)/archive` - Upload an archive of content to be extracted to an existing directory inside a container’s filesystem.

**Comment by elasti-erezh** [comment]
started working on it and will send pull request when done

**Comment by fsouza** [comment]
@elasti-erezh thank you!

**Comment by jandre** [comment]
^^ does that work?  I need to figure out how to add a test for this.

**Comment by elasti-erezh** [comment]
@jandre i've tested it vs a live container and it works well.

Don't have a test for it yet..

**Comment by elasti-erezh** [comment]
@fsouza this can be closed right ? 
saw @jandre already took care of it 
Sorry for the lag and thank you

**Comment by fsouza** [comment]
@elasti-erezh no problem! Thanks for opening the issue.
