### ISSUE TITLE
More of a general question around documentation

### ISSUE THREAD

**Issue by EwanValentine** [fsouza/go-dockerclient#354]
Hi folks, 

Great library. Very easy to get up and running. However I was wondering if you have any full documentation for all of the available functions etc? I know this library matches the Docker external API, but I was struggling to work my way around this library (I'm a little new to Go). Is there some generic method for calling these api endpoints? Or a series of functions which match up?

**Comment by fsouza** [comment]
Hi @EwanValentine, thanks for opening this issue.

You will find all the methods in the client here: https://godoc.org/github.com/fsouza/go-dockerclient#Client.

There isn't a generic method for sending generic requests to an endpoint.

**Comment by EwanValentine** [comment]
This is perfect, thanks!
