### ISSUE TITLE
Events and swarm

### ISSUE THREAD

**Issue by aanm** [fsouza/go-dockerclient#366]
Hey, has anyone tried events with against a swarm agent?
I used this code

``` go
package main

import (
    "fmt"

    "github.com/fsouza/go-dockerclient"
)

func main() {
    endpoint := "tcp://127.0.0.1:2375"
    client, _ := docker.NewClient(endpoint)

    events := make(chan *docker.APIEvents)
    client.AddEventListener(events)

    for {
        select {
        case event := <-events:
            fmt.Printf("%#v\n", event)
        }
    }
}
```

If tcp://127.0.0.1:2375 doesn't exist I get this:

```
(*docker.APIEvents)(nil)
... #500000 more messages like that in 1 second
```

**Comment by EmileVauge** [comment]
I'm also getting nil events, when the docker server restarts for example.
This is clearly a bug.

**Comment by SpComb** [comment]
Are you sure that's not just a closed go channel return nil values? Try using

```go
for event := range events {
    fmt.Printf("%#v\n", event)
}   
```

FWIW I haven't noticed any issues when using go-dockerclient against swarm's `/events` API, apart from the extra "from" field embedded in the image name.

**Comment by carlskii** [comment]
This seems to work for me. How do I filter the events e.g. container start events only ?

**Comment by carlskii** [comment]
This seems to work for me. How do I filter the events e.g. container start events only ?
