### ISSUE TITLE
Logs - get two container Logs results in different goroutines at the same time.

### ISSUE THREAD

**Issue by openxxs** [fsouza/go-dockerclient#373]
## Container A is started by Goroutine A while Container B is started by Goroutine B, at the same time. Each goroutine has created docker client, and includes below code:

```
opts := docker.LogsOptions {
    Container:      containerId,
    OutputStream:   &buf,
    Follow:         true,
    Stdout:         true,
    Stderr:         true,
    Timestamps:     true,
}
err = client.Logs(opts)
containerLogs := buf.String()
```

---

It leads to strange containerLogs value: only one containerLogs is right while another one is empty. I have changed LogsOptions: Follow true<-->false, RawTerminal true<-->false. But they doesn't work.

**Comment by fsouza** [comment]
Can you show the creation of the buffer? Is it shared in the goroutines?

**Comment by openxxs** [comment]
Hi @fsouza , I define the buffer in each goroutines, just like this:
    var buf bytes.Buffer
I am sure they are independent.
If the container runs in a short time and products less logs, it works fine, both containerLogs are right. But complex container will cause the problem. It makes me confused.
