### ISSUE TITLE
client: trouble exiting from attached container

### ISSUE THREAD

**Issue by eliasgs** [fsouza/go-dockerclient#374]
Hi @fsouza,

Since somewhere around https://github.com/fsouza/go-dockerclient/commit/9702534da348f2aeafce8010d28a87d400cb724e, I have been having some trouble exiting from attached containers. Exiting waits for stdin and fails with: `read dev/stdin: bad file descriptor`

https://github.com/eliasgs/go-dockerclient/commit/97c85625bc5075fed8bb6ce16cebdc5e346c52b2 seems to fix it, but I am not entirely sure if there would be any undesired side effects with this?

Thanks,
Elias

**Comment by fsouza** [comment]
Hi @eliasgs, can you share a reproducer? Thanks!

**Comment by eliasgs** [comment]
Hi @fsouza 
Assuming you have the busybox image available, here is an example that reproduces the issue: https://github.com/eliasgs/reproducer/blob/master/main.go

Thanks:)

**Comment by fsouza** [comment]
Closed via #396.
