### ISSUE TITLE
Error during build image using private git repository 

### ISSUE THREAD

**Issue by nlamirault** [fsouza/go-dockerclient#376]
Hi
I try to build and image from a Git repository. It works with github public repository, but with a private Git repository i've got an error : 

```
Error trying to use git: exit status 128 (Cloning into '/var/lib/docker/tmp/docker-build-git601451926'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
)
```

How can i setup git authentication ?
Thanks

**Comment by fsouza** [comment]
Hi @nickethier, I'm not sure I understand the question, can you share some code? Thanks!

**Comment by nickethier** [comment]
@fsouza I think you meant to tag @nlamirault :)

**Comment by fsouza** [comment]
Waaaaat. @nickethier I'm sorry! haha

**Comment by nlamirault** [comment]
I make build options like that : 

```go
opts := docker.BuildImageOptions{
		Name:         imageName,
		Dockerfile:   "Dockerfile",
		Remote:      remote,
		OutputStream: outputbuf,
	}

	err := db.Client.BuildImage(opts)
```

if "remote" is a public repository (like https://github.com/docker/docker) it works fine.
If i setup a private git repository it failed. I suppose it's due to authorization / git authentication. 
Do you know how can i setup credentials ?
thanks
