### ISSUE TITLE
Large responses over Unix domain socket fail with 'use of closed network connection'

### ISSUE THREAD

**Issue by awh** [fsouza/go-dockerclient#378]
After the following commit

edc2bd38d8fa79581371ea78b3c09935877a1ade

commands which yield large (> ~4k) HTTP responses over a Unix domain connection fail with the message 'use of closed network connection'. The problem stems from the deferred `dial.Close()` statement:

https://github.com/fsouza/go-dockerclient/blob/edc2bd38d8fa79581371ea78b3c09935877a1ade/client.go#L405

As long as the headers and response body fit within 4k they will be read into memory during the call to `http.ReadResponse()` before the close operation occurs. When this is not the case, JSON decode fails later on trying to read the remainder of the body from the (now closed) socket.

We noticed this in weaveworks/weave#1410; inspect of certain containers (in particular those with volume mounts) with go-dockerclient failed as the returned JSON was big enough to exceed the buffer size of the initial read.

Unfortunately removing the `defer dial.Close()`, whilst fixing the immediate problem, leaks file descriptors - the `defer resp.Body.Close()` used by the clients of `do` does not appear to close the domain socket...

**Comment by fsouza** [comment]
@awh thanks for reporting it! I've just reverted edc2bd38d8fa79581371ea78b3c09935877a1ade so we can get to a proper solution for both issues.

**Comment by awh** [comment]
No problem - thanks for the prompt response!

**Comment by fsouza** [comment]
Closing in favor of #379.
