### ISSUE TITLE
UploadToContainer fails silently if user is not root

### ISSUE THREAD

**Issue by zramsay** [fsouza/go-dockerclient#384]
Godeps updated from 42d06e2b125654477366c320dcea99107a86e9c2 to c9ad0ce23f68428421adfc6ced9e6123f54788a5 for `UploadToContainer()` (see code [here](https://github.com/eris-ltd/eris-cli/pull/244)) and now our test for `Logs()` fails. It's not clear why since there doesn't appear to be a diff on that function between those two revisions.

**Comment by fsouza** [comment]
@zramsay I wasn't able to find the the error message in the build output (https://circleci.com/gh/eris-ltd/eris-cli/787), can you point me out to it, so we can understand what's going on?

Thank you!

**Comment by zramsay** [comment]
Yup. [Here it passes](https://gist.github.com/zramsay/9361135eb7d36f849eb6#file-logs_pass-L58), and [here it fails](https://gist.github.com/zramsay/4289eadb74637b19c3f0#file-logs_fail-L58). (tests run locally). The test starts [here](https://github.com/eris-ltd/eris-cli/blob/docker_cp/services/services_test.go#L131), and the call to `Logs()` is [made here](https://github.com/eris-ltd/eris-cli/blob/docker_cp/perform/docker_run.go#L660).

Between all that, a call is made to [this function](https://github.com/eris-ltd/eris-cli/blob/docker_cp/services/manage.go#L171) then [this one](https://github.com/eris-ltd/eris-cli/blob/docker_cp/services/operate.go#L199), then [here](https://github.com/eris-ltd/eris-cli/blob/docker_cp/perform/docker_run.go#L409).

Let me know if you need more info. Thanks!

**Comment by zramsay** [comment]
problem identified. see title change. closing; not an issue with this repo ... [`PUT`](http://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container) uses root by default and does not allow override.

**Comment by fsouza** [comment]
@zramsay thanks for coming back here. I didn't know Docker forces that :-( But I'm glad it works now!

**Comment by zramsay** [comment]
@fsouza no problem. I'm sure I'll be back!
