### ISSUE TITLE
Client.stream closes stdout/stderr

### ISSUE THREAD

**Issue by gavrie** [fsouza/go-dockerclient#385]
In `client.go`, in the `stream` method of `Client`, the stdout and stderr writers are closed when the method finishes.
It seems to me that this is wrong. For example, when passing `os.Stderr`, this causes the standard file descriptor to be closed and it cannot be used afterwards. This bit me and took a while to debug.

What if I want progress to be logged to stderr? Does this mean that I need to wrap it in another writer or use a pipe? Why not put the responsibility of closing the writer on the caller?

**Comment by gavrie** [comment]
If the behavior of closing the writers is required or relied on by others, how about a patch like this:

```
diff --git i/vendor/github.com/fsouza/go-dockerclient/client.go w/vendor/github.com/fsouza/go-dockerclient/client.go
index 3ba44e8..bc36e9b 100644
--- i/vendor/github.com/fsouza/go-dockerclient/client.go
+++ w/vendor/github.com/fsouza/go-dockerclient/client.go
@@ -467,12 +467,16 @@ func (c *Client) stream(method, path string, streamOptions streamOptions) error
        if streamOptions.stdout == nil {
                streamOptions.stdout = ioutil.Discard
        } else if t, ok := streamOptions.stdout.(io.Closer); ok {
-               defer t.Close()
+               if streamOptions.stdout != os.Stdout && streamOptions.stdout != os.Stderr {
+                       defer t.Close()
+               }
        }
        if streamOptions.stderr == nil {
                streamOptions.stderr = ioutil.Discard
        } else if t, ok := streamOptions.stderr.(io.Closer); ok {
-               defer t.Close()
+               if streamOptions.stderr != os.Stdout && streamOptions.stderr != os.Stderr {
+                       defer t.Close()
+               }
        }
        if protocol == "unix" {
                dial, err := c.Dialer.Dial(protocol, address)
```

**Comment by fsouza** [comment]
I do agree that we should rely on callers for closing the writers, but changing it now might introduce unexpected leaks, whenever the caller is relying on the current behavior.

I will remove the whole Close block, if it breaks existing code, we can then revert my commit and use those if conditions you presented to prevent closing os.Stdout and os.Stderr.

Thanks for raising this question.
