### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by onlyjob** [fsouza/go-dockerclient#403]
Formal releases are useful to downstream maintainers in order to define dependencies as well as to ship release-quality versions.
Please consider tagging. Thanks.

**Comment by adamveld12** [comment]
:+1:

**Comment by onlyjob** [comment]
Seriously this is important for defining dependencies. Please consider [Software versioning](https://en.wikipedia.org/wiki/Software_versioning).

**Comment by krise3k** [comment]
+1

**Comment by yassirh** [comment]
:+1:

**Comment by onlyjob** [comment]
See also

 * http://semver.org/
 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions)

**Comment by fsouza** [comment]
We're tagging releases now! Forgot about this issue x)

**Comment by onlyjob** [comment]
Thanks!
