### ISSUE TITLE
Failed to parse dockercfg because of colon (:) in password

### ISSUE THREAD

**Issue by ArneZsng** [fsouza/go-dockerclient#414]
When I tried to connect to Docker Hub, it mysteriously failed with the following error message:

Failed to parse dockercfg: Failed to read authentication from dockercfg

After playing around for quite a bit and looking into the code of go-dockerclient, I was able to figure out that the reason for this failure was that the Docker Hub password contained a colon (:) and thus this logic in auth.go fails:
```
userpass := strings.Split(string(data), ":")
		if len(userpass) != 2 {
			return nil, ErrCannotParseDockercfg
		}
```

The error was quite hard to find as the password was randomly generated and the string was base64 encoded but could possibly trouble a range of people.

**Comment by ArneZsng** [comment]
Thanks! :+1:

**Comment by fsouza** [comment]
@ArneZsng thank you for reporting it in the first place! :-)
