### ISSUE TITLE
is there a version control for this docker client?

### ISSUE THREAD

**Issue by Jam-Lin** [fsouza/go-dockerclient#422]
hi all,
   i use the docker 1.6 version,  i want to know which go-dockerclient commits is support for docker 1.6.  i use the latest code but there is something wrong, so is there a version control relate to the docker api version? thank you very much.

**Comment by fsouza** [comment]
@Jam-Lin unfortunately no :-( Can you share which errors you're facing?

I may rollback in time and add some tags to document compatibility with older releases of Docker.

**Comment by Jam-Lin** [comment]
thank you, it is a performance question. 
my config is: 
  go-dockerclient version: latest
  docker server: 1.6

test:
  1. i run 20 goroutine to create container -->start container(the image is pull in localhost).
  2. record the time for every goroutine,
  3. the result is: 
1st container: spent: 468.368225ms
2nd container: spent: 838.847678ms
3rd container: spent: 1.391688069s
..: spent: 2.067306631s
..: spent: 2.18801109s
..: spent: 2.4040604s
..: spent: 2.593022622s
the last: spent: 6.695398777s

it seems to the time is increasing, but i was run 20 goroutine,  is the go-dockerclient has a queue to create the container? when i use the docker run command with -d, the time is very fast. i hope you can help me.
