### ISSUE TITLE
CI for docker 1.9?

### ISSUE THREAD

**Issue by achanda** [fsouza/go-dockerclient#424]
The default version of docker that travis provides is 1.7. Thus we are not testing anything post that. With a bunch of new features in 1.9, this was bothering me. I was trying to test against 1.9 and came across this error:
https://travis-ci.org/achanda/go-dockerclient/jobs/93640319

I need some help in getting this to work. I do see that those packages are in GOPATH, but I'm not sure why those are not being located.

**Comment by fsouza** [comment]
Seems like you're fighting a different issue. I will try to use travis's matrix to run tests against different versions of Docker. Thanks for raising this issue!

**Comment by fsouza** [comment]
@achanda I solved it with the environment variables in travis.yml. We now have lots of jobs, but Travis can handle it :)

https://travis-ci.org/fsouza/go-dockerclient/builds/93961172

**Comment by achanda** [comment]
Awesome @fsouza :) I will close this issue now.
