### ISSUE TITLE
How can i get number of containers or images?

### ISSUE THREAD

**Issue by erolg** [fsouza/go-dockerclient#425]
I tried "cap" and "len" command but both of these didn't help.

```len(client.ListContainers(docker.ListContainersOptions{All: true}))```
```cap(client.ListImages(docker.ListImagesOptions{All: true}))```

How can i get number of containers or images?

**Comment by fsouza** [comment]
len should world, but keep in mind that these methods return both the list and an error:

```go
containers, err := client.ListContainers(docker.ListContainersOptions{All: true})
if err != nil {
  // handle error
}
fmt.Printf("containers: %d\n", len(containers))

**Comment by erolg** [comment]
@fsouza thanks!
