### ISSUE TITLE
CreateNetwork error decode doesn't work

### ISSUE THREAD

**Issue by bboreham** [fsouza/go-dockerclient#427]
It appears [this](https://github.com/fsouza/go-dockerclient/blob/master/network.go#L96) doesn't work, since the error comes back from Docker as http 500.

example:

```
error: *docker.Error API error (500): network with name weave already exists
```

**Comment by fsouza** [comment]
Sounds like a bug in Docker itself. I will do further investigation on that.

**Comment by fsouza** [comment]
Just reported docker/docker#18363.

Let's see what comes next.
