### ISSUE TITLE
Question: Docker logs

### ISSUE THREAD

**Issue by diptanu** [fsouza/go-dockerclient#443]
Hi @fsouza 

I am trying to use this client to stream logs from a docker container. Unfortunately when I use the follow option the io reader doesn't read anything. When the follow is turned off, things work just fine.

Here is the code 

```
func  (h *DockerDriver) Logs(follow bool, stdout bool) (io.Reader, error) {
	var buf bytes.Buffer
	err := h.client.Logs(docker.LogsOptions{
		Container:    h.containerID,
		OutputStream: &buf,
		Stdout:       stdout,
		Follow:       follow,
	})
	if err != nil {
		return nil, err
	}
	return &buf, nil
}

rdr, _ := h.Logs(true, true)

io.Copy(os.Stdout, rdr)
```

This never prints anything for me if i set follow as ```true``` but works as expected if I set follow as ```false```

Probably doing something silly here, any pointers would be appreciated.

**Comment by diptanu** [comment]
@fsouza So figured out what's happening, the call to client.Logs is blocking, but still not sure why.

**Comment by diptanu** [comment]
@fsouza When follow is set to ```true``` this is where the call to Logs block https://github.com/fsouza/go-dockerclient/blob/master/client.go#L541

Can you please provide some pointers around what's happening?

**Comment by diptanu** [comment]
@fsouza So two questions -

a. So it feels like the Logs method on the client was designed to be called from a go-routine? Other then that I feel there is no way to stream the logs the they are being copied into the io.Writers by the client.

b. And if the call to Logs happens on a go-routine, how do we cancel the go-routine?

**Comment by diptanu** [comment]
Closing this ticket since now I understand the intended use of the Log API.

**Comment by fsouza** [comment]
Hi @diptanu, sorry about the late response. The logs goroutine will die automatically whenever the container dies. Currently there's no other way of canceling it. You can alternatively using Attach with the non-blocking option, which returns a CloseWaiter, and then you can call the method Close when you want to detach.
