### ISSUE TITLE
AttachToContainer - Content-Type error with 1.10

### ISSUE THREAD

**Issue by beetree** [fsouza/go-dockerclient#455]
I have a setup using .AttachToContainer. After upgrading to Docker 1.10-rc2 I'm getting an error `Content-Type specified (plain/text) must be 'application/json'`.

Why am I getting this?

Any help would be great!

/beetree

**Comment by beetree** [comment]
Row 590 in this file: https://github.com/fsouza/go-dockerclient/blob/b3de6cfc437eb5bb97b5b28ed827bcdbd7860e22/client.go

I think that should be changed to `application/json`.

**Comment by beetree** [comment]
Confirmed. Changing line 590 fixes the problem. If there's a 1.10 branch I'd be happy to submit the fix myself...?

**Comment by fsouza** [comment]
@beetree do you know if using application/json in previous versions of the API work? If so, you can send the change right away. Otherwise we should provide a solution for supporting both ``plain/text`` and ``application/json``.

**Comment by beetree** [comment]
No sorry, haven't tested that.

**Comment by fsouza** [comment]
No problem, I'm on it right now! :-)

**Comment by fsouza** [comment]
@beetree just pushed a fix for this issue, can you give it a try? Thanks!

**Comment by beetree** [comment]
Confirmed, working.

**Comment by gopinatht** [comment]
@beetree @fsouza What version of docker has the fix been pushed to? How can I access it?

**Comment by beetree** [comment]
Of docker? The current dockerclient should work with both docker 1.9.1 and
1.10. The old version of dockerclient was not working with docker 1.10.

**Comment by gopinatht** [comment]
@beetree: Aha, my mistake. I am seeing this error coming from the kubectl world and am not completely familiar with the go dockerclient. So I mistakenly thought this was a fix went directly into the docker. Apologies and thanks for the clarification.

**Comment by fsouza** [comment]
@gopinatht it should be fixed in the next version of Kubernetes as well.
