### ISSUE TITLE
Equivalent of `-v /path:/path:ro` using go-dockerclient?

### ISSUE THREAD

**Issue by dalanmiller** [fsouza/go-dockerclient#464]
I'm wondering how do a I replicate the same pattern using `go run -v /path:/path:ro` using go-dockerclient? I'm assuming I'm supposed to use `docker.Mount` under `Config` when using `CreateContainer` but nothing is working. 

In my use case, I'm trying to mount the LetsEncrypt directory into my container:

```go
config := docker.Config{
			...
			// Set mount point for LetsEncrypt certs
			Mounts: []docker.Mount{
				{
					Name:        "tls",
					Source:      "/etc/letsencrypt/",
					Destination: "/root/tls",
				},
			},
            ...
		} 
		
```

Ultimately, I get no errors and no mount points in the resulting container. I've also tried with setting the other properties on `docker.Mount` such as `Mode` and `Driver` and `RW` to no avail.

**Comment by jmparra** [comment]
According to the [API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container) you should use `HostConfig.Binds`

```Go
HostConfig := &docker.HostConfig{Binds: []string{"/ets/letsencrypt/:/root/tls:ro"}}
```

**Comment by dalanmiller** [comment]
Thank you @jmparra, I obviously totally overlooked this.
