### ISSUE TITLE
Implement login command

### ISSUE THREAD

**Issue by faiq** [fsouza/go-dockerclient#468]
hey- docker has a built in docker command called login which lets you use a certain registry with a given username, password and email. typically you would run the command like this

`docker login -u USERNAME -p PASSWORD  REGISTRY`

and typically a new file called `.docker/config.json` is modified or made in the user's home directory which allows them to pull and push from different registry providers.

i'm suggesting we implement a login command which takes in options similar to how the cli does it- 

https://github.com/docker/docker/blob/7ecba9c6687ee922b1c77add0c92ad11858de558/api/client/login.go#L23#L70

this would make it really easy for me to programmatically edit and save the config file which would be quite helpful for integrating a project i have with [Amazon ECR](http://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html)

**Comment by ido50** [comment]
Also "docker logout"

**Comment by ErezHorev** [comment]
+1
