### ISSUE TITLE
What's the equivalent of `-p` from `docker run`?

### ISSUE THREAD

**Issue by dalanmiller** [fsouza/go-dockerclient#470]
I'm trying to publish a container port on a specific host port. If I were using the command line, I know this works fine: `docker run -p 5050:8080` 

Here's what I have in my code.
```
hostConfig.PortBindings = map[docker.Port][]docker.PortBinding{
    "8080/tcp": []docker.PortBinding{
	{HostPort: serveHTTPPort},
    },
}
```
The port is ultimately unpublished though.

**Comment by jmparra** [comment]
I understand there is no documentation, [but the test are very useful](https://github.com/fsouza/go-dockerclient/blob/master/testing/server_test.go#L595)

```go
HostConfig: &docker.HostConfig{
	PortBindings: map[docker.Port][]docker.PortBinding{
		"8080/tcp": {{HostPort: serveHTTPPort}},
	},
}
```

**Comment by dalanmiller** [comment]
Looks like that's not working for me either. Do I need to set any other settings in `HostConfig` or `Config`?

**Comment by jmparra** [comment]
the [latest versions](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#start-a-container) of Docker need `HostConfig` in `CreateContainer`, maybe this can help you.

**Comment by dalanmiller** [comment]
Do my `HostConfig` settings need to be identical for `CreateContainer` as well as `StartContainer`?

**Comment by fsouza** [comment]
@dalanmiller only if you want to override it when starting the container, otherwise you can set it to nil in the StartContainer call.

**Comment by dalanmiller** [comment]
Hey guys, I found my problem! I was doing this:

```
client.StopContainer(container.ID, 0)
```

And then immediately trying to start a new container with the same exact port. Adding a delay of 3 seconds gave the server enough time to detach the container from the port I assume. As starting a new container with the same exposed port now works fine.
