### ISSUE TITLE
Ping() timeout

### ISSUE THREAD

**Issue by yassirh** [fsouza/go-dockerclient#473]
Hi. what is the default timeout duration? and is there a way to configure it? thanks

**Comment by fsouza** [comment]
Hi @yassirh, the ping is a regular request, so you cannot set a timeout to this operation only. Timeouts can be controlled by overriding the HTTPClient used by the library. If you really wanna have a specific timeout for the ping operation, you can create a client instance just for it:

```go
client, err := docker.NewClient("tcp://127.0.0.1:2375")
// handle err
transport := http.Transport{
	Dial: (&net.Dialer{
		Timeout:   time.Second,
		KeepAlive: 10 * time.Second,
	}).Dial,
	TLSHandshakeTimeout: time.Second,
}
client.HTTPClient = &http.Client{Transport: &transport, Timeout: 2 * time.Second}
```

The timeout in the Dialer is the timeout for establishing the TCP connection. There's also another timeout for the TLS handshake, if you're using TLS-enabled Docker API. And the overall timeout is the timeout in the http.Client instance.

**Comment by yassirh** [comment]
@fsouza that is very enlightening thank you.
