### ISSUE TITLE
Client.Info() return does not correctly reflect returned data

### ISSUE THREAD

**Issue by cezarsa** [fsouza/go-dockerclient#474]
Currently [(*Client).Info()](https://github.com/fsouza/go-dockerclient/blob/2705b71/misc.go#L28) return is an `Env` instance which is in fact a `[]string` where each entry is in the format `key=value`.

This does not correctly represent the response from `GET /info` route. According to [docker api docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#display-system-wide-information) the response is a complex json. My opinion is that go-dockerclient should have a custom struct mapping these fields.

**Comment by fsouza** [comment]
Closing, as #476 has been merged.
