### ISSUE TITLE
Unexpected behavior of AttachToContainerNonBlocking

### ISSUE THREAD

**Issue by cezarsa** [fsouza/go-dockerclient#478]
If one wants to mimic the behavior of the `docker run` command using go-dockerclient a common approach would be:

``` go
client.CreateContainer()
opts := AttachToContainerOptions{OutputStream: buffer}
waiter := client.AttachToContainerNonBlocking(opts)
client.StartContainer()
waiter.Wait()
println("container output:", buffer.String())
```

However, this code is wrong. There's a chance that the container will be started and finished before the attach request is even made. This happens because `AttachToContainerNonBlocking` returns before the attach request is sent to the docker server. To fix this behavior the correct approach would be:

``` go
client.CreateContainer()
opts := AttachToContainerOptions{OutputStream: buffer, Success: make(chan struct{})}
waiter := client.AttachToContainerNonBlocking(opts)
<-opts.Success
close(opts.Success)
client.StartContainer()
waiter.Wait()
println("container output:", buffer.String())
```

In this case, the `Success` channel is used to let the user know that the request have already been sent to docker and we're attached to the container. It's not clear, though, that using this channel is needed when attaching to a container with the purpose of capturing its output. This may trick a lot of users into having inconsistent responses from containers. (I for one have been tricked before)

I propose that we change the `AttachToContainerNonBlocking` method to only return after ensuring that go-dockerclient is already attached to the container. This could be done in a backwards compatible way by only waiting for attaching if `opts.Success` channel is `nil`. If it's not nil it's possible that the user is already doing the right thing.

**Comment by logicminds** [comment]
What if this is a container that is interactive?  Meaning we also need to write to stdin and get stdout?

Example: ruby irb session
