### ISSUE TITLE
Filtering events 

### ISSUE THREAD

**Issue by carlskii** [fsouza/go-dockerclient#483]
I've worked out how to make a simple event listener. However, I need to filter so that only `start` and `die` events are monitored. I can't seem to work out how to add the filter using go. 

```
events := make(chan *docker.APIEvents)
client.AddEventListener(events)

for {
    select {
    case event := <-events:
        fmt.Printf("%#v\n", event.Status)
    }
}
```

**Comment by cirocosta** [comment]
I think it's worth pointing out that filtering is actually supported by the Remote API

**Comment by realshuting** [comment]
Do we have any update on this? Filtering events is definitely needed.

**Comment by stokito** [comment]
This feature was just merged. Here is an usage example:

	filters := map[string][]string{
		"type":  {"container"},
		"event": {"create", "destroy", "start", "stop", "pull", "attach"},
	}
	opts := EventsOptions{Filters: filters}
	err = client.AddEventListenerWithOptions(opts, listener)

I'll recommend you at least filter our health check events because it's too many of them.
Please test it and report any bugs
