### ISSUE TITLE
drop local customisations to "github.com/hashicorp/go-cleanhttp"

### ISSUE THREAD

**Issue by onlyjob** [fsouza/go-dockerclient#487]
Bundled/vendored _go-cleanhttp_ is customised: 9d655b36b02eca3965472ce35b89ddae3c87121c

Please consider forwarding your improvement upstream and use pristine [go-cleanhttp](http://github.com/hashicorp/go-cleanhttp) library. Thanks.

**Comment by onlyjob** [comment]
FYI @orivej

**Comment by orivej** [comment]
This is not a local customization but a previous upstream. And the previous upstream is more useful than the current one. See https://github.com/fsouza/go-dockerclient/pull/434#issuecomment-195063684.

**Comment by orivej** [comment]
Do you attempt to unbundle go-dockerclient?

**Comment by onlyjob** [comment]
Thanks. I did not realise they've removed this code from _go-cleanhttp_. Anyway this is to be discussed with upstream to avoid maintenance burden of maintaining a fork.

> Do you attempt to unbundle go-dockerclient?

You mean _go-cleanhttp_? Yes, downstream (in Debian) we need a modular build reusing system _go-cleanhttp_ library...

**Comment by fsouza** [comment]
@onlyjob the point in vendoring is pinning a version that is supported by the library. I don't see a compiling reason for updating go-cleanhttp at the moment.

I agree that party does a terrible job at tracking which version of each dependency we're using though.

**Comment by onlyjob** [comment]
> the point in vendoring is pinning a version that is supported by the library.

That's why we need to use versioning. Downstream distributions can't rely on vendoring and have to reuse system packages (which is a much better approach). Unfortunately "vendoring" in Golang throws away 20+ years of best practices in software engineering... :(

> I don't see a compiling reason for updating go-cleanhttp at the moment.

When do you suppose this might change?

**Comment by fsouza** [comment]
Closing, as go-dockerclient is no longer vendoring. See 9d5fef7969a53796f7405827c3e68804f533b1ee for more details.
