### ISSUE TITLE
"API error (500): manifest unknown: manifest unknown" when trying to PullImage()

### ISSUE THREAD

**Issue by ihsw** [fsouza/go-dockerclient#488]
I am trying to run `PullImage()` but I keep getting a "manifest unknown" error.

This is the repository I am trying to pull: https://hub.docker.com/r/ihsw/omega-jazz/

And the repository param is: "ihsw/omega-jazz"

**Comment by fsouza** [comment]
@ihsw can you share some code? What's the version of your remote Docker host?

**Comment by ihsw** [comment]
I'm just running:

    client.PullImage(docker.PullImageOptions{Repository: "ihsw/omega-jazz"}, docker.AuthConfiguration{})

And here is my Docker version: Docker version 1.9.1, build a34a1d5

**Comment by prateekgogia** [comment]
I am also hitting this error in Docker version 1.9.1, but works fine in 1.10.1. However, would like this to work in version 1.9.1. Here is the error and docker version:
API error (500): repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
