### ISSUE TITLE
API Events listener fails with OS X private beta

### ISSUE THREAD

**Issue by drewwells** [fsouza/go-dockerclient#495]
During debugging, I noticed that requesting a listener channel always fails in the OS X private beta. Not sure if it's a docker bug, or go-dockerclient bug. No errors are given on this call, so at least it would be helpful to add error context when this call fails. Other docker calls worked just fine. If there are workarounds, it would be great to list them here.

Communication type: socket `/var/run/docker.sock` (it's like running on linux!)
Version info

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by nickvanw** [comment]
Hmmm, this is interesting! I'm in the Docker for Mac beta as well -- I'll give this a go sometime this weekend or week.
