### ISSUE TITLE
PullImage function fails with private registry endpoints

### ISSUE THREAD

**Issue by benton** [fsouza/go-dockerclient#498]
I am having a problem using the [PullImage][1] method to download Docker images from any registry endpoint other than the public registry (in my case, [Amazon ECR][2]).  

I believe that the following sample code *should* attempt to pull an image from the registry endpoint `https://bogus-hostname.whatever.com`, and should therefore produce some sort of "host not found" error. Instead, the code is ignoring the `Registry` and `ServerAddress` values in the call to `PullImage`, and attempts to contact `https://registry-1.docker.io` instead!

    package main

    import (
    	"fmt"

    	"github.com/fsouza/go-dockerclient"
    )

    func main() {
    	c, err := docker.NewClientFromEnv()
    	err = c.PullImage(docker.PullImageOptions{
    		Registry:   `bogus-hostname.whatever.com`,
    		Repository: `some/repo`,
    		Tag:        `latest`,
    	}, docker.AuthConfiguration{
    		Username:      `AWS`,
    		Password:      `(fecthed-from-ecr-api)`,
    		Email:         `none`,
    		ServerAddress: `https://bogus-hostname.whatever.com`,
    	})
    	if err != nil {
    		fmt.Println("ERROR pulling:", err)
    	}
    }

The output produced by this program is:

    ERROR pulling: API error (401): Authentication is required: 
    Get https://registry-1.docker.io/v2/some/repo/manifests/latest: 
    unauthorized: incorrect username or password

It *should* be some message saying that host `bogus-hostname.whatever.com` does not exist. (Or, if it *does* exist, the same 401 error as above, only with the correct hostname reported!)

Am I passing the wrong data for using a private registry to the API call? Is there example code somewhere that demonstrates how to accomplish this?

Thanks,
-benton

[1]:https://godoc.org/github.com/fsouza/go-dockerclient#Client.PullImage
[2]:https://aws.amazon.com/ecr/

**Comment by carsonoid** [comment]
This happened to me. You need to ignore the registry param and just put the full registry/repo path in the repository field.

So instead of:
```
docker.PullImageOptions{
        Registry:   "bogus-hostname.whatever.com",
        Repository: "some/repo",
        Tag:        "latest",
    }
```

Use:
```
docker.PullImageOptions{
        Registry: "",
        Repository: "bogus-hostname.whatever.com/some/repo",
        Tag:        "latest",
    }
```

I don't think there is support for a "Registry" field when calling /images/create.

**Comment by benton** [comment]
@carsonoid Thank you!
