### ISSUE TITLE
Info() fails on Docker 1.6

### ISSUE THREAD

**Issue by krallin** [fsouza/go-dockerclient#503]
As opposed to e.g. Docker 1.10, older versions of Docker return integer values for the (pseudo) boolean values in the info call. 

Here's e.g. what Docker 1.6.2 returns (note: I do not know when exactly that output changed, but I do know that it's integers on Docker 1.6.2 as opposed to booleans on Docker 1.10.3 — I can try and figure out the exact version difference if needed):

```
{
    "Containers": 6,
    "Debug": 0,
    "DockerRootDir": "/var/lib/docker",
    "Driver": "aufs",
    "DriverStatus": [
        [
            "Root Dir",
            "/var/lib/docker/aufs"
        ],
        [
            "Backing Filesystem",
            "xfs"
        ],
        [
            "Dirs",
            "181"
        ],
        [
            "Dirperm1 Supported",
            "true"
        ]
    ],
    "ExecutionDriver": "native-0.2",
    "ID": "U43F:6VP4:VR6J:JZ7N:HNFY:OWJP:RHEH:42TA:DYN4:OWXU:2BAM:BHAQ",
    "IPv4Forwarding": 1,
    "Images": 169,
    "IndexServerAddress": "https://index.docker.io/v1/",
    "InitPath": "/usr/bin/docker",
    "InitSha1": "7f9c6798b022e64f04d2aff8c75cbf38a2779493",
    "KernelVersion": "3.16.0-29-generic",
    "Labels": null,
    "MemTotal": 4143697920,
    "MemoryLimit": 1,
    "NCPU": 2,
    "NEventsListener": 0,
    "NFd": 27,
    "NGoroutines": 41,
    "Name": "app-longcat",
    "OperatingSystem": "Ubuntu 14.04.4 LTS",
    "RegistryConfig": {
        "IndexConfigs": {
            "docker.io": {
                "Mirrors": null,
                "Name": "docker.io",
                "Official": true,
                "Secure": true
            }
        },
        "InsecureRegistryCIDRs": [
            "127.0.0.0/8"
        ]
    },
    "SwapLimit": 0,
    "SystemTime": "2016-04-15T12:48:37.98444477Z"
}
```

However, `Info()` only accepts boolean, so it fails to parse this output and throws a de-serialization error.

Is Docker 1.6.2 meant to be supported? If so, it might be worth accepting integers and booleans for those. The work around in [this SO answer](http://stackoverflow.com/questions/30856454/golang-how-to-unmarshall-both-0-and-false-as-bool-from-json) worked perfectly for me, and I'm able to use the `Info()` call successfully.

I'm happy to submit a PR if Docker 1.6.2 is supposed to be supported. Just let me know!

Thanks!

**Comment by krallin** [comment]
Quick additional data point: Docker 1.9.1 returns booleans (i.e. it's not affected).

**Comment by peter-edge** [comment]
This one is...fun.

So overall, go-dockerclient generally just parses JSON directly, to do a split on this, having an intermediate struct with fields of `json.RawMessage` would probably be the way to go, and then switch based on the type. There's other places in the code I'd want this to be done too, namely strings (like the `State` string for containers that only has a static set of values `Running, Exited, ...`) where we could transform the values to constants. This is a lot of work and should be thought out, but if you have a few hours on your hands... :)

**Comment by fsouza** [comment]
Docker 1.6 is ancient now :D :D :D Closing.
