### ISSUE TITLE
APIMount.RW should be bool - listContainers fail

### ISSUE THREAD

**Issue by tahmmee** [fsouza/go-dockerclient#507]
Looks like recent regression from
https://github.com/fsouza/go-dockerclient/commit/88cf489573aa4e48954412d865600a715c3639d9#diff-4042076be99ff99c0353b4d447624156R52

Where json is decoding RW to bool, whereas the field is defined as a string, leading to err
json: cannot unmarshal bool into Go value of type string

             "Mounts": [
                     {
                              "Name": "fac362...80535",
                              "Source": "/data",
                              "Destination": "/data",
                              "Driver": "local",
                              "Mode": "ro,Z",
                              "RW": false,
                              "Propagation": ""
                     }
             ]
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#list-containers

**Comment by fsouza** [comment]
Ops, sorry about that. Just pushed a fix.

Thanks for reporting.

**Comment by tahmmee** [comment]
nice +thanks
