### ISSUE TITLE
Tty required?

### ISSUE THREAD

**Issue by raphink** [fsouza/go-dockerclient#509]
When I try to run a program using this library as a container without a tty attached, I get errors `inappropriate ioctl for device`.

Is it necessary to have a TTY attached to the process?

I don't get this with every action:
- `ListVolumes` works
- `InspectVolume` fails

**Comment by fsouza** [comment]
Hi @raphink. No, TTY should not be required. Can you share some code that reproduces the issue?

**Comment by raphink** [comment]
@fsouza I'm having this issue with https://github.com/camptocamp/conplicity/blob/master/conplicity.go. When I put it in a container and run without a tty:

```shell
$ docker run -v /var/run/docker.sock:/var/run/docker.sock --rm camptocamp/conplicity:0.4.0
time="2016-04-18T20:47:23Z" level=error msg="Failed to start container for volume temp: inappropriate ioctl for device" 
time="2016-04-18T20:47:23Z" level=error msg="Failed to process volume temp: inappropriate ioctl for device"
```

but it works with `-t`.

**Comment by fsouza** [comment]
Hi @raphink, did you find what was wrong? I was looking into it and was unable to reproduce it with the command you provider (see output below) :/ Which version of Docker you're running?

```
% docker run -v /var/run/docker.sock:/var/run/docker.sock --rm camptocamp/conplicity:0.4.0
Unable to find image 'camptocamp/conplicity:0.4.0' locally
0.4.0: Pulling from camptocamp/conplicity
3dbc7ce873ca: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:483b5ae6b70b36992d934aba3ba044ea4856f101ca8c36fb1cf709b5608eda75
Status: Downloaded newer image for camptocamp/conplicity:0.4.0
time="2016-04-23T17:07:52Z" level=info msg="Starting backup..."
time="2016-04-23T17:07:52Z" level=info msg="Pulling image camptocamp/duplicity:latest"
time="2016-04-23T17:09:04Z" level=info msg="End backup..."
% docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   a5315b8
 Built:        Mon Apr 18 19:19:21 2016
 OS/Arch:      linux/amd64
```

**Comment by raphink** [comment]
You probably don't have any volumes on your machine. Can you try creating a volume and launching it again?

**Comment by fsouza** [comment]
Oh, makes sense. Will try that!
