### ISSUE TITLE
CreateContainer with user defined network not work

### ISSUE THREAD

**Issue by dongmx** [fsouza/go-dockerclient#513]
I create a contaienr with `HostConfig.NetworkMode = "xxx"`.  And when container running, `docker inspect` shows that `NetworkMode` is `"default"`. I think maybe you missing `NetworkingConfig` in type `CreateContainerOptions`.

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.0
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   a6c1f14
 Built:        Wed Apr 13 05:58:31 UTC 2016
 OS/Arch:      linux/amd64
```

**Comment by fsouza** [comment]
Hi @dongmx, thanks for reporting this issue. Can you share the piece of code that you're using to test this?

**Comment by dongmx** [comment]
It's should be easy to test. User `docker network create xxx` create a network, then create a container which `HostConfig.NetworkMode = "xxx"` and start it with go-dockerclient. Then docker inspect to check this container's `NetworkMode `.

**Comment by fsouza** [comment]
Can you try with NetworkingConfig, as of the changes from PR #519?
