### ISSUE TITLE
go dockerclient support context?

### ISSUE THREAD

**Issue by WIZARD-CXY** [fsouza/go-dockerclient#516]
I wonder if there is any support on context using in client.
context info : https://blog.golang.org/context.
I think it would be nice if I can cancel a ongoing client request. 
Thanks

**Comment by fsouza** [comment]
Hi @WIZARD-CXY, currently go-dockerclient doesn't offer contexts or other general methods for canceling in-flight requests. I believe it would be a nice thing to have, though.

**Comment by WIZARD-CXY** [comment]
@fsouza I think it would be nice too, maybe I can help you with it.

**Comment by fsouza** [comment]
go-dockerclient supports context now! :D
