### ISSUE TITLE
Proper pull output

### ISSUE THREAD

**Issue by paralin** [fsouza/go-dockerclient#521]
When pulling, if I attach the output to Stdout, I get a lot of spammy output, basically one line for each progress update tick. 

Is there any way to get nicely printed progress output, like in the official docker client?

**Comment by pietv** [comment]
@paralin you can take a note how we have this using the docker `jsonmessage` package: https://github.com/eris-ltd/eris-cli/blob/master/perform/perform.go#L743-L770

Though would really love `dockerclient` have a better looking output itself.

**Comment by fsouza** [comment]
go-dockerclient now uses the jsonmessage package, so the output is better now! :D
