### ISSUE TITLE
CreateNetworkOptions.Options is wrong type

### ISSUE THREAD

**Issue by bboreham** [fsouza/go-dockerclient#527]
At https://github.com/fsouza/go-dockerclient/blob/master/network.go#L115 it's `map[string]interface{}`, but at https://github.com/docker/engine-api/blob/master/types/types.go#L449 it's `map[string]string`

I could submit a PR, but thought I would seek your view on making such a breaking (and not very important) change.

CC @dcbw who seems to have added this line in the first place (likely Docker had the same type back then)

**Comment by fsouza** [comment]
Hi @bboreham, sorry for the delayed response, and thanks for reporting this issue. I'm not sure if Docker changed that, but it's unfortunate that we're not using the exact same type. That being said, it still works if the user uses only strings as values in the Options map. It's far from ideal, but I'd not want to make this breaking change :-(

**Comment by bboreham** [comment]
OK, no problem
