### ISSUE TITLE
misleading error generated by 404 from docker daemon

### ISSUE THREAD

**Issue by joeshaw** [fsouza/go-dockerclient#528]
`client.CreateContainer` interprets any 404 from the server as a "no such image" error (`ErrNoSuchImage`), but there are other problems that can cause a 404 error.

One problem that I'm running into with the Docker for Mac beta is that the `LogConfig` inside the `HostConfig` points to a syslog unix socket in the container that does not exist: `LogConfig:{Type:syslog Config:map[syslog-address:unix:///var/folders/r0/m8hpb98s4xj8z9q5vfd6f1w102j22s/T/plugin563018527]}`

The error I get when trying to start the container from the API is `API error (404): stat /var/folders/r0/m8hpb98s4xj8z9q5vfd6f1w102j22s/T/plugin563018527: no such file or directory` but go-dockerclient is interpreting and returning `ErrNoSuchImage` which isn't right, and makes tracking down the real issue harder.

I wonder if rather than checking for a 404 error it'd be better to do explicit string matching.

**Comment by fsouza** [comment]
Hi @joeshaw, thanks for opening this issue. It used to be in the past the createContainer reported 404 only when the image didn't exist, and we didn't catch up with changes in Docker daemon.

**Comment by prateekgogia** [comment]
Seeing the same issue, when network name provided for create container call in opts is not found. Error returned is - "no such image". Actual error response body - "network failme not found".

@fsouza - I can submit a PR for this error fix.
