### ISSUE TITLE
Is client safe for concurrent use by multiple go-routines?

### ISSUE THREAD

**Issue by selvik** [fsouza/go-dockerclient#529]
I was wondering if I can create a TLS client once (NewTLSClient) and reuse it repeatedly from multiple goroutines throughout the duration of my application?
Or is the recommended usage to create a client for each API call? 

Thank you for any hints!

**Comment by fsouza** [comment]
Hi @selvik, it is supposed to be safe. We've been using it with [tsuru](https://github.com/tsuru/tsuru) with no problems.

The tests run on Travis with the race detector enabled. We might not have coverage for some edge cases tho.

Please let me know if you find any bad/unexpected behavior!

**Comment by selvik** [comment]
@fsouza Thank you very much for the prompt response - we were going to make a design change and this is very helpful feedback. 👍 I will be changing our usage and will let you know if we find anything go amiss.
