### ISSUE TITLE
Support DOCKER_CONFIG environment variable

### ISSUE THREAD

**Issue by margueritepd** [fsouza/go-dockerclient#530]
The docker cli supports the `DOCKER_CONFIG` environment variable to indicate where the client should look for docker configuration vs the default `~/.docker`). See [the docs](https://docs.docker.com/v1.8/reference/commandline/cli/#configuration-files)

`go-dockerclient` should support it too, and/or passing in the docker config path explicitly.

**Comment by fsouza** [comment]
Looks good, could you include a test and open the PR? Thanks!

**Comment by fsouza** [comment]
Since the PR has been merged, I'm going to close this issue. Thanks for opening it and for contributing with the needed changes!
