### ISSUE TITLE
Beta Docker Windows support

### ISSUE THREAD

**Issue by pietv** [fsouza/go-dockerclient#531]
A question: does dockerclient support the Beta Docker for Windows which uses the endpoint

```
endpoint := "npipe:////./pipe/docker_engine"
```
instead of 
```
endpoint := "unix:///var/run/docker.sock"
```
https://github.com/docker/docker/blob/master/opts/hosts_windows.go#L6
https://github.com/docker/docker/blob/master/opts/hosts.go#L26
https://github.com/docker/docker/blob/master/opts/hosts.go#L63-L83

Thank you in advance.

**Comment by fsouza** [comment]
Hi @pietv, it isn't currently supported, I could look into that, but unfortunately I don't have access to a Windows Machine with Beta Docker for Windows to test it.

Could you help testing?

**Comment by pietv** [comment]
Hi @fsouza, sure! I'm happy to test it on a Windows 10 machine. Thank you!

**Comment by fsouza** [comment]
Awesome, thanks! I will dig it up, prepare a pull request and notify you. I won't be able to work on that today, but I hope I can have something by Monday.

Thanks for opening the issue.

**Comment by pietv** [comment]
Monday is great! Not at all! Thank you! :)

**Comment by fsouza** [comment]
@pietv I'm running late :-( Unfortunately it's more complicated than I thought (I'll need a new dependency for handling named pipes). I'm still working on that.

**Comment by pietv** [comment]
@fsouza thank you for the update! yes, I've noticed the `DialPipe` machinery on the Docker side which didn't look very straightforward to incorporate. No rush and thank you!

**Comment by zramsay** [comment]
@fsouza have you made any progress on this front? Now that Docker for Windows is out of beta, users are asking for supported integration. Perhaps there is work @pietv or I can help with.

**Comment by fsouza** [comment]
Sorry @zramsay, I haven't had any progress on that. Help is very welcome!

I wonder if we could have the code in continuous integration afterwards.

**Comment by samuelkarp** [comment]
@fsouza I've started working on this and hope to have a pull request ready next week.  Is there anything specific other than just adding support that I should handle?  (For example: the endpoint defaults to `tcp://127.0.0.1:2375` on Windows but `unix:///var/run/docker.sock` elsewhere; should the Windows behavior change to default to the named pipe or stay with TCP by default?)

**Comment by fsouza** [comment]
@samuelkarp thank you very much for working on that! Regarding the default endpoint, I think we can stick to Docker's behavior here. What do you think?

**Comment by samuelkarp** [comment]
@fsouza For "[Docker on Windows](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/configure_docker_daemon)" ([Windows Containers](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview)) the default is `npipe:////./pipe/docker_engine` (the path is `//./pipe/docker_engine` and protocol is `npipe://`).  I'm not sure what the default is for "[Docker for Windows](https://docs.docker.com/docker-for-windows/)" (Linux containers inside a Linux VM).

**Comment by fsouza** [comment]
@samuelkarp oh boy. It looks like the default is a named pipe in the client: https://github.com/docker/docker/blob/master/opts/hosts_windows.go#L6. So we can go with ``npipe:////./pipe/docker_engine``.

Thanks!

**Comment by samuelkarp** [comment]
@fsouza I've opened https://github.com/fsouza/go-dockerclient/pull/579 to add support for named pipes on Windows.
