### ISSUE TITLE
go-dockerclient#ParseRepositoryTag not parsing properly images with digest

### ISSUE THREAD

**Issue by hgontijo** [fsouza/go-dockerclient#532]
Parsing repo and tag from an image (with digest):
```go
package main

import (
    "fmt"
    "github.com/fsouza/go-dockerclient"
)

func main() {
    repo, tagOrDigest := docker.ParseRepositoryTag("busybox@sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92")
    fmt.Printf("repo: %s, tagOrDigest: %s", repo, tagOrDigest)
}
```

The parsing results is:
```
image: busybox@sha256
tagOrDigest: 4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
```
instead of
```
image: busybox
tagOrDigest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
```

Is this an expected behavior for go-dockerclient#ParseRepositoryTag?

**Comment by fsouza** [comment]
Hi @hgontijo, no, this isn't the expected behavior. I'm marking this issue as a bug, but please notice that ``sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92`` is a digest, and not a tag. This image has no tag.

Thanks for opening the issue!

**Comment by hgontijo** [comment]
Thanks a lot, it worked fine.
