### ISSUE TITLE
Duplication of Memory settings and config properties

### ISSUE THREAD

**Issue by laplab** [fsouza/go-dockerclient#534]
According to Docker API 1.23 [create container](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container) has memory settings only inside HostConfig. Why they are duplicated in Config and HostConfig of [CreateContainerOptions](https://godoc.org/github.com/fsouza/go-dockerclient#CreateContainerOptions)?
Why KernelMemory property is inside Config and not inside HostConfig?
Why UsernsMode property is not inside HostConfig?

**Comment by fsouza** [comment]
Hi @laplab, thanks for raising this question. In some ancient version of Docker, Memory and some other settings were specified in Config, then it moved to HostConfig. I wanted to wait before removing these parameters from Config, until Docker provided no support for versions that still take Memory in the config. I believe this time has arrived, so I might create a tag for go-dockerclient and clean-up the Config struct at master.

Regarding KernelMemory, it was indeed missing from HostConfig, I just pushed the fix. UsernsMode is [already declared in HostConfig](https://github.com/fsouza/go-dockerclient/blob/f13dd32c18284616647ff3caeff3e509a0aef596/container.go#L625).

**Comment by fsouza** [comment]
Just to add some information, this is how Config and HostConfig looked like in Docker 1.0:

Config: https://github.com/docker/docker/blob/v1.0.1/runconfig/config.go#L11
HostConfig: https://github.com/docker/docker/blob/v1.0.1/runconfig/hostconfig.go#L22

When go-dockerclient started (circa Docker v0.3), there was no HostConfig: https://github.com/docker/docker/blob/v0.3.0/container.go#L54-L72.

**Comment by laplab** [comment]
Thank you very much for your fast answer and fix! Now it is clear for me.

**Comment by fsouza** [comment]
I'm going to close this issue. Please feel free to reopen it or open new issues whenever you find something wrong/unclear about go-dockerclient.

Thanks!
