### ISSUE TITLE
Ability to timeout requests over Unix Domain Socket

### ISSUE THREAD

**Issue by dadgar** [fsouza/go-dockerclient#535]
The client's HTTPClient is exposed which allows you to set the timeout when using TCP but since the unixClient is created lazily and not exposed, the same facility can not be used.

I have a commit to do this: https://github.com/dadgar/go-dockerclient/commit/cdd3eb9d0f02d39cde0fd35aa7c67ba8835bed1c

Let me know if you would want this as a PR

**Comment by fsouza** [comment]
Hi @dadgar, sorry for the delayed response and thanks for opening this issue. Your change looks good, please feel free to send the PR.

**Comment by fsouza** [comment]
@dadgar I'm closing this issue, thanks for contributing!
