### ISSUE TITLE
Newest client calls /version on every startContainer

### ISSUE THREAD

**Issue by timgp** [fsouza/go-dockerclient#539]
https://github.com/fsouza/go-dockerclient/commit/67c30ae246a11510ed1c3b72145e2daf76e4d664

This commit has changed behaviour in my unit tests as all calls to StartContainer now seem to make an additional HTTP request to /version under the covers.

Is this correct?  Or should version checking be done when creating a new client?

**Comment by fsouza** [comment]
@timgp the version checking is done only if it wasn't done before. When creating a new client, it's done only if you specified the API version that you want to use (using ``NewVersioned(TLS)?Client``).

The other operations that triggers a request to ``/version`` are:

- StartContainer
- BuildImage

But the request is always trigged once per-client, unless it fails. That might be the case in your unit tests?

**Comment by timgp** [comment]
Thanks, you're right, each unit test creates a new client so the additional stubbed response is required. Thanks for the quick response.
