### ISSUE TITLE
Docker 1.12 HEALTHCHECK

### ISSUE THREAD

**Issue by ybogdanov** [fsouza/go-dockerclient#551]
Hi,

Any plans to support the new container Healthcheck option? https://github.com/docker/engine-api/blob/master/types/container/config.go#L49

**Comment by ybogdanov** [comment]
Docker 1.12 has been released, any update on this? We can do a PR if you want.

**Comment by fsouza** [comment]
Hi @ybogdanov, thanks for opening this issue and sorry for taking that loooong to get back to you. I'm not aware of anyone working on this, so yes, you can send a PR :-D

Thanks for opening the issue in the first place!

**Comment by ybogdanov** [comment]
Thanks @fsouza, we will take a look. Any recommendations on the implementation?

**Comment by fsouza** [comment]
I'd just add the Healthcheck field to the Config struct and make the another struct with the required Healthcheck configuration. We could call it HealthConfig, just like that in the link you shared initially. What do you think?

**Comment by ybogdanov** [comment]
Closing in favor of https://github.com/fsouza/go-dockerclient/pull/559
