### ISSUE TITLE
Docker 1.12 support

### ISSUE THREAD

**Issue by kyhavlov** [fsouza/go-dockerclient#555]
Are there plans to update this repo to support the new API endpoints like node/service in 1.12?

**Comment by andrestc** [comment]
I think we are only missing the [plugins](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/3-6-plugins-experimental) api. Should we add experimental features to the client or wait for them to become stable?

**Comment by fsouza** [comment]
@andrestc we had experimental features in the past. We can wait until someone needs it.

**Comment by gpolaert** [comment]
Hello, I'm faced to an issue with the 1.12 (API 1.24) when I use `AttachToContainer`.
`2016/12/22 15:26:37 Unrecognized input header: 68`

When do you plan to support it :)?
Thanks, Guillaume

**Comment by gpolaert** [comment]
Sorry not sure it's related (downgrading to 1.23 didn't fix it)

**Comment by fsouza** [comment]
Hey @gpolaert, this should work with Docker 1.12 already.

Can you share a snippet of code so I can take a look?

Thanks!

**Comment by ericwoodruff** [comment]
I'm looking for docker 1.13 cpu-rt-period support.

**Comment by fsouza** [comment]
@ericwoodruff can you open an issue for Docker 1.13? Since Docker 1.12 is supported, I'm closing this issue.
