### ISSUE TITLE
VolumesFrom should be a slice not string

### ISSUE THREAD

**Issue by relvacode** [fsouza/go-dockerclient#558]
The `VolumesFrom` attribute of `container.Config` expects `[]string`, not `string`.

**Comment by sorawa** [comment]
yes,need a pr~!!

**Comment by fsouza** [comment]
You should probably use VolumesFrom in HostConfig. It used to be in Config, now it's in HostConfig. Sorry about the mess, Docker keeps changing the API.

I'll add a comment to Config.VolumesFrom to make it clear that it's no longer valid.

Sorry for the delayed response, and thanks for opening this issue!
