### ISSUE TITLE
question about the hijack method

### ISSUE THREAD

**Issue by logicminds** [fsouza/go-dockerclient#563]
I am trying to run commands on a container by writing to a "stdin stream" and then read the output by reading the "stdout stream".  But I can't get this to work.

Essentially, I do the following:
1. create container
2. Create two pipes (one for stdin, other for stdout)
3. attach to container
4. start container
5. write input on stdin
6. read output on stdout

The code snippet is here.  I know that docker creates a websocket for full duplex communication but I can't seem to leverage the go-dockerclient to get or send any data.  I must also note I am new to GO. 

https://gist.github.com/logicminds/ef38af5b6756c1fd53ac80845970336b

Any help is appreciated.

**Comment by fsouza** [comment]
Hi @logicminds, what happens when you try to do that?

Since you're building a repl and using the TTY, please make sure that you also set RawTerminal, otherwise go-dockerclient will mess with the byte stream returned by the Docker remote API.

Here's an example that works: https://gist.github.com/fsouza/43a05241ed9f943d24e5324c0f07471a

```
% go run sample.go
root@6a3b65523efc:/# ls
ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
root@6a3b65523efc:/# pwd
pwd
/
root@6a3b65523efc:/# ^-D
%
```

Thanks for opening this issue!

**Comment by JiangZhaoYang** [comment]
Hi @fsouza , I wan't to know why the TTY repeat display input commands, same as your example. How to remove these, thanks a lot.

**Comment by logicminds** [comment]
Your sample does work but I am just having a difficult time translating to my situation since I am new to go.   Basically from the snippet below I am not able to take input fed from a string `request.input` and have the container take the input to it's STDIN stream.

I am also unsure when to use the following method calls.  As it seems stdin doesn't stop reading until it the stream is closed.

c.waiter.Close()
c.waiter.Wait()
  


```go
func generate_response(client *docker.Client, c *Container, request ReplRequest) ReplResponse {
  attach_container(c, client)
  Info.Printf("Starting Container: %s", c.uuid)
  client.StartContainer(c.uuid, &docker.HostConfig{})
  go io.Copy(c.stdin_w, strings.NewReader(request.input))
  output_buf := bytes.NewBuffer(nil)
  go io.Copy(output_buf, c.stdout_r)
  //c.waiter.Close()
  //c.waiter.Wait()
  resp := ReplResponse{Uuid: c.uuid, Output: string(output_buf.Bytes())}
  // Read all data from stdin, passing the data as parts into the channel
  // for processing.

  Info.Printf("Closing stdout writer: %s", string(output_buf.Bytes()))
  //c.waiter.Wait()
  return resp
}


```

**Comment by fsouza** [comment]
@JiangZhaoYang in order to stopping the echo, you have to make your terminal a "raw" terminal. You can do it with the terminal lib:

```go
oldState, err := terminal.MakeRaw(0)
if err != nil {
        panic(err)
}
defer terminal.Restore(0, oldState)
```

Please check the updated gist: https://gist.github.com/fsouza/43a05241ed9f943d24e5324c0f07471a

And the terminal session:

```
% go run sample.go
root@c8a009e8191c:/# ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
root@c8a009e8191c:/# pwd
/
root@c8a009e8191c:/# [^-D]
root@c8a009e8191c:/# exit
```

**Comment by fsouza** [comment]
@logicminds what are you using as Stdin? Using a string reader should work fine:

```go
// ...
	waiter, err := client.AttachToContainerNonBlocking(docker.AttachToContainerOptions{
		Container:    container.ID,
		Stderr:       true,
		Stdout:       true,
		Stdin:        true,
		RawTerminal:  true,
		Stream:       true,
		ErrorStream:  stderrWriter,
		InputStream:  strings.NewReader("ls -lh\n"),
		OutputStream: stdoutWriter,
	})
	go io.Copy(os.Stdout, stdoutReader)
	go io.Copy(os.Stderr, stderrReader)
	if err != nil {
		panic(err)
	}
	waiter.Wait()
// ...
```

**Comment by logicminds** [comment]
My stdin is :  `go io.Copy(c.stdin_w, strings.NewReader(request.Input))`

While I still haven't made this work, part of my problem was that I was attaching to the container before starting the container.  
```go
        Info.Printf("Starting Container: %s", c.uuid)
	output_buf := bytes.NewBuffer(nil)
	err := client.StartContainer(c.uuid, &docker.HostConfig{})
	attach_container(c, client)
	Info.Printf("Running %s:", request.Input)
	go io.Copy(output_buf, c.stdout_r)
        go io.Copy(c.stdin_w, strings.NewReader(request.Input))
	Info.Printf("Starting Container: %s", output_buf)

```


```go
// modified the container object and updates the stdin,stdout, and stderr
func attach_container(c *Container, client *docker.Client) error {
	stdoutReader, stdoutWriter := io.Pipe()
	stdinReader, stdinWriter := io.Pipe()
	opts := docker.AttachToContainerOptions{
		Container:    c.uuid,
		RawTerminal:  true,
		InputStream:  stdinReader,
		OutputStream: stdoutWriter,
		ErrorStream:  stdoutWriter,
		Stream:       true,
		Stdin:        true,
		Stdout:       true,
		Stderr:       true,
		Logs:         true,
		//Success:      make(chan struct{}),
	}
	waiter, err := client.AttachToContainerNonBlocking(opts)
	// <-opts.Success
	// close(opts.Success)
	c.waiter = waiter
	c.stdout_r = stdoutReader
	c.stdout_w = stdoutWriter
	c.stdin_r = stdinReader
	c.stdin_w = stdinWriter
	Info.Println("Attaching to container", c.uuid)
	return err
}
```

Also I don't remember why I needed this code but I believe it has something to do with a callback and the waiter: `Success:      make(chan struct{})`

**Comment by logicminds** [comment]
If anyone is curious, I separated writing to the container and attaching to different functions and store the STDIN, STDOUT objects in a stuct for later retrieval.  Since the INPUT is coming from an http request object I cannot simply watch os.STDIN

**Comment by JiangZhaoYang** [comment]
@fsouza THX, I try your sample, it work good !

**Comment by hsyed** [comment]
```
oldState, err := terminal.MakeRaw(0)
if err != nil {
        panic(err)
}
defer terminal.Restore(0, oldState)
```

@fsouza @logicminds it would be great to have this snippet available in the godocs on the `CreateExec` or `StartExec` methods. The api has been fairly intuitive so far, but this echoing issue requires tactical googling to find a solution to.

**Comment by logicminds** [comment]
I don't think I ever got this working they way I wanted. I ended up switching to the docker provided api library and refactored my code to work with differently.  It was a lot work but I did solve my problem using the docker api and a modified approach.
