### ISSUE TITLE
Question - Modify Container at creation

### ISSUE THREAD

**Issue by johscheuer** [fsouza/go-dockerclient#564]
I want to modify the mount points at the creation time of a container. I subscribed to the `create` and with the following snippet I get the Container Config:

```go
c, err := watcher.dockerClient.InspectContainer(e.ID)
if err != nil {
	return err
}

adjustMounts(c)
```

then in the `adjustMounts` method I want to modify the mount points:

```go
func adjustMounts(c *docker.Container) error {
	for i, mount := range c.Mounts {
		mountDir, mountVolume := path.Split(mount.Source)
		mount.Source = path.Join(mountDir, fmt.Sprintf("%s/%s", test, mountVolume))
		c.Mounts[i] = mount
	}

	log.Printf("Container: %v", c)
	return nil
}
```

The printed Config shows the modified mount points but when I run `docker inspect <docker-id>` I see the old mount point and of course this results in an error: `Stale NFS file handle`.

I just wanted to ask what I'm missing or what would be the correct way to do this?

**Comment by fsouza** [comment]
Hi @johscheuer, thanks for opening this issue. This library only communicates with the Docker remote API, when you inspect the container, the library grabs the information and keeps a copy in memory. If you want  to make operations in containers, you need to find the corresponding call in the Docker remote API.

That being said, it's not possible to change the mount points of a container after it has been created, so you need to create a new container to achieve this goal. It was possible to do that in the past by restarting containers, but this is no longer supported by the Docker remote API.

**Comment by johscheuer** [comment]
Thanks @fsouza for your fast reply. So my first try was this:

```go
func (watcher *watcher) recreateContainer(c *docker.Container) error {
	// create new Container
	newContainer, err := watcher.dockerClient.CreateContainer(
		docker.CreateContainerOptions{
			Config:     c.Config,
			HostConfig: c.HostConfig,
		})

	if err != nil {
		return err
	}

 	// otherwise we are in an infinite loop
	watcher.recreatedContainer[newContainer.ID] = true

	// remove old container
	if err := watcher.dockerClient.RemoveContainer(
		docker.RemoveContainerOptions{
			ID:            c.ID,
			RemoveVolumes: false,
			Force:         true}); err != nil {
		return err
	}

	// start new container
	return watcher.dockerClient.StartContainer(newContainer.ID, newContainer.HostConfig)
}
```

theoretically everything should be fine (from my perspective) but `c.Config` is empty and this is why the creation of the new container fails (basically it doesn't fail but I get an Container without any configuration). Do you know what I'm missing or why the config is empty?

**Comment by fsouza** [comment]
@johscheuer where does this ``c *docker.Container`` parameter come from? If it is the value returned by CreateContainer, you need to call InspectContainer to get everything back, because CreateContainer returns the container only with the ID filled up. Something like:

```go
container, err := client.CreateContainer(...) // returns the container with just ID filled-up
if err != nil {
  // handle err
}
container, err = client.InspectContainer(container.ID)
if err != nil {
  // handle err
}
watcher.recreateContainer(container)
```

Sorry abut the confusion, I updated the documentation for CreateContainer to clarify that it doesn't return the complete container instance and that users should call InspectContainer to gather more information about the container.

**Comment by johscheuer** [comment]
@fsouza ah okay, thanks :) So hopefully one last question:

I get the original Container this way:

```go
func (watcher *watcher) handleEvent(e *docker.APIEvents) error {
	if !watcher.WatchedStatus[e.Status] {
		return nil
	}

	c, err := watcher.dockerClient.InspectContainer(e.ID)
	if err != nil {
		return err
	}

	if _, ok := watcher.recreatedContainer[c.ID]; ok == true {
		log.Printf("Container %s already newly created", c.ID)
		return nil
	}

	return watcher.adjustMounts(c, watcher.watchedLabels(c))
}
```

Then I adjust the mount points with the function from above and in the next step I recreate a new Container (I added some debug output):

```go
func (watcher *watcher) recreateContainer(c *docker.Container) error {
	newContainer, err := watcher.dockerClient.CreateContainer(
		docker.CreateContainerOptions{
			Config:     c.Config,
			HostConfig: c.HostConfig,
		})

	if err != nil {
		return err
	}

	newContainer, err = watcher.dockerClient.InspectContainer(newContainer.ID)
	if err != nil {
		// handle err
	}

	log.Printf("Created new Container: %v", newContainer)

	watcher.recreatedContainer[newContainer.ID] = true

	log.Printf("Remove container: %v\n", c)
	if err := watcher.dockerClient.RemoveContainer(
		docker.RemoveContainerOptions{
			ID:            c.ID,
			RemoveVolumes: false,
			Force:         true}); err != nil {
		return err
	}

	log.Printf("Starting new container: %v\n", newContainer)
	return watcher.dockerClient.StartContainer(newContainer.ID, newContainer.HostConfig)
}
```

I get the following output:

```bash
20:05:30 Created new Container: &{ ... devicemapper [{TestVolume /run/docker/quobyte/mnt/TestVolume /vol quobyte  true}] ... }
20:05:30 Remove container: &{ ... devicemapper [{TestVolume /run/docker/quobyte/mnt/root#root@TestVolume /vol quobyte  true}] ... }
```

I tried doing this but I still get the old mount point:

```go
c.Config.Mounts = c.Mounts
newContainer, err := watcher.dockerClient.CreateContainer(
	docker.CreateContainerOptions{
		Config:     c.Config,
		HostConfig: c.HostConfig,
	})
```

The code is here if you want to take a look [event-watcher](https://github.com/johscheuer/docker-volume/blob/fixed-user-mounts/event_watcher.go)
