### ISSUE TITLE
Display a deprecation error for CopyFromContainer and docker 1.12

### ISSUE THREAD

**Issue by gravis** [fsouza/go-dockerclient#568]
Hi,

We have a worker based on go-dockerclient running for 2 years now. After an upgrade to docker 1.12, the worker stopped working, and I can't figure out why :(

The simplified process is:

- Create the container
- Start the container
- Wait for container to finish
- Attach output to fetch result
- Remove container

The process is failing after step 3, with `No such container: [container_id]`.

Sounds like the new behaviour is to remove the container after execution, but it should not happen, since `AutoRemove` is defaulted to false in `HostConfig`.

The container exists until step4, we can see the same ID in the logs as the one in `No such container: [container_id]`, meaning the container is removed right after WaitContainer.

Any idea why I'm seeing this?

**Comment by gravis** [comment]
It's not removed, the problem seems to be in `CopyFromFiles`

**Comment by gravis** [comment]
Ok, this method is completely not working with docker 1.12, I must use `DownloadFromContainer` now (which is working btw).

I'm updating the title of the issue, we need to issue a visible warning about the deprecation of `CopyFromContainer`, otherwise people will fall into the same trap.

**Comment by fsouza** [comment]
@gravis thanks for reporting it! Should we check the API version and return an error? Or just document?

**Comment by gravis** [comment]
Definitely check the API version, and return an error. This would have saved me 2h of debugging, and I'm probably not the only one :)
Of course it was noted as deprecated in the code, BUT:
- you need to know exactly which function is not working well
- with just ` No such container: [container_id]`, it's almost impossible to tell
- we can't read all the source of the libs we're using, all the time (especially those related to docker, they're getting huge :))

so 100% for return an error. If you really don't want to break to API, you could wrap the `DownloadFromContainer` inside `CopyFromContainer` and print a warning, but I don't like that.
Printing is often ignored (nobody checks stdio, we all log to centralized logging servers, right?). Also, it encourages to continue using a dead function.

**Comment by fsouza** [comment]
@gravis I'd rather return the error. I'm going to do that.

We've done similar stuff with StartContainer (HostConfig is no longer supported in Docker 1.12). I'm sorry to read that it took you two hours of debugging to figure this out. Thanks for opening the issue!

**Comment by gravis** [comment]
Don't be sorry :)
At least it's fixed on my side, and pretty soon for everyone thanks to you!
I wish I could spend another extra hour to provide a nice PR :(
