### ISSUE TITLE
tcp port=0 will throw a exception

### ISSUE THREAD

**Issue by kingbug** [fsouza/go-dockerclient#576]
when port is null  or 0,will throw exceptin

**Comment by fsouza** [comment]
@kingbug on which method? InspectContainer?

**Comment by kingbug** [comment]
@fsouza  yes.InspectContainer！ This should return an error ，Otherwise it will cause the program to exit

**Comment by kingbug** [comment]
@fsouza  file:client.go  412

**Comment by fsouza** [comment]
@kingbug can you share a code snippet? The only way client.go:412 could panic is if you're using a nil client (maybe ignoring the error returned by the constructor?), like below:

```
client, _ := docker.NewClient(...) // no error check, client might be nil
client.InspectContainer(...)
```

You might be using an older version of the client as well, in this case your client.go:412 could be something else. In either case, it would be great to have a reproducer.
