### ISSUE TITLE
endpoint spec?

### ISSUE THREAD

**Issue by 5k3105** [fsouza/go-dockerclient#578]
Using Go1.7 from Win7 machine to connect to Alpine + Docker machine.

I am attempting to use the example with endpoint "unix:///var/run/docker.sock"

I am using the client to remotely connect to the docker service. The host machine has ip addr 10.200.14.169

I'm not sure what the endpoint should look like. Maybe "http://10.200.14.169:xxxx" with some port number I don't know about?

Thanks.

**Comment by fsouza** [comment]
Hi @5k3105, the default Docker port is 2376 for TLS-enabled connections and 2375 to non-tls connections. You'd need to check which port the server is listening to, if any.
