### ISSUE TITLE
Accept the service version in Client.UpdateService

### ISSUE THREAD

**Issue by omallo** [fsouza/go-dockerclient#580]
According to the [API documentation](https://goo.gl/wu3MmS), the `Client.UpdateService` function should pass a service `version` parameter to Docker which is used for optimistic locking. Without this parameter, the call always fails.

**Comment by fsouza** [comment]
Hi @omallo, thanks for reporting and sorry about the broken code in the first place.. I just pushed a fix.

**Comment by omallo** [comment]
Hi @fsouza , thanks a lot for the very rapid fix! I just gave it a try and it seems to work fine.

BTW: From the API documentation I'm not really sure whether the version should be an `int` or a `string` but I saw that you are using different types in `UpdateServiceOptions.Version`, `UpdateNodeOptions.Version`, and `Version.Index`.

**Comment by fsouza** [comment]
@omallo thanks! I'll look into Docker code to confirm the correct type.

**Comment by fsouza** [comment]
Indeed it's an integer on Docker code, I'll update ``UpdateServiceOptions.Version`` to be an int. Thanks for the catch!
