### ISSUE TITLE
undefined: http.MethodPost

### ISSUE THREAD

**Issue by mervynzhang** [fsouza/go-dockerclient#581]
Hello,

i'm trying to build https://github.com/looplab/logspout-logstash , which leverage go-dockerclient, but got following error, could you please help to fix this? 

# github.com/fsouza/go-dockerclient
../../fsouza/go-dockerclient/auth.go:167: undefined: http.MethodPost
../../fsouza/go-dockerclient/client.go:366: undefined: http.MethodGet
../../fsouza/go-dockerclient/client.go:378: undefined: http.MethodGet
../../fsouza/go-dockerclient/client.go:435: undefined: http.MethodPost
../../fsouza/go-dockerclient/client.go:489: undefined: http.MethodPost
../../fsouza/go-dockerclient/client.go:503: undefined: http.MethodPost
../../fsouza/go-dockerclient/container.go:87: undefined: http.MethodGet
../../fsouza/go-dockerclient/container.go:441: undefined: http.MethodPost
../../fsouza/go-dockerclient/container.go:469: undefined: http.MethodPost
../../fsouza/go-dockerclient/container.go:484: undefined: http.MethodGet
../../fsouza/go-dockerclient/container.go:484: too many errors

**Comment by amitripshtos** [comment]
same here :(

**Comment by fsouza** [comment]
Hm, looks like this is new in Go 1.6. I'm reverting, sorry about that.
