### ISSUE TITLE
Can't find Dockerfile as client on Windows

### ISSUE THREAD

**Issue by Trane9991** [fsouza/go-dockerclient#589]
Hello,
using client connecting to remote docker daemon.
When connecting from Linux to Docker daemon installed on CoreOS everything is ok.
When connecting from Windows to Docker daemon installed on CoreOS and trying to build docker image(on remote system) I get `API error (500): {\"message\":\"Cannot locate specified Dockerfile: Dockerfile\"}`. Pull images works ok.

```
err := client.BuildImage(docker.BuildImageOptions{
    Name: item.Name,
    // Dockerfile:     "Dockerfile",
    SuppressOutput: true,
    OutputStream:   &buf,
    RmTmpContainer: true,
    ContextDir:     filepath.Join(app.cnf.DockerfilesPath, item.Name),
})
```

where is: `app.cnf.DockerfilesPath = "images"` and `item.Name = app1`
Dockerfile is located in the: `images/app1/Dockerfile`

Building on remote docker daemon from client on Linux passes, and failing on Windows...

Any ideas why?

**Comment by fsouza** [comment]
@Trane9991 try with ``path.Join`` instead of ``filepath.Join``. This information is probably compared to the contents of the tarball sent to the remote server and tar always uses ``/``, even on Windows.

**Comment by Trane9991** [comment]
@fsouza 
hey, still no success with code:
```
app.l.Debugf("Found Dockerfile %s. Trying to build %s ...", lang.fullDockerfilePath(app.cnf.DockerfilesPath), lang.fullImageName())
contextPath := path.Join(app.cnf.DockerfilesPath, lang.Name)
app.l.Debugf("app.cnf.DockerfilesPath=%s", app.cnf.DockerfilesPath)
app.l.Debugf("lang.Name=%s", lang.Name)
app.l.Debugf("contextPath=%s", contextPath)
files, _ := ioutil.ReadDir(contextPath)
for _, f := range files {
	app.l.Debugf("Found file %s in %s", f.Name(), contextPath)
}
err := client.BuildImage(docker.BuildImageOptions{
	Name:           lang.Name,
	SuppressOutput: true,
	OutputStream:   &buf,
	RmTmpContainer: true,
	ContextDir:     contextPath,
})
if err != nil {
	app.l.Errorf("Couldn't build docker image %s with error: %s", lang.fullImageName(), err)
} else {
	app.l.Infof("Successfuly built docker image %s", lang.fullImageName())
}
```

get next output:
```
time="2016-10-01T11:37:30+03:00" level=debug msg="Found Dockerfile images\\bash\\Dockerfile. Trying to build bash:latest ..."
time="2016-10-01T11:37:30+03:00" level=debug msg="app.cnf.DockerfilesPath=images"
time="2016-10-01T11:37:30+03:00" level=debug msg="lang.Name=bash"
time="2016-10-01T11:37:30+03:00" level=debug msg="contextPath=images/bash"
time="2016-10-01T11:37:30+03:00" level=debug msg="Found file Dockerfile in images/bash"
time="2016-10-01T11:37:30+03:00" level=error msg="Couldn't build docker image bash:latest with error: API error (500): {\"message\":\"Cannot locate specified Dockerfile: Dockerfile\"}\n"
```

any ideas?

**Comment by Trane9991** [comment]
@fsouza 
Hello, I have found a problem. I created simple test application which creates Tar archives with use `createTarStream` method(https://github.com/fsouza/go-dockerclient/blob/master/tar.go#L20) and I found that problem is in the resolving relative path on Windows. 
Example:
Creating 2 tar packages from the same directory, only one time with relative path and next time with absolute path:
```
func main() {
	path1 := `images`
	path2 := `bash`
	tarStr1, err := createTarStream(filepath.Join(path1, path2), "Dockerfile")
	fmt.Println(err)
	outFile1, err := os.Create(`test.tar`)
	// handle err
	defer outFile1.Close()
	_, err = io.Copy(outFile1, tarStr1)

	// ---------------------------

	path3 := `d:\Workspace\Git\go\src\test\images`
	path4 := `bash`
	tarStr2, err := createTarStream(filepath.Join(path3, path4), "Dockerfile")
	fmt.Println(err)
	outFile2, err := os.Create(`test2.tar`)
	// handle err
	defer outFile2.Close()
	_, err = io.Copy(outFile2, tarStr2)
}
```

checking results:
![](http://img.ctrlv.in/img/16/10/01/57efb3189d631.jpg)

Conclusion:
Tar package created from directory with relative path is empty.

**Comment by Trane9991** [comment]
@fsouza 
As a workaround, adding `filepath.Abs()` to the contextDir in my code works fine. But this need be fixed in the library.

P.S. I tried to replace `validateContextDirectory`(https://github.com/fsouza/go-dockerclient/blob/master/tar.go#L67) with builder.ValidateContextDirectory() from https://github.com/docker/docker/blob/master/builder/context.go#L26 but looks like issue still persist.

**Comment by Trane9991** [comment]
@fsouza 
As a workaround adding `absContextDir, err := filepath.Abs(filepath.Join(app.cnf.DockerfilesPath, item.Name))` works fine, but the issue need to be fixed in the library.

P.S. I'm tried to replace `validateContextDirectory`(https://github.com/fsouza/go-dockerclient/blob/master/tar.go#L67) with the `builder.ValidateContextDirectory`( https://github.com/fsouza/go-dockerclient/blob/master/tar.go#L67), but looks like issue persist. Need more testing.

**Comment by willseward** [comment]
@fsouza Does this bug still exist in the library? If so, you would be willing to implement the work-around that @Trane9991 mentioned?

It would be nice to get https://github.com/dnephin/dobi working on Windows.

**Comment by jward-2ndwatch** [comment]
This is also causing a problem in Harbur Captain on Windows. I have opened a bug there (https://github.com/harbur/captain/issues/77) but it seems a fix here would be the correct solution.

**Comment by fsouza** [comment]
I apologize for leaving this bug hanging for  so long. I just pushed a tentative fix. Unfortunately I don't have a Windows host where I can reproduce the bug nor test the fix, but the CI build did succeed: https://ci.appveyor.com/project/fsouza/go-dockerclient/build/355.

@jward-2ndwatch can you give it a shot?

**Comment by jward-2ndwatch** [comment]
I will try to make some time and give it a shot soon. Thanks for getting to this.

**Comment by jward-2ndwatch** [comment]
@fsouza I rebuilt Harbur Captain with this update and it looks like it solved the issue I was having. 👍

**Comment by fsouza** [comment]
@jward-2ndwatch thank you very much for confirming!
