### ISSUE TITLE
What's the difference between the docker client package and go-dockerclient?

### ISSUE THREAD

**Issue by jbucaran** [fsouza/go-dockerclient#593]
What's the difference between the [docker client package](https://github.com/docker/docker/tree/master/client) and go-dockerclient (this project)?

Cheers.

**Comment by fsouza** [comment]
@jbucaran this project is older, from a time where Docker didn't provide a client (around May 2013).

The issues below can provide some background:

- docker/docker#224
- docker/docker#640
- tsuru/tsuru#372
- tsuru/tsuru#440

**Comment by fsouza** [comment]
Oh, I realized I haven't explained anything, just threw some links. Sorry about that. So, we wanted to use the Docker API before Docker wanted to commit to providing a stable API, so I created the client. After committing to a stable API, Docker created the official client.

**Comment by jbucaran** [comment]
@fsouza Thanks for the links! Those would've been hard to dig up myself.

What would you recommend for a new project? Go with the official client?

Thanks!
