### ISSUE TITLE
If socket is used shouldn't that  skip any http proxy? 

### ISSUE THREAD

**Issue by kohlerm** [fsouza/go-dockerclient#596]
I ran into this when trying https://github.com/matthieudelaro/nut: 
For the tool to work with your client lib I have to add /var/run/.docker.sock to the   no_proxy environment variable. 
This was also necessary for old docker versions in genear, but is not required anymore since quite some time.

**Comment by fsouza** [comment]
Hi @kohlerm, thanks for reporting! Indeed we should skip proxies when using local sockets.
