### ISSUE TITLE
Could not get images list

### ISSUE THREAD

**Issue by lwhhhh** [fsouza/go-dockerclient#598]
I used "go get github.com/fsouza/go-dockerclient" command to get the this package. 
Then  pasted example code to run fristly, but I got a blank output. 
I can sure my image list is not empty.

Is my operation wrong?

**Comment by fsouza** [comment]
Hi @lwhhhh, maybe something is failing and the example code doesn't check for errors (unfortunately). I'm going to push a fix, but can you try with the code below instead?

```go
package main

import (
	"fmt"

	"github.com/fsouza/go-dockerclient"
)

func main() {
	endpoint := "unix:///var/run/docker.sock"
	client, err := docker.NewClient(endpoint)
	if err != nil {
		panic(err)
	}
	imgs, err := client.ListImages(docker.ListImagesOptions{All: false})
	if err != nil {
		panic(err)
	}
	for _, img := range imgs {
		fmt.Println("ID: ", img.ID)
		fmt.Println("RepoTags: ", img.RepoTags)
		fmt.Println("Created: ", img.Created)
		fmt.Println("Size: ", img.Size)
		fmt.Println("VirtualSize: ", img.VirtualSize)
		fmt.Println("ParentId: ", img.ParentID)
	}
}
```

**Comment by lwhhhh** [comment]
@fsouza 

I pasted the new code and run it, then the output told me "/var/run/docker.sock" not exist.(but my docker can run well ?).So I created the file next, but now I get a permission denied when I run it.

>panic: Get http://unix.sock/images/json: dial unix /var/run/docker.sock: connect: permission denied

>goroutine 1 [running]:
>panic(0x644260, 0xc420017590)
>	/usr/local/go/src/runtime/panic.go:500 +0x1a1
>main.main()
>	/home/lwh/gitrepo/webdocker/src/main.go:16 +0x711
>exit status 2

I tried to entry "sudo su"(ubuntu), but also get another error.

**Comment by fsouza** [comment]
@lwhhhh you need to see where Docker is running and point go-dockerclient to it. Can you run ``docker run``? What's the output of ``docker info``? Do you have the DOCKER_HOST environment variable?

This file is a unix socket and should be created by the Docker daemon (if it's configured to do so).

**Comment by lwhhhh** [comment]
@fsouza 
Oh sorry, my docker environment was damage(maybe since  I entrid
 `sudo docker -d -H unix:///var/run/docker.sock  -H tcp://127.0.0.1:9090` previously)

After I rebooted  my machine, the code could run well.

Thanks for you reply.
