### ISSUE TITLE
How to save image to a tar archive, and load it back

### ISSUE THREAD

**Issue by summerQLin** [fsouza/go-dockerclient#600]
Hi,

docker has a command `docker save [OPTIONS] IMAGE [IMAGE...]`, to save an image to a tar archive.

Is this client able to do that? I notice there is no `save` function in `image.go`, but `ExportImage`, is this what `docker save` does?

Thanks

**Comment by fsouza** [comment]
Hi @summerQLin, thanks for opening this issue.

Yes, ``docker save`` does the same thing as ``ExportImage``.

**Comment by summerQLin** [comment]
Hi @fsouza,  `ExportImage` works, and I save the image to a tar.

The export code is:
```
func (backup *Backup) save(imageid string) error {
  f, err := os.Create("/"+imageid+".tar.gz")
  if err != nil {
    log.Fatal(err)
  }
  defer f.Close()
  w := bufio.NewWriter(f)
  opts := docker.ExportImageOptions{Name: imageid, OutputStream: w}
  if err := dockerClient.ExportImage(opts); err != nil {
    return err
  }
  w.Flush()
  return nil
}
```

However I failed to load the image back, here is the code
```
func (backup *Backup) load(imageid string) error {
  tar, err := os.Open("/"+imageid+".tar.gz")
  if err != nil {
    return err
  }
  opts := docker.LoadImageOptions{InputStream: tar}
  if err = dockerClient.LoadImage(opts); err != nil {
    return err
  }
  return nil
}
```
`LoadImage` didn't throw any error, but I can't see the image from `docker images` command.

Could you please help me with this case.

**Comment by summerQLin** [comment]
The docker server is swarm using API 1.23.

**Comment by summerQLin** [comment]
It works perfectly using docker cli. So something should be wrong on this go client.

**Comment by fsouza** [comment]
Hi @summerQLin, it looks like there's a bug in go-dockerclient. I believe I have a fix, but can you first test if using ExportImage**s** with a single image argument fixes the issue?

You'd need to change your code to something like:

```
func (backup *Backup) save(imageid string) error {
  f, err := os.Create("/"+imageid+".tar.gz")
  if err != nil {
    log.Fatal(err)
  }
  defer f.Close()
  w := bufio.NewWriter(f)
  opts := docker.ExportImagesOptions{Names: []string{imageid}, OutputStream: w}
  if err := dockerClient.ExportImages(opts); err != nil {
    return err
  }
  w.Flush()
  return nil
}
```

If that fixes the issue for you, I can push a fix for ExportImage very quickly. Thanks!

**Comment by summerQLin** [comment]
@fsouza, unfortunately `ExportImages` doesn't work. 

I tested function `load` to load image tar, which was exported by docker cli.  And it worked. 

I notice that two image tars, one is exported by go-dockerclient,  the other is exported by docker cli, have different size. 

So the problem is with function `ExportImages`.

**Comment by summerQLin** [comment]
@fsouza the tarball exported by go-client is broken, here is err when I use vi to view the tar:

```
gzip: /home/hos/ghe/Time-based-Image-Backup/puller/image-storage/sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

**Comment by fsouza** [comment]
@summerQLin please notice that ExportImage generates a tarball, not a compressed tarball. Here's a working example:

```
% cat export.go
```
```go
package main

import (
	"os"

	"github.com/fsouza/go-dockerclient"
)

func main() {
	f, err := os.Create("imagefile.tar")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	client, err := docker.NewClientFromEnv()
	if err != nil {
		panic(err)
	}
	opts := docker.ExportImageOptions{Name: "alpine", OutputStream: f}
	if err := client.ExportImage(opts); err != nil {
		panic(err)
	}
}
```

```
% cat load.go
```
```go
package main

import (
	"os"

	"github.com/fsouza/go-dockerclient"
)

func main() {
	f, err := os.Open("imagefile.tar")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	client, err := docker.NewClientFromEnv()
	if err != nil {
		panic(err)
	}
	opts := docker.LoadImageOptions{InputStream: f}
	if err := client.LoadImage(opts); err != nil {
		panic(err)
	}
}
```

Shell session:

```
% go run export.go
% ls -l imagefile.tar
-rw-r--r--  1 fsouza  staff  5059072 Nov  8 09:19 imagefile.tar
% mkdir /tmp/image
% tar -C /tmp/image -xvf imagefile.tar
x 8a11799f505a4704c80d222c1b02d6635ecd8c87b859727593e3aa61c5c6bf45/
x 8a11799f505a4704c80d222c1b02d6635ecd8c87b859727593e3aa61c5c6bf45/VERSION
x 8a11799f505a4704c80d222c1b02d6635ecd8c87b859727593e3aa61c5c6bf45/json
x 8a11799f505a4704c80d222c1b02d6635ecd8c87b859727593e3aa61c5c6bf45/layer.tar
x baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3.json
x manifest.json
x repositories
% docker rmi alpine
Untagged: alpine:latest
Deleted: sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3
% docker inspect alpine
[]
Error: No such image, container or task: alpine
% go run load.go
% docker inspect alpine
[
    {
        "Id": "sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3",
        "RepoTags": [
            "alpine:latest"
        ],
...
```

Three question:

1. Can you share your code that is loading the image?
1. Can you try to extract the output file without the option to decompress?
1. Can you try the code without ``bufio.Writer``?

**Comment by summerQLin** [comment]
@fsouza My loading image code is the same as yours. I tested both `ExportImage` and `ExportImages`, and they gave me the same result. And I removed bufio.Writer. 

The docker service is swarm API 1.23
Go client, I imported `github.com/fsouza/go-dockerclient`, that should the latest master branch code.

To extract the tar `busybox-go.tar` exported by go client:
```
$ ls -l busybox-go.tar
-rw-r--r-- 1 root root 1300992 Nov  8 15:46 busybox-go.tar
$ sudo tar -C ./image-go -xvf busybox-go.tar
2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749.json
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/VERSION
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/json
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/layer.tar
manifest.json
```
To extract the tar  `busybox.tar`  exported by docker cli, docker client API 1.23, version 1.11.2
```
$ ls -l busybox.tar
-rw-r--r-- 1 root root 1302016 Nov  8 15:55 busybox.tar
$ sudo tar -C ./image -xvf busybox.tar
2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749.json
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/VERSION
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/json
374004614a75c2c4afd41a3050b5217e282155eb1eb7b4ce8f22aa9f4b17ee57/layer.tar
manifest.json
repositories
```
Please notice two tarball sizes are different, and go client exported tar is lack of a file `repository`.

Load `busybox-go.tar` by go client load function, no image showed up. 
Load `busybox.tar` by docker cli, succeeded.

**Comment by fsouza** [comment]
Hi @summerQLin, thanks for detailing the versions you used. I'll try with Docker 1.11 and see if I observe any change in the behavior. Does it happen to any image or just this one? If it's just this one, can you share it with me somehow?

Thank you again!

**Comment by summerQLin** [comment]
Hi @fsouza I finally know the reason it didn't work. I export image by image id, while docker API doc says:
` If name is an image ID, similarly only that image (and its parents) are returned, but with the exclusion of the ‘repositories’ file in the tarball, as there were no image names referenced.`

And I tested using image name, and it worked.

Thank you very much for your help. I will close this issue.

**Comment by fsouza** [comment]
Oh, nice catch. I didn't know that either. Thanks for dedicating your time to investigate this!
