### ISSUE TITLE
Question: build container from an io.Writer

### ISSUE THREAD

**Issue by cescoferraro** [fsouza/go-dockerclient#603]
Is there a way to pass a io.writer to docker.BuildImageOptions so one would not need to create a temp file, build an image then delete it.

It would be very helpful for https://github.com/dnephin/dobi/pull/55

**Comment by fsouza** [comment]
Hey @cescoferraro, thanks for opening the issue!

You need an io.Reader in the InputStream. Checkout the example in the documentation: https://godoc.org/github.com/fsouza/go-dockerclient#example-Client-BuildImage.

**Comment by cescoferraro** [comment]
@fsouza when using an InputStream I cant use a ContextDir.
Then how can I make the current directory available to COPY or ADD?

```
// This
tr.Write([]byte("COPY . /test\n"))
tr.Write([]byte("RUN ls /test\n"))
// Prints
Step 3 : RUN ls /test
 ---> Running in b4a6d55eacbb
Dockerfile
```

**Comment by cescoferraro** [comment]
Got it! I was using multiple tar.Writer on the same buffer. I had to write multiple tar.Header to the same writer on the same buffer
