### ISSUE TITLE
1.6 Incompatibility due to cleanhttp dep

### ISSUE THREAD

**Issue by tahmmee** [fsouza/go-dockerclient#623]
3 days ago a change went into go-cleanhttp project which is breaking attempts to build docker client on Go 1.6:
[https://github.com/hashicorp/go-cleanhttp/commit/a45970658e51fea2c41445ff0f7e07106d007617
](https://github.com/hashicorp/go-cleanhttp/commit/a45970658e51fea2c41445ff0f7e07106d007617
)

The maintainer doesn't seem uninterested in supporting 1.6 and looks like some people have already started forking the repo and reverting the change.   I've left a comment there in the change requesting backward compatibility of some sort.

My opinion here is, that dropping Go 1.6 support of the entire docker client project for this minor change is excessive.  However, I'd like to know if there are any plans here to keep 1.6 support or to force upgrades at this point.

**Comment by fsouza** [comment]
Hey @tahmmee, thanks for raising this issue. Usually, I'd stop supporting Go 1.6 as well, but if the change to keep go-dockerclient is small (as in this case), I'd be happy to accept it. Unfortunately, I won't be able to work on that today, but I can try to put up some fix in two or three days.

I'm also happy to review any PRs related to that. Thank you again!

**Comment by fsouza** [comment]
@tahmmee since this is causing a bunch of issue for other people, I'm going to merge #621 and drop support for Go 1.6 for _now_, and then we can try to figure the best strategy to add back support for Go 1.6.

**Comment by tahmmee** [comment]
Ok, thanks for update - I don't plan on putting together a PR here since the code *works* but it's more of a decision of go version supportability and given feedback here and downstream projects I'm moving to 1.7.

**Comment by fsouza** [comment]
@tahmmee cool, makes sense! I'm going to close this issue then.

Thank you for opening it! :)
