### ISSUE TITLE
Credential Store/Helpers

### ISSUE THREAD

**Issue by bantonj** [fsouza/go-dockerclient#627]
Are there any plans to add support for [Credential Store/Helpers](https://github.com/docker/docker-credential-helpers)? It's especially useful for Amazon ECR which does not support username and password credentials that last longer than 12 hours.

**Comment by fsouza** [comment]
@bantonj this is not part of the Docker API, you can import the code for managing the credentials locally and use it. For example, with osxkeychain: https://godoc.org/github.com/docker/docker-credential-helpers/osxkeychain.

**Comment by bantonj** [comment]
From what I can tell the credential-helper stuff needs to be implemented client side. Is this something that you feel is outside the scope of your project? If not I'll see what I can do about putting together a PR.

Thanks for the help!

**Comment by trastle** [comment]
I know this is quite an old thread but is there any intention of using the credentials store? The use of this is now ubiquitous on OSX so the existing credential loading mechanism is less and less useful.
