### ISSUE TITLE
Add Toml tags to the json and yaml tags.

### ISSUE THREAD

**Issue by VoR0220** [fsouza/go-dockerclient#628]
I'd be happy to send up the PR for this.

**Comment by fsouza** [comment]
@VoR0220 can you share your use case for the toml tags?

**Comment by VoR0220** [comment]
We use toml files to configure docker services/containers...we currently use our own definitions as an endaround that eventually get turned into go-dockerclient's types....this is quite a bastardized process...I'm contemplating using your native types and creating a configuration from those. The option would be nice to have on the table and it doesn't really affect anything to have them on there is my view.
