### ISSUE TITLE
ExportImage tarball doesn't contain manifest.json

### ISSUE THREAD

**Issue by jgsqware** [fsouza/go-dockerclient#630]
Hello,

i'm working with docker `docker 1.13.1`
when I try to export some image (for example *nginx:1.11.5*) with 

```
client.ExportImage(dockerclient.ExportImageOptions{Name: imageName, OutputStream: w})
```

the tarball doesn't contain the `manifest.json` file.

with `docker save nginx:1.11.5 > output.tar` the `manifest.json` is present.

Have you an idea?

**Comment by fsouza** [comment]
@jgsqware can you test with ExportImages instead (https://godoc.org/github.com/fsouza/go-dockerclient#Client.ExportImages)? I have a theory, but I'm not entirely sure.

Also, what is the content of "imageName"?

**Comment by jgsqware** [comment]
Unfortunately, it's not working. I've tried with 
  - `client.ExportImages(dockerclient.ExportImagesOptions{Names: []string{"nginx:1.11.5"}, OutputStream: w})`
  - `client.ExportImages(dockerclient.ExportImagesOptions{Names: []string{"nginx"}, OutputStream: w})`

Same result, no manifest.json file in the tarball

**Comment by jgsqware** [comment]
Could it be due to the manifest version? 

for example it works for `registry:2.1.1` and not for `nginx:1.11.5`

just a guess

**Comment by jgsqware** [comment]
I have the same behavior with the docker client itself 
https://github.com/docker/docker/blob/master/client/image_save.go

**Comment by jgsqware** [comment]
currently, I achieve the save with 
```
var stderr bytes.Buffer
	save := exec.Command("docker", "save", imageName)
	save.Stderr = &stderr
	save.Stdout = fo
	if err := save.Run(); err != nil {
		return nil, errors.New(stderr.String())
	}
```

but i would prefer to use the API, I will open an issue there

**Comment by jgsqware** [comment]
Ok, after investigation, I was creating the writer with `w := bufio.NewWriter(fo)` and then save the images `client.ExportImage(dockerclient.ExportImageOptions{Name: imageName, OutputStream: w})`

but I forgot to flush the `w` writer after the call. 
If I add `w.Flush()` after the `client.ExportImage`, it's working

I will close this issue

**Comment by fsouza** [comment]
@jgsqware oh, i'm glad you figure it out! Thank you for reporting and closing the issue! :)
