### ISSUE TITLE
Question: how do I create a mount a volume

### ISSUE THREAD

**Issue by logicminds** [fsouza/go-dockerclient#633]
It is a little unclear how I start a container with a volume attached.

https://github.com/fsouza/go-dockerclient/blob/master/container.go#L307

Which struct do I use?  Also how do I mount ro?

Do I need to use this?  https://github.com/docker/docker/blob/master/api/types/volume.go

**Comment by logicminds** [comment]
Is this what I need?

```
volumes := map[string]docker.Mount{
		Name:        "app_config",
		Source:      "/config",
		Destination: "/config",
		Driver:      "bind",
		Mode:        "ro",
		RW:          false
	}
```

**Comment by logicminds** [comment]
@fsouza any ideas?

**Comment by jensskott** [comment]
@logicminds im trying this one now.

`dockerHostConfig := docker.HostConfig{
		Binds: []string{"/var/run/docker.sock", "/var/run/docker.sock"},
	}

	dockerConfig := docker.Config{
		Image:      "docker/ucp:2.1.0",
		Entrypoint: []string{"backup", "--passphrase", "secret", ">", "/tmp/backup.tar"},
	}

	params := &docker.CreateContainerOptions{
		Name:       "ucp",
		Config:     &dockerConfig,
		HostConfig: &dockerHostConfig,
	}`

**Comment by fsouza** [comment]
@logicminds sorry, I missed this one somehow. You should use volumes on HostConfig.

I didn't want to remove Volumes from Config for compatibility issues, so maybe we could do some "aliasing" inside CreateContainer to make sure both work. What do you think?

**Comment by logicminds** [comment]
I ended up using the following:

```go
binds := []string{
		fmt.Sprintf("%s:/config:ro", source_config),
	}

hostconfig := container.HostConfig{
		VolumeDriver:    "bind",
		PublishAllPorts: true,
		AutoRemove:      true,
		Binds:          binds,
	}

```

**Comment by logicminds** [comment]
Volumes seem more like a predefined bind that one can reuse according to docker api docs. It is kinda confusing.  Binds are simple once you figure out that is the same thing you specify when using `docker run` command.

Additionally, I started using the official docker api client instead of this one as my needs changed.
