### ISSUE TITLE
Docker plugins api support question

### ISSUE THREAD

**Issue by prateekgogia** [fsouza/go-dockerclient#644]
I checked the code and couldn't find support for plugin apis present in Docker, I am specifically looking for this- 
https://docs.docker.com/engine/api/v1.25/#tag/Plugin

Can someone please let me know if the support is added to this package ?

**Comment by fsouza** [comment]
@prateekgogia hey, thanks for opening this issue and sorry for the delayed response. I'm not aware of anyone working on the plugin integration, but I'd be happy to review changes related to that. I can also work on that too, but not this week :(

**Comment by fsouza** [comment]
Done via #713.
