### ISSUE TITLE
LoadImage does not return an image id after importing

### ISSUE THREAD

**Issue by ubuntolog** [fsouza/go-dockerclient#645]
LoadImage (https://github.com/fsouza/go-dockerclient/blob/master/image.go#L343) does not return an image id after importing. At least I cannot find any nice way to retrieve it. Unlike ImportImage, it does not have any OutputStream where I could put my bytes.Buffer or something: there are only InputStream and Context fields available in LoadImageOptions.

**Comment by fsouza** [comment]
Hey @ubuntolog, thanks for opening this issue. Currently, the Docker API doesn't return the image that has been loaded, which means that you have to know the tag of the image and inspect it to get its ID.

You can also parse the Docker output and then inspect the image by its tag/name. I know it's weird, but it looks like this feature wasn't well designed for integration on the Docker API side.

**Comment by ubuntolog** [comment]
Thank you for the answer. I ended up getting this information from manifest.json from the tar archive with the image.

**Comment by fsouza** [comment]
@ubuntolog thanks for coming back here, I'm glad you figure it out. Apologies for not being able to help you out on time.
