### ISSUE TITLE
Panic on Windows Server 2016

### ISSUE THREAD

**Issue by schmichael** [fsouza/go-dockerclient#648]
The [Nomad](https://github.com/hashicorp/nomad) project uses go-dockerclient for all interactions with the Docker daemon. Once we started distributing Nomad with Go 1.8 we started to run into panics when using Docker on Windows:

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x40e892]

goroutine 185 [running]:
runtime.throw(0x1283a40, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x9c fp=0xc04213fe18 sp=0xc04213fdf8
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:155 +0x18b fp=0xc04213fe48 sp=0xc04213fe18
runtime.unlock(0xc042303092)
        /usr/local/go/src/runtime/lock_sema.go:107 +0x72 fp=0xc04213fe70 sp=0xc04213fe48
runtime.chansend(0x1039460, 0xc04230303a, 0xc04213ffb0, 0xc04213ff01, 0xabc44a, 0xc04213ff9c)
        /usr/local/go/src/runtime/chan.go:179 +0x8af fp=0xc04213ff20 sp=0xc04213fe70
runtime.chansend1(0x1039460, 0xc04230303a, 0xc04213ffb0)
        /usr/local/go/src/runtime/chan.go:113 +0x4d fp=0xc04213ff60 sp=0xc04213ff20
github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x384)
        /home/schmichael/go/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/file.go:131 +0xea fp=0xc04213ffd8 sp=0xc04213ff60
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc04213ffe0 sp=0xc04213ffd8
created by github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio.initIo
        /home/schmichael/go/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/file.go:55 +0x87
```

While dockerclient isn't listed in this stack trace it is the only code that uses `go-winio` in Nomad, and the panic occurs most often (it's racy) when pulling and removing Docker images.

I know this isn't technically a bug in `go-dockerclient`, but the bug effectively breaks this library on Windows for me.

- *Is anyone else having this issue?*
- *Is anyone using this library on Windows without panics?*
- *Is there a possible workaround? Possibly a way of interacting with Docker that doesn't require `winio.DialPipe`?*

## Related Issues

- Main Nomad issue: hashicorp/nomad#2343
- Potential upstream issue: Microsoft/go-winio#41

**Comment by fsouza** [comment]
Seems like we need Microsoft/go-winio#48 merged. I can see some activity there. If they don't merge today, I can change go-dockerclient so it uses a temporary fork of go-winio.

Thanks for reporting this!

**Comment by fsouza** [comment]
@schmichael Microsoft/go-winio#48 has been merged, can you give it a try?

**Comment by schmichael** [comment]
@fsouza It introduced cgo so it took me a while to work out the right cross compilation command to get it built. However, I was able to build Nomad with an updated go-winio, run it on Windows 2016, and have it attempt to run a Docker job without panics!

I'm now getting a Docker error I haven't even begun debugging:

```
API error
 (404): {"message":"container 17fea8cc5b23693e0acb572d995ddb75b32dae8b67762b6c590fe0eead343743 encountered an error during CreateContainer: failure in a Windows system c
all: Element not found. (0x490) extra info: {...the container spec...}
```

This can be reproduced by running the following on Windows with Docker 17.03.1-ee-3:

```
docker run redis:3.0-nanoserver
```

So it seems entirely unrelated to `go-dockerclient`; I'm closing this issue!

**Comment by fsouza** [comment]
@schmichael thanks for confirming! Let me know if I can help debugging this other issue :)

**Comment by schmichael** [comment]
@fsouza Other Nomad users are reporting it's working fine for them, so there's probably just a bug in my Windows and/or Docker version.

One thing worth noting is that Microsoft/go-winio#48 requires cgo on Windows now. I think the only effect is a minor annoyance for people like me who cross-compile.

I just wanted to let you know as go-dockerclient didn't require cgo on any platform (YAY) prior to this change in a dependency.

**Comment by darrenstahlmsft** [comment]
I didn't realize we (go-winio) didn't already require cgo. I might be able to implement the fix without cgo. Let me take a look.

As an aside, the above error looks like a platform issue with the containers feature. CC me on an issue against Docker and we can narrow it down. Or just try running [CleanupContainerHostNetworking.ps1](https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking), as it might fix things (Element not found is a common error when a network endpoint is in a bad state)

**Comment by schmichael** [comment]
@darrenstahlmsft Thanks for the info! Seems allocating and free'ing a security descriptor is the only time cgo is used: https://github.com/Microsoft/go-winio/pull/48/files#diff-f2948a032122ad84d0002dc69cd75b76R240 I was surprised it wasn't already being used as well!

If that script doesn't fix Docker for me I'll open an issue over on Docker. Thanks again!
