### ISSUE TITLE
Support API version >=1.25 for Docker on Windows support

### ISSUE THREAD

**Issue by schmichael** [fsouza/go-dockerclient#649]
Docker on Windows adds some complexity over previous Docker releases as it supports two modes of operation: Linux or Windows containers. Images are OS specific. In order to determine if an image will run, two new pieces of metadata are needed:

* `Image.Os` (from `GET /images/(name)/json` has been around since at least API version 1.23 but is [missing from the struct](https://godoc.org/github.com/fsouza/go-dockerclient#Image)
* `DockerInfo.Isolation` was added to `GET /info` in API version 1.25 - [struct](https://godoc.org/github.com/fsouza/go-dockerclient#DockerInfo)
  * I don't see it in the docs, but `hyperv` seems to mean Windows mode, and `""` (a blank string) means Linux mode. (This is a bit confusing since [Microsoft's documentation lists HyperV and Windows Server Containers as 2 different modes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/) which appear to be distinct from Docker's 2 modes.)

As [we need these API changes for Nomad](https://github.com/hashicorp/nomad/issues/2633) (and maybe more I haven't discovered yet) I'll try to submit a PR, but we don't have this particular issue prioritized yet.

**Comment by fsouza** [comment]
@schmichael I can take a look at this before the weekend, but let me know if you start working on it before :)

**Comment by schmichael** [comment]
Thanks! I'll make sure to comment here before starting work, but I doubt it'd be this week anyway.

**Comment by fsouza** [comment]
@schmichael I just pushed the change! :)

**Comment by schmichael** [comment]
Looks great! Thanks!
