### ISSUE TITLE
How to apply "RUN" directives in container changes (Commit API)?

### ISSUE THREAD

**Issue by justinfx** [fsouza/go-dockerclient#651]
I've asked this question in general, related to the Docker API:
https://stackoverflow.com/questions/43926803/docker-api-equivalent-to-dockerfile-run-directive-when-configuring-container

But I am thinking it may be specific to this docker client library...

How does one go about adding "RUN" directives to a container? I am seeing this in the general [Docker API](https://docs.docker.com/engine/api/v1.23/):

```
CREATE A NEW IMAGE FROM A CONTAINER’S CHANGES

POST /commit
Create a new image from a container’s changes

Query parameters:

container – source container
repo – repository
tag – tag
comment – commit message
author – author (e.g., “John Hannibal Smith <hannibal@a-team.com>”)
pause – 1/True/true or 0/False/false, whether to pause the container before committing
changes – Dockerfile instructions to apply while committing
```

And in [another Docker client library](https://github.com/moby/moby/blob/master/api/types/client.go#L46), I see this available:

```
// ContainerCommitOptions holds parameters to commit changes into a container.
type ContainerCommitOptions struct {
    Reference string
    Comment   string
    Author    string
    Changes   []string
    Pause     bool
    Config    *container.Config
}
```

But this library exposes:

```
// CommitContainerOptions aggregates parameters to the CommitContainer method.
type CommitContainerOptions struct {
    Container  string
    Repository string `qs:"repo"`
    Tag        string
    Message    string `qs:"comment"`
    Author     string
    Run        *Config `qs:"-"`
    Context    context.Context
}
```

So if using the commit API is the way to add Dockerfile changes, and this library does not expose the "changes" field on the commit, how is it accomplished?

Thanks!

**Comment by justinfx** [comment]
Nevermind. I have confused my terminology. I should have been looking at building an image:
https://godoc.org/github.com/fsouza/go-dockerclient#Client.BuildImage

Sorry for the noise.

**Comment by fsouza** [comment]
Hi @justinfx, thanks for reporting this! Regardless of build vs commit, go-dockerclient was missing the changes parameter that can be used to set some configuration in the resulting Docker image (such as labels or the entrypoint).

I just pushed the change that adds the option ``Changes`` to ``CommitContainerOptions``.

**Comment by justinfx** [comment]
I'm glad my issue uncovered this and wasn't purely noise!
