### ISSUE TITLE
Replace "golang.org/x/net/context" with standard library "context"

### ISSUE THREAD

**Issue by richardpen** [fsouza/go-dockerclient#658]
Go 1.7 has moved the `golang.org/x/net/context` to standard library, and we want to get rid of the `golang.org/x/net/context` by using the standard `context`, but go-docker-client has a dependency on `golang.org/x/net/context` which is blocking us from doing so. I was wondering can go-docker-client upgrade to use `context` instead of the one under `x/net`, is there any concerns to do so?

**Comment by yyf1986** [comment]
I have the same problem

**Comment by fsouza** [comment]
For backwards compatibility reasons, we can't address this issue yet. Starting with Go 1.9, ``golang.org/x/net/context.Context`` is just an alias to ``context.Context``.

We can revisit this issue once Go 1.10 is released (following the Go release policy of supporting only the last two releases).

**Comment by fsouza** [comment]
This is done now.
