### ISSUE TITLE
How to get exec status from 'func (c *Client) StartExec(id string, opts StartExecOptions) error'

### ISSUE THREAD

**Issue by rshinn** [fsouza/go-dockerclient#659]
Refering to: 'https://github.com/fsouza/go-dockerclient/issues/287'

Is 'StartExecOptions' field: 'Success:' intended for use by the caller to receive the exec status of the remote command? My caller needs to know the exec status of the remote command in order to know whether or not to stop the build. But, try as I might, I can find no way for it to return the status.

Thanks much.

**Comment by sosedoff** [comment]
@rshinn you can do that with:

```go
info, err := dockerClient.InspectExec(exec.ID)
if err == nil {
  log.Println("Command exited with", info.ExitCode)
}
```

**Comment by rshinn** [comment]
Oh, awesome! That works. Thank you.

One more question. I need to run it in non-interactive mode. I noticed that if I do not specify 'InputStream', it will not hang waiting for input. However, it seems it returns before the command is run and hense returns a status of '0' even when I know the command should fail (i.e. if I run it interactively, I'll get back an exit value of '1' as expected). Also, while I DO see program output to stdout (I specified 'OutputStream: os.Stdout') when I have 'InputStream' specified, if I do NOT specify 'InputStream', I don't see the output. Hense my conslusion that, in non-interactive mode, it is returning before allowing the command to execute.

**Comment by rshinn** [comment]
One idea I did have was to pass a channel to 'InputStream' and send in an item just before the call to StartExec. I'm wondering if that might be the 'right' way to, effectivley, make it non-interactive.

**Comment by sosedoff** [comment]
Can you post an example code so i can better understand what you're trying to do ?

**Comment by rshinn** [comment]
So, this function creates and starts a container with supplied env vars, and then, creates and starts an ExecID. We have a library that, given a yml like specification, will build and deploy docker containers. The idea is to (after building the image), create a local container and run unit tests in the container before deploying. So, we call this function to do that and, if the tests fail, the build should stop. So, but, it's running from within a jenkins build job and so has to run non-interactivley.

```go
func Run(imageName string, cmd string, env []string, client *docker.Client) error {

    Logf("Creating container for image: %s", imageName)
    //Try to create a container from the imageID
    config := docker.Config{
        Image: imageName,
        //Env:   []string{"TEST=true"},
        Env: env, // TODO - verify, by starting the container and then exec 'env' to see that multiple vars can be set
        // Cmd:          []string{"/bin/sh"},
        OpenStdin:    true,
        StdinOnce:    true,
        AttachStdin:  true,
        AttachStdout: true,
        AttachStderr: true,
        Tty:          true,
    }

    opts2 := docker.CreateContainerOptions{Config: &config}
    container, err := client.CreateContainer(opts2)
    if err != nil {
        Logf(err.Error())
        return err
    } else {
        defer func() {
            err = client.RemoveContainer(docker.RemoveContainerOptions{ID: container.ID})
            if err != nil {
                Logf(err.Error())
                return
            }
            Logf("Removed container with ID: %s", container.ID)
        }()
    }
    Logf("Created container with ID: %s", container.ID)

    // So, you can't start the container until you have TEST=true set
    // So, that probably means we have to pass additional toml values
    err = client.StartContainer(container.ID, nil)
    if err != nil {
        Logf("XXXX 1: %s", err.Error())
        return err
    } else {
        // And once it is done with all the commands, remove the container.
        Logf("start defered func to stop container")
        defer func() {
            Logf("Running defered func to stop container")
            err = client.StopContainer(container.ID, 0)
            if err != nil {
                Logf(err.Error())
                return
            }
            Logf("Stopped container with ID: %s", container.ID)
        }()
    }
    Logf("Started container with ID: %s", container.ID)

    var dExec *docker.Exec
    cmdSlice := []string{"bash", "-c", cmd}
    de := docker.CreateExecOptions{
        AttachStderr: true,
        AttachStdin:  true,
        AttachStdout: true,
        Tty:          true,
        Cmd:          cmdSlice,
        Container:    container.ID,
    }
    Logf("CreateExec")
    if dExec, err = client.CreateExec(de); err != nil {
        Logf("CreateExec Error: %s", err)
        return err
    }
    Logf("Created Exec")
    execId := dExec.ID
    opts := docker.StartExecOptions{
        OutputStream: os.Stdout,
        ErrorStream:  os.Stderr,
        InputStream:  os.Stdin,
        RawTerminal:  true,
    }

    Logf("StartExec")
    if err = client.StartExec(execId, opts); err != nil {
        Logf("StartExec Error: %s", err.Error())
        return err
    }
    Logf("DONE")

    info, err := client.InspectExec(execId)
    if err == nil {
        Logf("Command exited with %d", info.ExitCode)
    }

    Logf("Got result")

    return nil
}
```

**Comment by rshinn** [comment]
Specifying 'InputStream' in 'docker.StartExecOptions' causes 'StartExec()' to block waiting for a carriage return before completing. Leaving 'InputStream' unspecified allows 'StartExec()' to run to completion and return but, seemingly, does not allow enough time for (or simply does not execute) the command to be executed before returning and so always results in InspectExec() returning '0' even in the case where it should have returned '1' due to a failed test.

**Comment by sosedoff** [comment]
If you don't plan on any stdin, just remove `AttachStderr` and `InputStream` when you create and start exec. That should fix your problem.

**Comment by sosedoff** [comment]
Side note, when you want to stop and delete container, you can use a single command `RemoveContainer` with `Force` flag on.

**Comment by rshinn** [comment]
Awesome! Thanks so much.

**Comment by FengyunPan2** [comment]
How to get exec result from “StartExec(id string, opts StartExecOptions)”？
I need the result of 'dockerclient.StartExec()'.
