### ISSUE TITLE
An error on distribution.go

### ISSUE THREAD

**Issue by ridhoperdana** [fsouza/go-dockerclient#679]
Here i found an error like this : 

`github.com/fsouza/go-dockerclient/distribution.go:14:53: undefined: registry.DistributionInspect`

When i check on the docker/api/types/registry there is no function named DistributionInspect

I am using docker version v17.05.0-ce-rc3 (latest)

Thank you

**Comment by fsouza** [comment]
Hey @ridhoperdana, thanks for reporting this. Please take a look at #678. Unfortunately, tags in the ``moby/moby`` repo no longer represent Docker releases and you shouldn't rely on them :(

**Comment by ridhoperdana** [comment]
Oh great, thank you for the information. I’ll close the issue then.
