### ISSUE TITLE
How to set timezone of the container ? 

### ISSUE THREAD

**Issue by widon1104** [fsouza/go-dockerclient#682]
I want set the container timezone the same as the host
How can I do it? pass some args to CreateContainer ?
there is some doc about go-dockerclient ?

**Comment by fsouza** [comment]
Hey @widon1104, this is not specific to go-dockerclient, but to Docker itself. That being said, I believe you can mount the host ``/etc/localtime`` in the container. I haven't tested though.

**Comment by widon1104** [comment]
HostConfig: &docker.HostConfig{
		Binds: []string{"/etc/localtime:/etc/localtime:ro"},
},
this code works

**Comment by pznamensky** [comment]
In my opinion mount /etc/localtime from a host is just workaround and setting timezone from args is more universal and right way.
+1 for add ability to set tz without binds.

**Comment by fsouza** [comment]
@pznamensky this is not something go-dockerclient can do, unless Docker offers a way of doing it through its API.
