### ISSUE TITLE
Add golang/dep support

### ISSUE THREAD

**Issue by darkowlzz** [fsouza/go-dockerclient#683]
Hi, can we add support for [golang/dep](https://github.com/golang/dep)?

Recently, we got an issue https://github.com/golang/dep/issues/1274, where a project that depended on go-dockerclient tried using dep to manage the dependencies and dep installed docker version `1.13.1`, which doesn't work with the latest go-dockerclient. This happened because dep found that version as the most recent, valid semver version of docker. The new releases of docker are of the form `v17.05.0-ce` which isn't a valid semver but a tag.

I can create a PR if we agree to add dep support 🙂

Thanks!

**Comment by fsouza** [comment]
Hey @darkowlzz, thanks for reporting that. If I remember correctly, there isn't a clearly defined flow for using deps with libraries yet. How would that work?

**Comment by darkowlzz** [comment]
Thanks!
For go-dockerclient, I would suggest committing just the manifest file (Gopkg.toml) and no need of the lock file and vendor directory. And the manifest can have open constraints of flexible version or branch or even tags. With that, the users of the library can just run (provided their code imports the lib)
```
$ dep ensure
```
or 
```
$ dep ensure -add github.com/fsouza/go-dockerclient
```
and all of go-dockerclient's dependencies would be downloaded abiding by the set constraints.

If you would like to continue with the current model, no any versioned releases of the library, constraining all the dependencies to their default branch (`master` mostly), would be enough.

But if you would like to move to a regular library release model, with support for maybe semver releases, then a little restrictive constraints would be better, some semver version or branch, if your dependencies support. This would ensure reliable rebuilds.

Hope that answered all your concerns. We can discuss more and maybe get this documented for others as well.

**Comment by fsouza** [comment]
@darkowlzz but would dep respect Gopkg.toml as specified inside libraries? Nice, I didn't know that!

**Comment by fsouza** [comment]
@darkowlzz oh, I forgot to answer your initial question. This sounds good to me now. Do you want to send a PR?

**Comment by darkowlzz** [comment]
@fsouza yes, dep would respect Gopkg.toml. If it doesn't, then that would be a bug that needs to be fixed :)

Alright, so I'll create a PR adding a Gopkg.toml with some project constraints.

Thanks a lot!
