### ISSUE TITLE
Plans for a release soon?

### ISSUE THREAD

**Issue by mavogel** [fsouza/go-dockerclient#685]
@fsouza is there any plan for a release/tag? 

I'd like to upgrade the `terraform-provider-docker` and your last and only release with hash `1d4f4ae73768d3ca16a6fb964694f58dc5eba601` is used. See [vendor.json](https://github.com/terraform-providers/terraform-provider-docker/blob/master/vendor/vendor.json#L238) for details. It would be nice to have a tag before I upgrade the docker provisioner 😃

**Comment by fsouza** [comment]
Just tagged 1.0 😁

**Comment by mavogel** [comment]
Gracias señor 🙏

**Comment by fsouza** [comment]
Nice catch, the README is outdated. It supports latest Docker API (1.33). I'll remove that note from the README because it's always gonna be outdated.
