### ISSUE TITLE
Remove volume throws only on 404 and 409 from docker engine

### ISSUE THREAD

**Issue by piyush-nimbalkar** [fsouza/go-dockerclient#691]
The current implementation for remove volume seems to be returning an error, only if there is a StatusNotFound (404) or StatusConflict (409).
Is there is a specific reason why it is done so? Should we not throw all the errors coming from docker engine? For instance, I am getting a InternalServerError when the volume is mounted. But RemoveVolume does not propogate the error.

**Comment by fsouza** [comment]
@piyush-nimbalkar you're right, thanks for reporting!
