### ISSUE TITLE
Is AuthConfiguration required for PullImage?

### ISSUE THREAD

**Issue by blaines** [fsouza/go-dockerclient#708]
https://github.com/fsouza/go-dockerclient/blob/master/image.go#L309

Is AuthConfiguration really required in order to pull an image? Should this be optional?

**Comment by fsouza** [comment]
Hey @blaines, yes it should, but unfortunately this already made into the API and using something like variadic parameters to implement optional arguments isn't a good idea :( It should've been an attribute of the ``PullImageOptions``, but now it's too late :/

As a workaround, users usually use an empty ``AuthConfiguration`` to indicate an unauthenticated pull.
