### ISSUE TITLE
Is there any update plan to newer API version?

### ISSUE THREAD

**Issue by airking05** [fsouza/go-dockerclient#714]
Hi :). It seems that we can apply some client code to newer API version e.g. 1.36.

https://docs.docker.com/engine/api/v1.36/

https://github.com/fsouza/go-dockerclient/blob/fac48ffdefb84ad6326eb23ea277e7ca8175b99e/client.go#L58-L61

**Comment by fsouza** [comment]
Hey @airking05, those variables are used when we need to create some kind of condition based on the API version. go-dockerclient is intended to always support the latest version of Docker Engine API, but there's some lagging feature-wise.
