### ISSUE TITLE
Support for server-side rollback

### ISSUE THREAD

**Issue by mavogel** [fsouza/go-dockerclient#716]
According to [API-v1.35](https://docs.docker.com/engine/api/v1.35/#operation/ServiceUpdate) for service updates there is a new parameter to handle server-side updates.

The struct needs to be adapted as follows:
```go
type UpdateServiceOptions struct {
	Auth AuthConfiguration `qs:"-"`
	swarm.ServiceSpec
	Context context.Context
	Version uint64
        Rollback string
}
```

**Comment by mavogel** [comment]
thx @fsouza for the blazingly fast solving of the issue 😃  🚀  Will be merged in `tf` soon with https://github.com/terraform-providers/terraform-provider-docker/pull/44

**Comment by fsouza** [comment]
@mavogel thank you  for reporting it! :D
