### ISSUE TITLE
Support for forcefully remove volumes

### ISSUE THREAD

**Issue by mavogel** [fsouza/go-dockerclient#717]
According to [API-v1.35](https://docs.docker.com/engine/api/v1.35/#operation/VolumeDelete) for volumes deletion, there is a new parameter to forcefully remove docker volumes

The method needs to be adapted:
```go
type RemoveVolumeOptions struct {
	Name       string
	force     boolean
}

func (c *Client) RemoveVolume(opts RemoveVolumeOptions) error {
...
}
```

**Comment by fsouza** [comment]
Oh no :-( That would be a breaking change, so we need to create something like ``RemoveVolumeWithOptions`` (matching  the ``*WithContext`` methods)  or ``RemoveVolumeEx`` (matching ``SearchImagesEx``).

I think``RemoveVolumeWithOptions`` makes more sense, so I'm gonna make this change and create this new method.

**Comment by mavogel** [comment]
Yep true, didn't consider the breaking change. Thx for implementing it. Next time I'll do a PR ;-)
