### ISSUE TITLE
Does it support docker's content trust feature in PullImage() function?

### ISSUE THREAD

**Issue by linggao** [fsouza/go-dockerclient#721]
1. If DOCKER_CONTENT_TRUST=1 environmetal variable is set up, does the PullIamge() only get the signed images as `docker pull`?
2. `docker pull` supports a flag` --disable-content-trust=false/true`, does the PullImage() function support this option?

**Comment by fsouza** [comment]
hey @linggao, sorry for such a delayed response. go-dockerclient doesn't support content trust feature at the moment, this is only implemented in the Docker CLI.
