### ISSUE TITLE
go routine leak from AddEventListener

### ISSUE THREAD

**Issue by houqp** [fsouza/go-dockerclient#723]
Hi,

I noticed we always get a dangling go routine running after calling `AddEventListener` then `RemoveEventListener`. The dangling go routine is created at https://github.com/fsouza/go-dockerclient/blob/master/event.go#L327. Is there anyway to tell that go routine to exit gracefully?

**Comment by fsouza** [comment]
@houqp thanks for reporting. This can definitely be worked out. Can you provide more details on how to reproduce the issue? Are you calling ``RemoveEventListener`` right after ``AddEventListener``?

**Comment by houqp** [comment]
Yes, you should be able to repro by calling RemoveEventListener right after AddEventListener.

**Comment by fsouza** [comment]
@houqp cool, thanks for confirming! I'll adjust the code to make sure this issue doesn't happen!
