### ISSUE TITLE
Error in running startexec

### ISSUE THREAD

**Issue by Sriharsha-reddy** [fsouza/go-dockerclient#734]
Hi,
I have recently started using go-dockerclient. All the args should be passed as a command.
This code works fine if WorkingDir is not mentioned in createExecConfig.
```
	createExecConfig := docker.CreateExecOptions{
			Container:    containerName,
			AttachStdin:  true,
			AttachStdout: true,
			AttachStderr: true,
			Tty:          true,
			WorkingDir: "/",
			Cmd:          [] string{"bash", "-c", strings.Join(args, " ")},
		}
		execObj, err := client.CreateExec(createExecConfig)
		if err != nil {
			fmt.Errorf("failed to create command")
		}

		var stdout, stderr bytes.Buffer
		startExecConfig := docker.StartExecOptions{
			OutputStream: &stdout,
			ErrorStream:  &stderr,
			InputStream:  os.Stdin,
			RawTerminal:  true,
		}
		err = client.StartExec(execObj.ID, startExecConfig)`
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x159ff98]

```
Error in err = client.StartExec(execObj.ID, startExecConfig)

I have tried removing the Workingdir from createExecOptions and it works.

**Comment by fsouza** [comment]
@Sriharsha-reddy can you post the full panic stack trace? Also, are you seeing the message "failed to create command"?

**Comment by harshareddy2020** [comment]
@fsouza Thank you very much for responding. This was because the code was inside a function and i was not throwing the error instead printing it out.

**Comment by fsouza** [comment]
Thanks for confirming. Please feel free to open new tickets or re-open this one if you feel like it :)
