### ISSUE TITLE
HostConfig is missing Runtime option

### ISSUE THREAD

**Issue by nneonneo** [fsouza/go-dockerclient#739]
I need to use an alternate runtime in one of my containers, and I found that `go-dockerclient` lacks the `Runtime` option for HostConfig. This is a documented option in the API: https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate. Can we get the Runtime option added to HostConfig?

**Comment by fpgeek** [comment]
@fsouza the `Runtime` option must be in `HostConfig` not in `Config`. Please fix that.

**Comment by fsouza** [comment]
Ohh my bad x(
