### ISSUE TITLE
Question: Howto get stats for a container NOT as Stream?

### ISSUE THREAD

**Issue by anthraxn8b** [fsouza/go-dockerclient#740]
This is the definition in docker:

https://docs.docker.com/engine/api/v1.30/#operation/ContainerStats
"[...] query Parameters [...] stream [...] Stream the output. If false, the stats will be output once and then it will disconnect. [...]"

I cannot find this option at `client.Stats(docker.StatsOptions{ID:id,Stream:false})` because there is no defined return value (`func (c *Client) Stats(opts StatsOptions) (retErr error) {`).

I am new to GO so please excuse if this is a silly question...

THX in advance!

**Comment by GeorgeMac** [comment]
@anthraxn8b I cannot say I have used this function myself. But my guess would be (based on the docker documentation and this function) that you would be able to set `Stream: false` and expect to receive one single https://godoc.org/github.com/fsouza/go-dockerclient#Stats struct to be sent on the channel you configure within the https://godoc.org/github.com/fsouza/go-dockerclient#StatsOptions struct.

For example:

```go
var id string
stats := make(chan docker.Stats)

go func() {
if err := client.Stats(docker.StatsOptions{ID: id, Stats: stats, Stream:false }); err != nil {
    // handle error
}
}()

stat <- stats
```

The call to `client.Stats(...)` is blocking and needs to happen in a separate goroutine. As per the docs https://godoc.org/github.com/fsouza/go-dockerclient#Client.Stats

The resulting `stat` should be one single response and `client.Stats` should unblock and exit once your receive it.
