### ISSUE TITLE
Automatically set proxy environment variables in containers

### ISSUE THREAD

**Issue by xrayrey** [fsouza/go-dockerclient#754]
Hi all,

Is there a way to automatically set the proxy environment variables inside containers started with go-dockerclient? This is supported by the docker client as shown here: https://docs.docker.com/network/proxy/#configure-the-docker-client

Thanks!

**Comment by fsouza** [comment]
Hey @xrayrey, thanks for opening this issue. This is not supported, you'd need to set the proxy environment variables when calling ``CreateContainer``.
