### ISSUE TITLE
Get the container id that the go app is currently running

### ISSUE THREAD

**Issue by marioarizaj** [fsouza/go-dockerclient#755]
I was wandering if there is a way to detect in the code level the currently running container of the application and restart it in a given case. 
The container is created through the docker build and run commands, not in code level.

**Comment by fsouza** [comment]
Hi @marioarizaj. I don't think docker offers an API for that and you'd need to mount the docker socket inside the container, which is usually not a good thing to do with untrusted containers (not sure if that's your case).

Alternatively, you could kill the process and docker will restart the container if you're using the correct restart policy.

**Comment by marioarizaj** [comment]
@fsouza Thank you for your fast response :)
