### ISSUE TITLE
create container failed: Post http://unix.sock/containers/create?name=...: dial unix /var/run/docker.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by GingerMoon** [fsouza/go-dockerclient#769]
Dear contributors,
I am trying to deploy [Hyperledger Fabric sample ](https://hyperledger-fabric.readthedocs.io/en/latest/build_network.html) into multi hosts and got this error when creating a container from within a container.
This issue happens on the hosts Boot2Docker 18.09.0 (TCL 8.2.1) and  CentOS Linux 7 (Core)-Kernel Version: 3.10.0-514.el7.x86_64.

Would you please tell me why this error message happens? 
``
create container failed: Post http://unix.sock/containers/create?name=dev-peer0.org2.example.com-mycc-1.0: dial unix /var/run/docker.sock: connect: no such file or directory {"imageName": "dev-peer0.org2.example.com-mycc-1.0-15b571b3ce849066b7ec74497da3b27e54e0df1345daff3951b94245ce09c42b", "containerName": "dev-peer0.org2.example.com-mycc-1.0"}
``

**Comment by GingerMoon** [comment]
this issue disappeared somehow....

**Comment by GingerMoon** [comment]
@fsouza I am sorry that I created so many issues... 
I just knew it. I had thought it's an issue of front-end js displaying 1 issue multiple times...
I guess it's because I refresh the page several times when creating the issue.
Sorry again.

**Comment by fsouza** [comment]
@GingerMoon no worries, it happens! Just to confirm, you're no longer having the issue, right?
