### ISSUE TITLE
StatusNotFound is not enough for verifying the ErrNoSuchImage

### ISSUE THREAD

**Issue by shiyuleixia** [fsouza/go-dockerclient#770]
if e, ok := err.(*Error); ok {
		if e.Status == http.StatusNotFound {
			return nil, ErrNoSuchImage
		}

this part should also justify the exact error message ,such as this:
if e.Status == http.StatusNotFound && strings.Contains(e.Message, "No such image")

because it the network resource is not exist ,the docker daemon service also response StatusNotFound

**Comment by fsouza** [comment]
dup of #528, but thanks for reporting, I had forgotten about this.
