### ISSUE TITLE
Question: Do you have a plan to support ssh?

### ISSUE THREAD

**Issue by skanehira** [fsouza/go-dockerclient#772]
I want to use ssh client to connect docker engine but it seems not support ssh now.
Do you have a plan to support ssh?

**Comment by fsouza** [comment]
Hey @skanehira, sorry for the delayed response. This is out of scope for this package, you'd probably need to wrap it with some ssh client library.

**Comment by skanehira** [comment]
@fsouza 
Thanks :)

**Comment by stokito** [comment]
Duplicate of #815

**Comment by alexpts** [comment]
Are there any improvements?
