### ISSUE TITLE
can't go get github.com/fsouza/go-dockerclient

### ISSUE THREAD

**Issue by gmorse81** [fsouza/go-dockerclient#773]
I've been trying to figure this out for a while. wondering if anyone has a solution for this issue. 
When i try to `go get github.com/fsouza/go-dockerclient`, i get the below error. From what i can tell, one of the dependencies of this package is importing Sirupsen/logrus (with a capital S).

I don't see any other issues opened on this repo for the issue, so i assume im just missing something. I've found a number of other issues on github about this, but none of them point to a workaround.

I am using go version go1.11.5 darwin/amd64

go get github.com/fsouza/go-dockerclient
go: finding github.com/docker/docker/opts latest
go: finding github.com/docker/docker/api/types/swarm latest
go: finding github.com/docker/docker/pkg/stdcopy latest
go: finding github.com/docker/docker/pkg/fileutils latest
go: finding github.com/docker/docker/pkg/homedir latest
go: finding github.com/docker/docker/pkg/pools latest
go: finding github.com/docker/docker/pkg/system latest
go: finding github.com/docker/docker/pkg/idtools latest
go: finding github.com/docker/docker/api/types/registry latest
go: finding github.com/docker/docker/pkg latest
go: finding github.com/docker/docker/api/types latest
go: finding github.com/docker/docker/api latest
go: finding golang.org/x/net/context latest
go: finding golang.org/x/net latest
go: downloading golang.org/x/net v0.0.0-20190206173232-65e2d4e15006
go: github.com/Sirupsen/logrus@v1.3.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements

**Comment by fsouza** [comment]
Hi @gmorse81, thanks for reporting. Do you have a ``go.mod`` file? Can you share it? It may be some dependency that isn't playing well.

It works fine on a newly initiated module:

```
root@0ff86cce8603:/tmp/aa# go mod init aa
go: creating new go.mod: module aa
root@0ff86cce8603:/tmp/aa# go get github.com/fsouza/go-dockerclient
go: finding github.com/fsouza/go-dockerclient v1.3.5
go: finding github.com/Microsoft/go-winio v0.4.11
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/docker/libnetwork v0.8.0-dev.2.0.20180608203834-19279f049241
go: finding github.com/docker/go-connections v0.4.0
go: finding github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: finding github.com/opencontainers/runc v0.1.1
go: finding github.com/gogo/protobuf v1.2.0
go: finding golang.org/x/sys v0.0.0-20190109145017-48ac38b7c8cb
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding gotest.tools v2.2.0+incompatible
go: finding github.com/containerd/continuity v0.0.0-20181203112020-004b46473808
go: finding github.com/ijc/Gotty v0.0.0-20170406111628-a8b993ba6abd
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding golang.org/x/crypto v0.0.0-20190103213133-ff983b9c42bc
go: finding github.com/gorilla/context v1.1.1
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/vishvananda/netlink v1.0.0
go: finding github.com/docker/docker v0.7.3-0.20190111153827-295413c9d0e1
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/vishvananda/netns v0.0.0-20180720170159-13995c7128cc
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/sirupsen/logrus v1.3.0
go: finding github.com/gorilla/mux v1.6.2
go: finding github.com/docker/go-units v0.3.3
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding github.com/stretchr/objx v0.1.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/stretchr/testify v1.2.2
go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: downloading github.com/fsouza/go-dockerclient v1.3.5
go: downloading github.com/docker/docker v0.7.3-0.20190111153827-295413c9d0e1
go: downloading golang.org/x/sys v0.0.0-20190109145017-48ac38b7c8cb
go: downloading github.com/docker/go-units v0.3.3
go: downloading github.com/ijc/Gotty v0.0.0-20170406111628-a8b993ba6abd
go: downloading github.com/sirupsen/logrus v1.3.0
go: downloading github.com/gogo/protobuf v1.2.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/libnetwork v0.8.0-dev.2.0.20180608203834-19279f049241
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/opencontainers/runc v0.1.1
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/containerd/continuity v0.0.0-20181203112020-004b46473808
go: downloading golang.org/x/crypto v0.0.0-20190103213133-ff983b9c42bc
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
```

**Comment by gmorse81** [comment]
Your comment got me thinking and i was able to resolve the issue. For those reading this, i had to delete the contents of go/pkg/mod 

i was then able to get everything working.
