### ISSUE TITLE
Ports not being opened

### ISSUE THREAD

**Issue by ciokan** [fsouza/go-dockerclient#775]
I have this config for a container but it only opens the `tcp` port:

    ...
	StartConfig: docker.HostConfig{
		PortBindings: map[docker.Port][]docker.PortBinding{
			"53/tcp": {{HostIP: "0.0.0.0", HostPort: "1053"}},
			"53/udp": {{HostIP: "0.0.0.0", HostPort: "1053"}},
		},

I tried in every possible way without luck. When I run the container using the cmd it works as expected:

```
docker run -d \
	-p 0.0.0.0:1053:53/udp \
	-p 0.0.0.0:1053:53/tcp ...
```

Any ideas what am I doing wrong here?

**Comment by fsouza** [comment]
Hey @ciokan, sorry I missed this. Were you able to figure out what was going on?

**Comment by ciokan** [comment]
yes, I forgot to expose the udp port in my dockerfile
