### ISSUE TITLE
install with modules throws a undefined error

### ISSUE THREAD

**Issue by arxdsilva** [fsouza/go-dockerclient#777]
Hi, I'm adding go modules to our org and after running the conventionals `go mod init/tidy` and trying to install it, this error showed up. I've looked up go-dockerclient and everthing seems to be on the right places but It still wont work.

```
➜  jobs git:(master) ✗ go install 
# github.com/fsouza/go-dockerclient/internal/archive
../../../../pkg/mod/github.com/fsouza/go-dockerclient@v1.4.0/internal/archive/archive.go:73:19: undefined: idtools.Identity
```

**Comment by fsouza** [comment]
@arxdsilva can you share your ``go.mod``?

**Comment by arxdsilva** [comment]
```
module github.com/levpay/jobs

go 1.12

require (
	github.com/DATA-DOG/go-sqlmock v1.3.3
	github.com/gofn/gofn v0.0.0-20181211161442-6c6d4df46796
	github.com/jmoiron/sqlx v1.2.0
	github.com/nuveo/beanstalk v0.0.0-20180807173258-dbe89e4c117f
	github.com/nuveo/log v0.0.0-20180612162145-f88607104ac8
	github.com/prest/adapters v0.0.0-20190405151647-53750aa8ac63
)
```

**Comment by fsouza** [comment]
Can you share the output of ``go mod graph`` or look into the line equivalent to ``github.com/docker/docker`` in ``go.sum``?

If you have private import paths that you'd rather not share, can you try to create a small reproducer? I can give it a shot later today as well.

**Comment by arxdsilva** [comment]
sure, gimme a sec

**Comment by fsouza** [comment]
Oh I see, so the problem here is that your package depends directly on docker/docker and somehow it's pulling an old version of Docker instead of the one specified in go-dockerclient's go.mod :thinking: I don't see docker/docker in your go.mod, so :man_shrugging:?

Can you try ``go get github.com/docker/docker@v0.7.3-0.20190309235953-33c3200e0d16``?

**Comment by arxdsilva** [comment]
Thank you @fsouza, It worked perfectly!
