### ISSUE TITLE
How to set a memory limit?

### ISSUE THREAD

**Issue by drrford** [fsouza/go-dockerclient#785]
Hello. I'm trying to create container with following host configuration:
```
hconf := docker.HostConfig{Mounts: mounts, Memory: 32000}
```
Here I'm trying to allocate 32 MB of RAM for a container, but I get this error:
**panic: API error (400): Minimum memory limit allowed is 4MB**

**Comment by fsouza** [comment]
@drrford hey there, the Memory field is specified in bytes, you need to set it to ``32000000``.
