### ISSUE TITLE
Do you have an  alternative for --sysctl flag?

### ISSUE THREAD

**Issue by twelfthdoctor** [fsouza/go-dockerclient#788]
Hello. How can I  translate the following command into code?
``` docker run --sysctl net.ipv4.ip_unprivileged_port_start=0 someimage ```
How can I pass some arguments to sysctl via your client?

**Comment by fsouza** [comment]
Hi @twelfthdoctor. Yes, you can set Sysctls in Hostconfig: https://godoc.org/github.com/fsouza/go-dockerclient#HostConfig

```go
hostConfig := HostConfig {
  Sysctls: map[string]string{"net.ipv4.ip_unprivileged_port_start": "0"},
}
```
