### ISSUE TITLE
can't find pkg github.com/docker/docker

### ISSUE THREAD

**Issue by zhcppy** [fsouza/go-dockerclient#801]
➜  go get -v github.com/docker/docker@v1.4.2        
go: finding github.com/docker/docker v1.4.2
Fetching https://github.com?go-get=1
https fetch failed: Get https://github.com?go-get=1: net/http: TLS handshake timeout
go get github.com/docker/docker@v1.4.2: unknown revision v1.4.2

**Comment by fsouza** [comment]
Hi @zhcppy, thanks for opening this issue. Can you provide steps for reproducing or share your go.mod file? go-dockerclient doesn't depend on docker/docker@v1.4.2, so that dependency may be coming from somewhere else.

**Comment by zhcppy** [comment]
Thank you @fsouza, I am so sorry! I got it wrong. I should use `GO111MODULE=on go get -v github.com/docker/docker@v1.4.2-0.20190710153559-aa8249ae1b8b`
