### ISSUE TITLE
github.com/ijc/Gotty is unmaintained...

### ISSUE THREAD

**Issue by onlyjob** [fsouza/go-dockerclient#804]
[github.com/ijc/Gotty](https://github.com/ijc/Gotty) is unmaintained, according to https://github.com/Nvveen/Gotty/issues/5.

It is used only in one place: https://github.com/fsouza/go-dockerclient/blob/master/internal/jsonmessage/jsonmessage.go#L17

Any alternatives?

**Comment by fsouza** [comment]
Hey @onlyjob, what issue are you running into?

I can go look for something else or vendor gotty into go-dockerclient/fix the issue, but I'd like to understand what's going on first.

**Comment by onlyjob** [comment]
Just a concern regarding life cycle and dependency hygiene. :)

Basically there is no `github.com/ijc/Gotty` on Debian and introducing unmaintained library as a standalone/reusable package is not a good idea... Without `github.com/ijc/Gotty` recent releases of _go-dockerclient_ FTBFS...

For now I could probably do something like 

~~~~
--- golang-github-fsouza-go-dockerclient-1.4.4.orig/client.go
+++ golang-github-fsouza-go-dockerclient-1.4.4/client.go
@@ -33,7 +33,7 @@ import (

        "github.com/docker/docker/pkg/homedir"
        "github.com/docker/docker/pkg/stdcopy"
-       "github.com/fsouza/go-dockerclient/internal/jsonmessage"
+       "github.com/docker/docker/pkg/jsonmessage"
 )

 const (
~~~~

but I think it would be better to address the root cause which is dependency on "dead" (unmaintained) code...

**Comment by fsouza** [comment]
Gotcha. Will fix.

**Comment by onlyjob** [comment]
Thanks. :)
