### ISSUE TITLE
Getting undefined: homedir.Get

### ISSUE THREAD

**Issue by lsascha** [fsouza/go-dockerclient#809]
When i try to compile a tool now i get the following error:
/go/src/github.com/fsouza/go-dockerclient/client.go:1105:12: undefined: homedir.Get

Not sure if it is the reason but it seems the namespace of the library now instead of docker/docker is moby/moby

**Comment by lsascha** [comment]
ok. sorry i am still new to golang etc.
I think the issue is only happening when compiling for Mac OS (i am compiling it on linux with `env GOARCH=amd64 GOOS=darwin go build -v -o ../../project.darwin.amd64`)

**Comment by lsascha** [comment]
I think i got a bit further.

It seems the issue is this change:

https://github.com/moby/moby/commit/023b072288eab3c9e768d4aeeb917f27f06034c7#diff-1b2f13bed97df1999bf7f922eb2f0909

when i remove `,osuergo` in the first line, it compiles without error.

**Comment by lsascha** [comment]
got it solved. using the build tag `osusergo` solves the issue. :)
`env GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build -tags osusergo -v -o ../../project.darwin.amd64`
So nothing to do here except learning about golang.

**Comment by cybe** [comment]
I was running into this issue as well, so thank you for posting the solution :)
