### ISSUE TITLE
Which is this SDK support max api version?  

### ISSUE THREAD

**Issue by lycclsltt** [fsouza/go-dockerclient#813]
Hi, I want to ask a question about api version. Now which is the max api version that this sdk can support ?

**Comment by lycclsltt** [comment]
hi

**Comment by lycclsltt** [comment]
I want use Docker 19 and Docker Server API version is 1.40.  Dose it support ?

**Comment by fsouza** [comment]
1.40 should work, but as noted in the README, feel free to open an issue or PR if anything is missing! :D

**Comment by lycclsltt** [comment]
Thanks!
