### ISSUE TITLE
do-dockerclient's version is equal to docker server api version ?

### ISSUE THREAD

**Issue by lycclsltt** [fsouza/go-dockerclient#814]

**Comment by fsouza** [comment]
See note in the readme (https://github.com/fsouza/go-dockerclient#difference-between-go-dockerclient-and-the-official-sdk):

> New features in the Docker API do not get automatically implemented here: it's based on
> demand, if someone wants it, they can file an issue or a PR and the feature may get
> implemented/merged.

Let me know if you have other questions!
