### ISSUE TITLE
Docker SSH client?

### ISSUE THREAD

**Issue by elasti-liranm** [fsouza/go-dockerclient#815]
Hi,
Any plans to add an SSH client to docker lib?
From 18.09 users can connect to the docker daemon using SSH password less

**Comment by fsouza** [comment]
hey @elasti-liranm, there aren't any plans at the moment. Will reopen the issue. I apologize for the bot getting in your way, I was a out for a little bit.

**Comment by vitalii-buchyn-exa** [comment]
hello community,

sorry, is this feature still in roadmap?

thanks
