### ISSUE TITLE
Correctly identify LCOW

### ISSUE THREAD

**Issue by jlarriba** [fsouza/go-dockerclient#830]
Hi,

Docker 19.03 on Windows Server 2019 supports running Linux Containers On Windows (lcow) and Windows Containers side by side on a transparent way.

The information gathered by this library does not report correctly the OSType in client.Info() when running lcow on Windows Server 2019: it always reports "windows" even if the Docker image is Linux.

Is it possible to report the Linux images correctly?

Thank you!

**Comment by fsouza** [comment]
Hi @jlarriba, thanks for opening this issue. I don't have access to a Windows server, unfortunately :(

What's the output of running `docker info` in that host? Thanks!

**Comment by jlarriba** [comment]
Hi @fsouza,

here is the output:

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 13
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.999GiB
 Name: WIN-DOCKER
 ID: 3Y2A:AWVD:FETC:2274:LOYP:AFGL:VCOS:G2N5:GIIX:AHCT:GVWU:MJL7
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

I don´t think that this gives any information on the running container. However, when I run a Linux Nginx container in Windows, docker inspect returns:

```
[
    {
        "Id": "b8d89bc49fe5edcca4ecef9209ebbdcd5c1ff0f6352a82b24d9b1ce7bf99b816",
        "Created": "2020-05-01T14:21:05.146583Z",
        "Path": "nginx",
        "Args": [
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
...
        },
        "Image": "sha256:602e111c06b6934013578ad80554a074049c59441d9bcd963cb4a7feccede7a5",
...
        "Name": "/busy_tesla",
        "RestartCount": 0,
        "Driver": "lcow",
        "Platform": "linux",
...

```
I have realized that I could Inspect using your API, and check for the "Platform" of the container:

```
c, _ := client.InspectContainer(container.ID)
fmt.Println("Platform: " + c.Platform)
```
If it is a linux container, the Platform is "linux". If it is windows, the Platform is "windows".

This is what I needed, so this issue can be closed :)

Thank you very much for your attention.

**Comment by fsouza** [comment]
Nice, glad to help! 😁 

Let me know if the Info struct is missing anything and we can fix it.
