### ISSUE TITLE
Node label update failed

### ISSUE THREAD

**Issue by eumme92** [fsouza/go-dockerclient#835]
Hello, I tried to update the node:
<pre><code>opts := map[string]string{"available_mem_gb": strconv.Itoa(45)}
update := docker.UpdateNodeOptions{
		NodeSpec: swarm.NodeSpec{
			Annotations: swarm.Annotations{
				Labels: opts,
			},
		},
	}
return client.UpdateNode(id, update)
</code></pre>

but I got this error:
<pre><code>error=API error (400): invalid Role: ""
</pre></code>

**Comment by fsouza** [comment]
Hi @eumme92, thanks for opening this issue. Do you have any logs from the server? I wonder if the API has changed and there's a new parameter or something like that.
