### ISSUE TITLE
Docker Events Any Loss possible ?

### ISSUE THREAD

**Issue by FLavalliere** [fsouza/go-dockerclient#859]
Hello,

I've using another project called 'registrator'. I've created my own version out of if with some more features.

```
     // Start event listener before listing containers to avoid missing anything
        events := make(chan *dockerapi.APIEvents)
        assert(docker.AddEventListener(events))
        log.Println("Listening for Docker events ...")
        
  // Process Docker events
        for msg := range events {
            ..
        }
```

Somehow it seems i might not receive all events from the docker deamon. Would you know any resaons ?

**Comment by FLavalliere** [comment]
Funny enough i'm also doing something like this :

```
       taskArnFilter := fmt.Sprintf("com.amazonaws.ecs.task-arn=%s", taskArn)
       log.Printf("Syncing services container id : %s and matching %s", ignoreId, taskArnFilter)
       arnFilters := map[string][]string{"label": {taskArnFilter}}
       containers, err := b.docker.ListContainers(dockerapi.ListContainersOptions{Filters: arnFilters})
```

Somehow it only return my own containers though the docker daemon should have two... if i dun the docker ps with the same filter it gives me two entries not 1

Not too sure if it might be a docker bug itself? or something else with listening at events..

**Comment by FLavalliere** [comment]
I've updated the code to  use AddListenerWithOptions and to only filter events that is of type

container with events of start,stop,kill, .... so this way it doesnt get into the 1000 lines limits... who knows :/

**Comment by fsouza** [comment]
Hey @FLavalliere, apologies for neglecting this issue. To be honest, I don't know if it's possible or not to lose events. Can you reproduce the issue you were seeing using just the docker cli, or provide a reproducible code snippet that I could use to try and test?
