### ISSUE TITLE
Tags delimited by colon, not @ ?

### ISSUE THREAD

**Issue by adibsaad** [fsouza/go-dockerclient#861]
Hi,

In this line https://github.com/fsouza/go-dockerclient/blob/91f5ca9986fa650a01849441d9a60e5e681bb908/image.go#L322 I noticed you are extracting the tag by splitting on the `@` character, but aren't tags separated by `:` e.g. `ubuntu:latest` or am I missing something here?

I found this issue when I was debugging another issue related to https://github.com/moby/moby/issues/42053

Thanks.

**Comment by fsouza** [comment]
Hi @adibsaad, tags are delimited by `:` the digest is delimited by `@`. The Docker API overloads the "tag" parameter with both the tag and the digest: https://docs.docker.com/engine/api/v1.41/#operation/ImageCreate

**Comment by thaJeztah** [comment]
Perhaps it would make sense to add an `PullImageOptions.All`  option (similar to [api/types/client.go#L252-L254](https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/client.go#L252-L254)

https://github.com/fsouza/go-dockerclient/blob/91f5ca9986fa650a01849441d9a60e5e681bb908/image.go#L293-L296


`client.PullImage()` could produce an error if neither the `All` option, nor `Tag` are set; https://github.com/fsouza/go-dockerclient/blob/91f5ca9986fa650a01849441d9a60e5e681bb908/image.go#L313

**Comment by adibsaad** [comment]
Thanks @fsouza , I'd forgotten about this.

**Comment by fsouza** [comment]
@adibsaad me too lol Thank the bot haha
