### ISSUE TITLE
FilteredListNetworks should take new filter format too

### ISSUE THREAD

**Issue by linggao** [fsouza/go-dockerclient#863]
Currently this FilteredListNetworks function takes option with format `map[string]map[string]bool`. However, the latest docker API uses `map[string][]string` format for filters: https://docs.docker.com/engine/api/v1.41/#tag/Network. This function returns an empty array for some "docker compatible" engine. So FilteredListNetworks function should support the latest API spec. We recommend that it supports both format.

**Comment by fsouza** [comment]
I agree we should keep supporting both format. Thanks for opening this issue!

**Comment by linggao** [comment]
Any idea when it will be supported?

**Comment by fsouza** [comment]
Hi @linggao, thanks for the comment. No plans on my side, would need a PR for this. I imagine the preferred approach would be to add another method that takes the new filter format (and probably a dedicated struct, to support extending in the future).
