### ISSUE TITLE
README guidance is correct???

### ISSUE THREAD

**Issue by cameronelliott** [fsouza/go-dockerclient#877]
Hey, this looks like a lovingly maintained repo. Very nice.

But, the README says this:
> For new projects, using the official SDK is probably more appropriate as go-dockerclient lags behind the official SDK.

Which is sort of a shocker, if you go review the official SDK:
https://github.com/docker/go-docker/

It has a total of seven commits, and the last was nearly four years ago.

Any thoughts if this still applies??

Thanks

**Comment by fsouza** [comment]
Ohh I didn't even know that repo existed, Docker should get rid of it.

The SDK is located within their "mono" repo: https://pkg.go.dev/github.com/docker/docker/client

**Comment by cameronelliott** [comment]
I think I am confused also by the renaming of Docker to Moby,
I guess the official client is actually here when browsing Github:
https://github.com/moby/moby/tree/master/client

**Comment by fsouza** [comment]
> I think I am confused also by the renaming of Docker to Moby,
> I guess the official client is actually here when browsing Github:
> https://github.com/moby/moby/tree/master/client
> 
> 

Correct, they renamed the repository, but didn't change the import paths. So the code is at moby/moby, but you still import it as docker/docker.
