### ISSUE TITLE
Dependency on docker is not compatible with freebsd/amd64

### ISSUE THREAD

**Issue by illarion** [fsouza/go-dockerclient#878]
This specific file is not able to compile:
https://github.com/moby/moby/blob/v20.10.8/pkg/system/mknod.go

```
GOOS=freebsd GOARCH=amd64 go build 
# github.com/docker/docker/pkg/system
../../go/pkg/mod/github.com/docker/docker@v20.10.8+incompatible/pkg/system/mknod.go:12:19: cannot use dev (type int) as type uint64 in argument to unix.Mknod
```

**Comment by fsouza** [comment]
🤔 need to track down how we're getting to that package or if docker is willing to fix it.

**Comment by illarion** [comment]
The most frustrating part is that mknod.go is not used by go-dockerclient by design, but there is no way to exclude it

**Comment by fsouza** [comment]
Yeah I looked into it a bit, it looks like we get it via `github.com/docker/docker/pkg/archive`.

I opened moby/moby#42849 to see if the folks over there would be open for a PR fixing it on their side. If not, we may need to vendor that package or something like that.

**Comment by Moonshine-cc** [comment]
https://github.com/tendermint/starport/issues/2042

**Comment by fsouza** [comment]
@Moonshine-cc I just pushed [go-dockerclient@v1.7.8](https://pkg.go.dev/github.com/fsouza/go-dockerclient@v1.7.8) and that should compile on freebsd now. I also added a job to cross compile in CI, it isn't as good as running the tests in freebsd, but at least we can guarantee no regression. Let me know if you need any info.
