### ISSUE TITLE
Security scan shows vulnerabilities in dependencies

### ISSUE THREAD

**Issue by Polber** [fsouza/go-dockerclient#885]
The following dependencies show 1 or more severe security vulnerabilities:

* github.com/gorilla/websocket:1.4.0
* github.com/coreos/etcd:3.3.10+incompatible

These package versions should be removed or updated to the latest safe versions.

**Comment by fsouza** [comment]
This has been fixed.

**Comment by linggao** [comment]
@fsouza This issue has not been fixed yet. The go.sum file still show these 2 versions are referenced.
````
github.com/gorilla/websocket:1.4.0
github.com/coreos/etcd:3.3.10+incompatible
````

https://github.com/fsouza/go-dockerclient/blob/main/go.sum#L353
https://github.com/fsouza/go-dockerclient/blob/main/go.sum#L193

Could you please re-open this issue?

**Comment by fsouza** [comment]
@linggao can you check the output of your `go mod graph` to confirm that you're getting those modules in your binary?

**Comment by linggao** [comment]
@fsouza Here is the list of dependencies from `go mod graph`. I think the problem is from the version of containerd that go-dockerclient depends. 
````
github.com/open-horizon/anax github.com/fsouza/go-dockerclient@v1.7.9
github.com/fsouza/go-dockerclient@v1.7.9 github.com/containerd/containerd@v1.5.9
github.com/containerd/containerd@v1.5.9 github.com/containerd/continuity@v0.1.0
github.com/containerd/continuity@v0.1.0 github.com/spf13/cobra@v1.0.0
github.com/spf13/cobra@v1.0.0 github.com/spf13/viper@v1.4.0
github.com/spf13/viper@v1.4.0 github.com/coreos/etcd@v3.3.10+incompatible
````

````
github.com/open-horizon/anax github.com/fsouza/go-dockerclient@v1.7.9
github.com/fsouza/go-dockerclient@v1.7.9 github.com/containerd/containerd@v1.5.9
github.com/containerd/containerd@v1.5.9 github.com/containerd/continuity@v0.1.0
github.com/containerd/continuity@v0.1.0 github.com/spf13/cobra@v1.0.0
github.com/spf13/cobra@v1.0.0 github.com/spf13/viper@v1.4.0
github.com/spf13/viper@v1.4.0 github.com/gorilla/websocket@v1.4.0
````

**Comment by fsouza** [comment]
Keep it
