### ISSUE TITLE
`authCheck` does not have context

### ISSUE THREAD

**Issue by eyJhb** [fsouza/go-dockerclient#887]
`authCheck` should have the ability to specify `context.Context`, so that the operation can be cancelled.

**Comment by fsouza** [comment]
To avoid a breaking change we should probably introduce a new method, `AuthCheckWithContext` and deprecate `AuthCheck`.

**Comment by eyJhb** [comment]
Go away bot.

**Comment by fsouza** [comment]
Keep it
