### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by buchdag** [fsouza/go-dockerclient#891]
Hi.

Do you plan to tag a new release with updated dependencies soon ?

I'd love to fix GitHub security alerts in [nginx-proxy/docker-gen](https://github.com/nginx-proxy/docker-gen) too 😄

**Comment by fsouza** [comment]
I'll tag one today!

**Comment by fsouza** [comment]
Just pushed 1.7.5, you should be good to go! 😁

**Comment by buchdag** [comment]
Thank you !
