### ISSUE TITLE
Looking for an example of Attach.

### ISSUE THREAD

**Issue by fubarhouse** [fsouza/go-dockerclient#894]
Hey!

I'm looking for a complete example of this library in which a container is started with a command running in the container accepts `stdin` for a given command and detaches itself after a condition, timeout, when the command exits etc...

I found a great example of opening a shell session but I'm wondering how this could be perhaps simplified for this use-case.

I'm actually considering switching out my own home-baked Docker abstraction library for this one - it's quite a nice library!

**Comment by fsouza** [comment]
Hm, iirc if you close stdin it should detach automatically. I can try writing an example some time next week. If you've tried writing it, can you share what you did? Just so I can start from there and add it to the docs. Thank you!

**Comment by fsouza** [comment]
Keep it
