### ISSUE TITLE
How to get the value of NAMES field?

### ISSUE THREAD

**Issue by anyone0034** [fsouza/go-dockerclient#913]
Example command:
###  `$ docker ps`
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS          PORTS                                         `NAMES`
993ed1527eeb   portainer/portainer   "/portainer -H unix:…"   15 minutes ago   Up 12 minutes   0.0.0.0:21999->9000/tcp, :::21999->9000/tcp   `portainer_portainer_1`

I want to get NAMES,`ListImages` interface was not found

### `my go code`

	client, err := docker.NewClient("tcp://192.168.0.84:2375")
	if err != nil {
		panic(err)

	}
	fmt.Println(client.Info())
	imgs, err := client.ListImages(docker.ListImagesOptions{All: false})
	if err != nil {
		panic(err)
	}

	for _, img := range imgs {
		fmt.Println("ID: ", img.ID)
		fmt.Println("RepoTags: ", img.RepoTags)
		fmt.Println("Created: ", img.Created)
		fmt.Println("Size: ", img.Size)
		fmt.Println("VirtualSize: ", img.VirtualSize)
		fmt.Println("ParentID: ", img.ParentID)
		fmt.Println("RepoDigests: ", img.RepoDigests)
		fmt.Println("Labels: ", img.Labels)
	}
### output
ID:  sha256:580c0e4e98b06d258754cf28c55f21a6fa0dc386e6fe0bf67e453c3642de9b8b
RepoTags:  [portainer/portainer:latest]
Created:  1616097222
Size:  79085285
VirtualSize:  79085285
ParentID:  
RepoDigests:  [portainer/portainer@sha256:fb45b43738646048a0a0cc74fcee2865b69efde857e710126084ee5de9be0f3f]
Labels:  map[]

**Comment by fsouza** [comment]
Hi @anyone0034, I imagine you figured it out, but just for anyone that comes here later, the output of `docker ps` is powered by [ListContainers](https://pkg.go.dev/github.com/fsouza/go-dockerclient#Client.ListContainers), not ListImages.
