### ISSUE TITLE
What would be the best way to specify version of docker api, so that go-dockerclient can adjust requests and response expectations accordingly?

### ISSUE THREAD

**Issue by kevintoormimik** [fsouza/go-dockerclient#920]
### Context 

I am creating a shim docker API service i.e., basically the service pretends to be docker and responds like docker. Requests are partially forwarded to docker engine and remainder (container or image related) are forwarded to a different container runtime. 

The piece of software using this shim service uses `go-dockerclient` library.

### Solution tried

I tried to return the version of docker API supported by the shim service as a response to `GET /version` request coming from the `go-dockerclient` lib.

The shim service responded by requesting the actual docker engine for response and replacing values for `response.ApiVersion` and `response.MinAPIVersion` with the supported version (`1.41`).

The solution did not work, can you please confirm if I am missing something, or if there is a better way of doing it

@playground

**Comment by kevintoormimik** [comment]
> Does [NewVersionedClient](https://pkg.go.dev/github.com/fsouza/go-dockerclient#NewVersionedClient) (or some of the variants) work for you?

**Comment by fsouza** [comment]
Hmm, I think this should be an issue/feature-request in anax then.

> Whats the criteria used by go-dockerclient to decide which docker API version to use if NewVersionedClient is not used?

In that case, go-dockerclient doesn't use versioned URLs, which means the latest supported by the remote Docker engine.

**Comment by kevintoormimik** [comment]
Understood. Thank you
