### ISSUE TITLE
Error trying to run ddev start after configure drupal 9 on windows

### ISSUE THREAD

**Issue by rickydj** [fsouza/go-dockerclient#924]
Hi.

Today I have a weird problem working with this plugin, i am using ddev, and it has a dependency with this library, when i try to run ddev start, it hangs with this error message

<code>
panic: interface conversion: *winio.win32Pipe is not interface { CloseWrite() error }: missing method CloseWrite

goroutine 225 [running]:
github.com/fsouza/go-dockerclient.(*Client).hijack.func1.2()
        C:/actions-runner/_work/ddev/ddev/vendor/github.com/fsouza/go-dockerclient/client.go:832 +0xb7
created by github.com/fsouza/go-dockerclient.(*Client).hijack.func1
        C:/actions-runner/_work/ddev/ddev/vendor/github.com/fsouza/go-dockerclient/client.go:826 +0x535

</code>

and I don't know how to handle this.

This happen on an Intel core I5 with 16 GB of ram running windows 10 64 bits

**Comment by fsouza** [comment]
Hey, I'm not familiar with ddev, but from a quick reading, it seems that ddev requires Docker running on the WSL side of things? The fact that this is an error trying to use a Windows pipe makes me think that maybe you're trying to connect to the wrong Docker server? I'm unfortunately also not familiar with Windows / WSL though, so maybe what I'm saying doesn't make much sense.

Any chance you could open an issue with ddev?
