### ISSUE TITLE
How to run a docker container with GPU support?

### ISSUE THREAD

**Issue by alex-litvak** [fsouza/go-dockerclient#927]
We're using [CreateContainer](https://github.com/fsouza/go-dockerclient/blob/003dd2da61e47c5a229f4f1fdd20d37ef6b567fa/container_create.go#L33) function to run a docker container. I need to pass the --gpu argument in order to enable GPU support:
`docker run --gpus all ...`

How can I pass the --gpus option programmatically? Thanks in advance!

**Comment by fsouza** [comment]
Hmm to be honest I'm not totally sure. I think gpus are represented as device requests in the Docker API? Meaning you'd need to set `DeviceRequests` in your [`HostConfig`](https://pkg.go.dev/github.com/fsouza/go-dockerclient#HostConfig). Something like (untested):

```go
hostConfig := HostConfig{
    // other attributes
    DeviceRequests: []DeviceRequest{
        {
            Count: 1,
            Capabilities: [][]string{{"gpu"}},
         },
    },
    // other attributes
}
// use hostConfig to create/start the container
```

(you can also set `Count` to `-1` to make all gpus available)
