### ISSUE TITLE
The module name change issues

### ISSUE THREAD

**Issue by vndroid** [fsouza/go-dockerclient#966]
The original project name is https://github.com/docker/docker.
but now the name is https://github.com/moby/moby,

and some project submodules such as: /xxx/vendor/github.com/fsouza/go-dockerclient/[distribution.go#L11](https://github.com/fsouza/go-dockerclient/blob/main/distribution.go#L11) it has an old path, how to deal with it?

**Comment by fsouza** [comment]
Can you clarify what issues you're facing? When docker renamed the repo to moby, they didn't change the name of the package, which means there's no impact to people importing it.

**Comment by vndroid** [comment]
> Can you clarify what issues you're facing? When docker renamed the repo to moby, they didn't change the name of the package, which means there's no impact to people importing it.

For example, my project introduced [go-dockerclient](https://github.com/fsouza/go-dockerclient) and [moby](https://github.com/moby/moby) as submodules, and now the path to them has changed, but the new path does not contain the original files,

```
ls vendor/github.com/docker/docker/
```

but in fact, the path is

```
ls vendor/github.com/moby/moby/
```

your code [distribution.go](https://github.com/fsouza/go-dockerclient/blob/main/distribution.go#L11)

```
...
	"github.com/docker/docker/api/types/registry"
...
```

if I add the submodule moby, the path doesn't have the file. in fact, its path is `vendor/github.com/moby/moby/api/types/registry`

**Comment by fsouza** [comment]
How are you vendoring the code? Are you using go modules?

For context, the repository docker/docker was renamed to moby/moby in 2017. It happened almost 6 years ago, and it shouldn't affect go-dockerclient's ability to import its code.

**Comment by vndroid** [comment]
> How are you vendoring the code? Are you using go modules?
> 
> For context, the repository docker/docker was renamed to moby/moby in 2017. It happened almost 6 years ago, and it shouldn't affect go-dockerclient's ability to import its code.

Such as this project [docker-ipv6nat](https://github.com/robbertkl/docker-ipv6nat), now the submodule path is `vendor/github.com/docker/docker`, When I delete the submodule and re-add moby submodule, I get an error that the module is not found and I can only modify it by following the old path.

I think this is unreasonable, is there a more perfect solution?

**Comment by fsouza** [comment]
Oh I see you're using Git submodules for vendoring. I strongly recommend migrating to Go modules, but if you'd like to continue using Git submodules, you should just remember to manually clone it under `vendor/github.com/docker/docker`. If you're adding the new submodule, you could do something like:

```
git submodule add https://github.com/docker/docker.git vendor/github.com/docker/docker
```

This alternative would work too:

```
git submodule add https://github.com/moby/moby.git vendor/github.com/docker/docker
```

You just need to make sure that the path is `vendor/github.com/docker/docker`.
